# Lab 1. Tehnici de bază în prelucrarea textelor

## Regex

Expresiile regulate reprezintă un șir de caractere care definesc un șablon⁠ de căutare.

Ele sunt utile pentru căutarea anumitor șabloane în text și de asemenea, pentru normalizarea textelor - https://www.w3schools.com/python/python_regex.asp

In [51]:
import re

text = """
Praise for The Rain in Portugal
 
“Nothing in Billy Collins’s twelfth book . . . is exactly what readers might expect, and that’s the charm of this collection.”—The Washington Post
 
“This new collection shows [Collins] at his finest. . . . Certain to please his large readership and a good place for readers new to Collins to begin.”—Library Journal. 
 
“Disarmingly playful and wistfully candid.”—Booklist
Buy new:$38.65
No Import Fees Deposit & $13.01 Shipping to Romania Details -12.3.
"""

Exemplu de utilizare: utilizând metoda `re.sub` ștergem toate caracterele diferite de literele mari și mici ale alfabetului englez, apoi normalizăm toate secvențele de caractere de tip spațiu consecutive la un singur spațiu.

In [52]:
cleaned_text = re.sub("[^A-Za-z]", " ", text)
cleaned_text = re.sub("\s+", " ", cleaned_text)
print(cleaned_text)

 Praise for The Rain in Portugal Nothing in Billy Collins s twelfth book is exactly what readers might expect and that s the charm of this collection The Washington Post This new collection shows Collins at his finest Certain to please his large readership and a good place for readers new to Collins to begin Library Journal Disarmingly playful and wistfully candid Booklist Buy new No Import Fees Deposit Shipping to Romania Details

Pentru testarea pattern-urilor putem folosi https://regex101.com/.

### Funcția `finditer`

Această funcție găsește un pattern într-un șir de caractere și returnează un iterator ce generează obiecte de tip Match cu toate potrivirile.

In [53]:
import re

s = 'Readability counts.'
pattern = r'[aeoui]'

matches = re.finditer(pattern, s)
for match in matches:
    print(match)

<re.Match object; span=(1, 2), match='e'>
<re.Match object; span=(2, 3), match='a'>
<re.Match object; span=(4, 5), match='a'>
<re.Match object; span=(6, 7), match='i'>
<re.Match object; span=(8, 9), match='i'>
<re.Match object; span=(13, 14), match='o'>
<re.Match object; span=(14, 15), match='u'>

Exemplu: căutăm toate numerele float sau int, împreună cu pozițiile și valorile lor. Aici folosim metode `compile()` pentru a compila expresia regulată sub forma de string într-un pattern de tip regex.

In [ ]:
pattern = re.compile("[+-]?(\d+\.)?\d+")
for match in pattern.finditer(text):
    print(match, "--> valoarea căutată începe de la caracterul nr.", match.start(), ", și este ", match.group())

<re.Match object; span=(418, 423), match='38.65'> --> valoarea căutată începe de la caracterul nr. 418 , și este  38.65
<re.Match object; span=(450, 455), match='13.01'> --> valoarea căutată începe de la caracterul nr. 450 , și este  13.01
<re.Match object; span=(484, 489), match='-12.3'> --> valoarea căutată începe de la caracterul nr. 484 , și este  -12.3

## Encodings

Codificarea (encoding-ul) unui text poate varia, în funcție de limbă și este un element foarte mportant când lucrăm cu texte. 

Python foloseste standardul 'utf-8' pentru limba română, și nu numai. 

Următorul exemplu este preluat dintr-o subtitrare (.srt) din limba rusă, dar nu este encodat in utf-8. Așadar dacă vom încerca să îl citim fără să specificăm tipul de encoding, vom primi următoarea eroare:

In [56]:
with open('encoded_text.txt', "r") as fin:
    content = fin.read()
    print(content)

UnicodeDecodeError: ignored

Putem detecta encoding-ul folosit cu librăria `chardet`:

In [57]:
! pip install chardet

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: chardet in /usr/local/lib/python3.8/dist-packages (4.0.0)

In [58]:
import chardet

with open('encoded_text.txt', "rb") as f:
    rawdata = f.read()
    result = chardet.detect(rawdata)
    extracted_encoding = result['encoding']
    print("Encoding-ul acestui fișier este: ", extracted_encoding)

Encoding-ul acestui fișier este:  windows-1251

Cu encoding-ul potrivit, acum fișierul se poate citi:

In [59]:
with open('encoded_text.txt', "r", encoding="windows-1251") as fin:
    content = fin.read()
    print(content)

1
00:00:05,100 --> 00:00:10,860
Это были тяжелые времена. Рим находился под господством коррумпированного Папы и сомнительных законов

2
00:00:10,960 --> 00:00:13,820
игр власти и междоусобной борьбы

3
00:00:15,660 --> 00:00:20,310
Синьоры начинали жестокие сражения с единственной целью – накопить состояние

4
00:00:21,640 --> 00:00:24,950
А тем временем, простые люди ели не каждый день

5
00:00:30,090 --> 00:00:36,040
Любовь была темой для поэтов, но редко упоминалась в свадебных клятвах

6
00:00:36,940 --> 00:00:42,140
Женщин отдавали в жены мужчинам, которых они едва знали, не говоря уже о любви

7
00:00:43,040 --> 00:00:47,980
В этом мире, жестоком и несправедливом, я повстречала двух молодых людей

Putem, dacă vrem, să salvam conținutul în format utf-8, deoarece acest format este default pentru python și nu mai trebie specificat la deschidere:

In [60]:
with open('encoded_text.txt', 'r', encoding=extracted_encoding) as fin:
    content = fin.read()
with open('utf8_text.txt', 'w', encoding='utf-8') as fout:
    fout.write(content)

In [61]:
with open('utf8_text.txt', "r") as fin:
    content = fin.read()
    print(content)

1
00:00:05,100 --> 00:00:10,860
Это были тяжелые времена. Рим находился под господством коррумпированного Папы и сомнительных законов

2
00:00:10,960 --> 00:00:13,820
игр власти и междоусобной борьбы

3
00:00:15,660 --> 00:00:20,310
Синьоры начинали жестокие сражения с единственной целью – накопить состояние

4
00:00:21,640 --> 00:00:24,950
А тем временем, простые люди ели не каждый день

5
00:00:30,090 --> 00:00:36,040
Любовь была темой для поэтов, но редко упоминалась в свадебных клятвах

6
00:00:36,940 --> 00:00:42,140
Женщин отдавали в жены мужчинам, которых они едва знали, не говоря уже о любви

7
00:00:43,040 --> 00:00:47,980
В этом мире, жестоком и несправедливом, я повстречала двух молодых людей

## Non-standard files (PDF, Word, etc.)

Putem citi texte din documente word folosind librăria `doc2txt`.

In [ ]:
!pip install docx2txt

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: docx2txt in /usr/local/lib/python3.8/dist-packages (0.8)

In [ ]:
import docx2txt
my_text = docx2txt.process("soup.docx")
print(my_text)

Beautiful Soup is a Python library for pulling data out of HTML and XML files. It works with your favorite parser to provide idiomatic ways of navigating, searching, and modifying the parse tree. It commonly saves programmers hours or days of work.



These instructions illustrate all major features of Beautiful Soup 4, with examples. I show you what the library is good for, how it works, how to use it, how to make it do what you want, and what to do when it violates your expectations.



This document covers Beautiful Soup version 4.10.0. The examples in this documentation were written for Python 3.8.



You might be looking for the documentation for Beautiful Soup 3. If so, you should know that Beautiful Soup 3 is no longer being developed and that all support for it was dropped on December 31, 2020. If you want to learn about the differences between Beautiful Soup 3 and Beautiful Soup 4, see Porting code to BS4.



This documentation has been translated into other languages by Beautiful Soup users:

Putem citi pdf-uri care sunt salvate ca texte (nu poze), de exemplu, cu librăria `pdfplumber`:

In [ ]:
! pip install pdfplumber

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting pdfplumber
  Downloading pdfplumber-0.8.0-py3-none-any.whl (43 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.7/43.7 KB 4.6 MB/s eta 0:00:00
Collecting Wand>=0.6.10
  Downloading Wand-0.6.11-py2.py3-none-any.whl (143 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 143.6/143.6 KB 17.0 MB/s eta 0:00:00
Collecting Pillow>=9.1
  Downloading Pillow-9.4.0-cp38-cp38-manylinux_2_28_x86_64.whl (3.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.4/3.4 MB 103.8 MB/s eta 0:00:00
Collecting pdfminer.six==20221105
  Downloading pdfminer.six-20221105-py3-none-any.whl (5.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.6/5.6 MB 113.5 MB/s eta 0:00:00
Requirement already satisfied: charset-normalizer>=2.0.0 in /usr/local/lib/python3.8/dist-packages (from pdfminer.six==20221105->pdfplumber) (3.0.1)
Collecting cryptography>=36.0.0
  Downloading cryptography-39.0.1-cp36-abi3-manylinux_2_28_x86_64.whl (4.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 115.2 MB/s eta 0:00:00
Requirement already satisfied: cffi>=1.12 in /usr/local/lib/python3.8/dist-packages (from cryptography>=36.0.0->pdfminer.six==20221105->pdfplumber) (1.15.1)
Requirement already satisfied: pycparser in /usr/local/lib/python3.8/dist-packages (from cffi>=1.12->cryptography>=36.0.0->pdfminer.six==20221105->pdfplumber) (2.21)
Installing collected packages: Wand, Pillow, cryptography, pdfminer.six, pdfplumber
  Attempting uninstall: Pillow
    Found existing installation: Pillow 7.1.2
    Uninstalling Pillow-7.1.2:
      Successfully uninstalled Pillow-7.1.2
Successfully installed Pillow-9.4.0 Wand-0.6.11 cryptography-39.0.1 pdfminer.six-20221105 pdfplumber-0.8.0

In [ ]:
import pdfplumber
with pdfplumber.open('soup.pdf') as pdf:
    for page in pdf.pages:
        print(page.extract_text())

Beautiful Soup is a Python library for pulling data out of HTML and XML files. It works with your favorite
parser to provide idiomatic ways of navigating, searching, and modifying the parse tree. It commonly
saves programmers hours or days of work.
These instructions illustrate all major features of Beautiful Soup 4, with examples. I show you what the
library is good for, how it works, how to use it, how to make it do what you want, and what to do when
it violates your expectations.
This document covers Beautiful Soup version 4.10.0. The examples in this documentation were written
for Python 3.8.
You might be looking for the documentation for Beautiful Soup 3. If so, you should know that Beautiful
Soup 3 is no longer being developed and that all support for it was dropped on December 31, 2020. If
you want to learn about the differences between Beautiful Soup 3 and Beautiful Soup 4, see Porting
code to BS4.
This documentation has been translated into other languages by Beautiful Soup users:

## Web scraping

Scraping-ul se referă la o mulțime de metode prin care putem descărca date nestructurate din mediul web. Pe noi ne interesează datele text, pe care după preluarea din mediul online le putem procesa și stoca într-o formă structurată.

Ca prim exemplu de scraping vom incerca următorul task: pornind de la site-ul de programare competitiva "infoarena.ro" dorim pentru un utilizator sa descarcam informatii despre toate submisiile efectuate de acesta.

Exemplu pagină de submisii: https://www.infoarena.ro/monitor?user=iordache.bogdan

Pentru a realiza un request care să întoarca conținutul paginii putem folosi librăria `requests`:

In [ ]:
! pip install requests

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: requests in /usr/local/lib/python3.8/dist-packages (2.25.1)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.8/dist-packages (from requests) (2022.12.7)
Requirement already satisfied: chardet<5,>=3.0.2 in /usr/local/lib/python3.8/dist-packages (from requests) (4.0.0)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.8/dist-packages (from requests) (2.10)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.8/dist-packages (from requests) (1.24.3)

In [ ]:
import requests

def get_submissions_page(user):
    return requests.get(f"https://www.infoarena.ro/monitor?user={user}")

In [ ]:
html = get_submissions_page("iordache.bogdan").content

Observăm că folosind metoda de mai sus putem descarca întreg conținutul HTML al paginii. Pentru a extrage informații utile trebuie să parsam acest conținut. Pentru aceasta vom folosi biblioteca [BeautifulSoup](https://www.crummy.com/software/BeautifulSoup/bs4/doc/):

In [ ]:
import bs4

def parse_html(html):
    return bs4.BeautifulSoup(html, "html.parser")

Având conținutul parsat, putem determina acum câte submisii are în total acest utilizator:

In [ ]:
import re

soup = parse_html(html)

# cautam un span care are clasa "count", in acest span se afla numarul de submisii
submission_count_text = soup.find("span", class_="count").text
print(submission_count_text)

 (5033 rezultate)

Pentru a extrage doar numărul din această înșiruire de caractere ne putem folosi de regex:

In [ ]:
submission_count = int(re.search(r"\d+", submission_count_text).group())
print(submission_count)

5033

Observăm că aceste submisii sunt împărtite în mai multe pagini (paginarea rezultatelor). 

De asemenea, link-ul următor: https://www.infoarena.ro/monitor?user=iordache.bogdan&display_entries=250&first_entry=100 ne returnează 250 de submisii, incepând cu submisia cu numarul 100. 

Putem modifica metoda `get_submissions_page` astfel:

In [ ]:
def get_submissions_page(user, display_entries=None, first_entry=None):
    req_string = f"https://www.infoarena.ro/monitor?user={user}"
    if display_entries is not None:
        req_string += f"&display_entries={display_entries}"
    if first_entry is not None:
        req_string += f"&first_entry={first_entry}"

    return requests.get(req_string)

Și putem implementa o funcție care returnează informații despre toate submisiile unui utilizator:

In [ ]:
from tqdm import tqdm
import pandas as pd
import pdb

def scrape_submissions(user):
    # determinam numarul total de submisii
    html = get_submissions_page(user).content
    soup = parse_html(html)
    submission_count_text = soup.find("span", class_="count").text
    submission_count = int(re.search(r"\d+", submission_count_text).group())
    print(submission_count)

    # vom salva in acest dictionar datele despre submisiile extrase, structura aceasta
    # ne va ajuta ulterior sa construim un tabel (dataframe) folosind pandas
    d = {
        "id": [],
        "problema": [],
        "url_problema": [],
        "url_sursa": [],
        "data": [],
        "puncte": [],
    }

    # accesam pagini cu submisii in grupuri de 250
    for first_entry in tqdm(range(0, submission_count, 250)):
        html = get_submissions_page(user, display_entries=250, first_entry=first_entry).content
        soup = parse_html(html)

        # selectam toate liniile de tabel (tr)
        lines = soup.select("table.monitor tbody tr")

        for line in lines:
            # selectam celulele de pe aceasta linie
            cells = [cell for cell in line.select("td")]

            # extragem link-urile pentru problema si codul sursa
            try:
                url_problema = cells[2].select_one("a")["href"]
                url_sursa = cells[4].select_one("a")["href"]
            except Exception:  # daca vreun link nu exista ignoram linia
                continue
            
            d["id"].append(cells[0].text)
            d["problema"].append(cells[2].text)
            d["url_problema"].append(url_problema)
            d["url_sursa"].append(url_sursa)
            d["data"].append(cells[5].text)

            try:
                puncte = int(re.search(r"\d+", cells[6].text).group())
            except Exception:
                puncte = 0
            d["puncte"].append(puncte)

    return pd.DataFrame(d)

In [ ]:
df_submissions = scrape_submissions("iordache.bogdan")

5033

100%|██████████| 21/21 [00:22<00:00,  1.05s/it]

In [ ]:
df_submissions.head()

,id,problema,url_problema,url_sursa,data,puncte
0,#2971352,Atac,/problema/atac,/job_detail/2971352?action=view-source,27 ian 23 01:27:44,100
1,#2971346,Atac,/problema/atac,/job_detail/2971346?action=view-source,27 ian 23 01:07:30,20
2,#2971294,Pirati,/problema/pirati,/job_detail/2971294?action=view-source,26 ian 23 23:18:14,100
3,#2970859,Lowest Common Ancestor,/problema/lca,/job_detail/2970859?action=view-source,25 ian 23 23:42:36,100
4,#2970853,Lowest Common Ancestor,/problema/lca,/job_detail/2970853?action=view-source,25 ian 23 23:19:15,100

In [ ]:
df_submissions.to_csv("submissions.csv", index=False)

Exemplu scriere/citire fisier JSON:

In [ ]:
import json

vec = [
    {"title": "example_1", "size": 7},
    {"title": "example_2", "size": 3},
    {"title": "example_3", "size": 8},
]

with open("example.json", "w") as f:
    json.dump(vec, f, indent=4)

In [ ]:
with open("example.json", "r") as f:
    vec = json.load(f)
print(vec)

[{'title': 'example_1', 'size': 7}, {'title': 'example_2', 'size': 3}, {'title': 'example_3', 'size': 8}]

Un alt mod de a face scraping este sa folosim biblioteca pandas pentru a ne extrage tabele html, transformandu-le in DataFrame-uri, pe care le putem manipula foarte usor. Un exemplu util este extragerea sărbătorilor legale romanesti, din anul 2022, de pe https://www.timeanddate.com/.

In [1]:
! pip install lxml

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: lxml in /usr/local/lib/python3.8/dist-packages (4.9.2)

In [3]:
import pandas as pd

tables_df = pd.read_html('https://www.timeanddate.com/holidays/romania/2022?hol=1')
df = tables_df[0]

# Il putem curata prin a sterge liniile nule si modifica coloanele de la tuplul "(Date, Date)" -> "Date"
df = df.dropna(axis='index')
df.columns = ['Date', 'Day', 'Name', 'Type']

# Reindexam tabelul
df = df.reset_index(drop="True")

# Afisam primele 5 randuri
df.head()

     Date       Day                      Name              Type
0   Jan 1  Saturday            New Year's Day  National holiday
1   Jan 2    Sunday  Day after New Year's Day  National holiday
2  Jan 24    Monday           Unification Day  National holiday
3  Feb 19  Saturday   Constantin Brancusi Day        Observance
4  Feb 24  Thursday                 Dragobete        Observance

In [4]:
# Daca vrem se vedem sarbatorile care se nimeresc in ziua de luni putem face o selecție în dataframe
df_luni = df.loc[df["Day"] == "Monday"]
df_luni

      Date     Day                       Name                        Type
2   Jan 24  Monday            Unification Day            National holiday
10  Apr 25  Monday     Orthodox Easter Monday  National holiday, Orthodox
19  Jun 13  Monday  Orthodox Pentecost Monday  National holiday, Orthodox
23  Aug 15  Monday              St Mary's Day            National holiday
25  Oct 31  Monday                  Halloween                  Observance
33  Dec 26  Monday    Second day of Christmas            National holiday

Putem salva rezultatul (la fel ca orice dicționar de python) intr-un json, ca alternativa la DataFrame - acest lucru poate fi util într-o aplicație pentru comunicarea cu front-end-ul.

In [ ]:
import json
json_str = df.to_json(orient='records')
json_result = json.loads(json_str)

with open('holidays.json', 'w', encoding='utf8') as fout:
    json.dump(json_result, fout, indent=4, sort_keys=True, ensure_ascii=False)

Alte biblioteci utile pentru scraping:
 * [scrapy](https://scrapy.org/) (folosit in special pentru web crawling)
 * [selenium](https://selenium-python.readthedocs.io/) (folosit pentru a simula activitatea din browser, utilizat in special in scrierea de teste pentru aplicatii front-end)

## TASK: IMDb scraping

1. Pornind de la lista cu cele mai populare 250 de filme de pe IMDb ([https://www.imdb.com/chart/top/](https://www.imdb.com/chart/top/)), identificati pentru toate aceste filme link-ul catre pagina sa de recenzii.

Exemplu: aici se gaseste pagina cu recenzii pentru "The Shawshank Redemption": [https://www.imdb.com/title/tt0111161/reviews](https://www.imdb.com/title/tt0111161/reviews)

In [62]:
import pandas as pd
import pdb
import bs4
import re
import requests
import json
from IPython.display import display_html

def get_page(link):
    # headers = {'Accept-Language': 'ro-RO,ro;q=0.9,en-US;q=0.8,en;q=0.7'}
    headers = {'Accept-Language': 'en-US;q=0.8,en;q=0.7'}
    return requests.get(link, headers=headers)

def parse_html(html):
    return bs4.BeautifulSoup(html, "html.parser")

def scrape_movies():
    html = get_page(f"https://www.imdb.com/chart/top/").content
    soup = parse_html(html)

    movies_review_link = {
        "title": [],
        "url_review": []
    }
    movies_list = soup.select("table.chart tbody.lister-list tr")

    for movie_line in movies_list:
        try:
            info = movie_line.select("td.titleColumn")[0]
            title = info.select_one("a").text
            review = info.select_one("a")["href"] + "reviews"
        except Exception:  # daca vreun link nu exista ignoram linia
            continue
        
        movies_review_link["title"].append(title)
        movies_review_link["url_review"].append(f"https://www.imdb.com" + review)

    return pd.DataFrame(movies_review_link)

df_movies = scrape_movies()
display_html(df_movies.head())

json_str = df_movies.to_json(orient='records')    
movies = json.loads(json_str)  #salvez datele intr-un json pentru a fi usor de utilizat la exercitiile urmatoare

,title,url_review
0,The Shawshank Redemption,https://www.imdb.com/title/tt0111161/reviews
1,The Godfather,https://www.imdb.com/title/tt0068646/reviews
2,The Dark Knight,https://www.imdb.com/title/tt0468569/reviews
3,The Godfather Part II,https://www.imdb.com/title/tt0071562/reviews
4,12 Angry Men,https://www.imdb.com/title/tt0050083/reviews

2. Pentru fiecare film colectati date despre recenziile sale (titlu, text, rating, data, utlizator, etc.)

In [96]:
import pandas as pd
import pdb
import re
import requests    
import json
from IPython.display import display_html

reviews = []
def select_movie_reviews():   # functie care ia pe rand fiecare film si ii afiseaza intr-un dataframe recenziile sale
    for movie in movies:
      print(movie["title"], end=" ")
      df_reviews = scrape_reviews_info(movie)
      reviews.extend(json.loads(df_reviews.to_json(orient='records'))) # jsonul de recenzii este necesar pentru exercitiuul 3
      display_html(df_reviews.head())    

def scrape_reviews_info(movie):
    html = get_page(movie["url_review"]).content
    soup = parse_html(html)

    reviews = {
        "titlu": [],
        "text": [],
        "rating": [],
        "data": [],
        "utilizator": [],
        "film": []
    }
    review_list = soup.select("div.lister div.lister-list div.review-container div.lister-item-content")

    for review in review_list:
      titlu = re.sub("\n", "", review.select_one("a").text)     # titlul era primit din html cu \n la final
      text = review.select_one("div.content div.text").text
      try:
        rating = int(review.select_one("span.rating-other-user-rating span").text)
      except Exception:  # daca userul nu a oferit un rating
        rating = "-"
      data = review.select_one("div.display-name-date span.review-date").text
      utilizator = review.select_one("div.display-name-date span.display-name-link a").text

      reviews["titlu"].append(titlu)
      reviews["text"].append(text)
      reviews["rating"].append(rating)
      reviews["data"].append(data)
      reviews["utilizator"].append(utilizator)
      reviews["film"].append(movie["title"])

    return pd.DataFrame(reviews)

select_movie_reviews()

The Shawshank Redemption

,titlu,text,rating,data,utilizator,film
0,Some birds aren't meant to be caged.,The Shawshank Redemption is written and direct...,10,24 July 2010,hitchcockthelegend,The Shawshank Redemption
1,An incredible movie. One that lives with you.,It is no wonder that the film has such a high ...,10,17 February 2021,Sleepin_Dragon,The Shawshank Redemption
2,Don't Rent Shawshank.,I'm trying to save you money; this is the last...,10,21 November 2005,EyeDunno,The Shawshank Redemption
3,This is How Movies Should Be Made,This movie is not your ordinary Hollywood flic...,10,18 February 2008,alexkolokotronis,The Shawshank Redemption
4,A classic piece of unforgettable film-making.,"In its Oscar year, Shawshank Redemption (writt...",10,10 February 2006,kaspen12,The Shawshank Redemption

The Godfather

,titlu,text,rating,data,utilizator,film
0,The Pinnacle Of Flawless Films!,'The Godfather' is the pinnacle of flawless fi...,-,20 June 2014,CalRhys,The Godfather
1,"An offer so good, I couldn't refuse",It is now past 1 PM and I just finished watchi...,10,1 April 2019,andrewburgereviews,The Godfather
2,"For Me, This Is The Definitive Film",This isn't just a beautifully crafted gangster...,10,11 February 2018,gogoschka-1,The Godfather
3,One of the best of all time.,"A masterclass in film making, is The Godfather...",10,6 February 2021,Sleepin_Dragon,The Godfather
4,An Iconic Film,Tell me a movie that is more famous than this....,10,21 June 2008,alexkolokotronis,The Godfather

The Dark Knight

,titlu,text,rating,data,utilizator,film
0,The Dark Knight,"Confidently directed, dark, brooding, and pack...",-,12 February 2020,MrHeraclius,The Dark Knight
1,The Batman of our dreams! So much more than a...,I got to see The Dark Knight on Wednesday nigh...,10,20 July 2008,Smells_Like_Cheese,The Dark Knight
2,This town deserves a better class of criminal!,This movie is a work of art. The finest sequel...,10,17 February 2021,dseferaj,The Dark Knight
3,MASTERPIECE,It is just what you want for the best movie. G...,10,7 October 2019,Aegontheconqueror,The Dark Knight
4,Mindblowing,I thought I was getting a clever comic book mo...,10,24 November 2019,RayCharles81,The Dark Knight

The Godfather Part II

,titlu,text,rating,data,utilizator,film
0,Breathtaking in its scope and tragic grandeur...,"Coppola's masterpiece is rivaled only by ""The ...",10,10 March 2001,Nazi_Fighter_David,The Godfather Part II
1,The Greatest Sequel During the Cinema's History,"""The Godfather, Part II"" is excellent just lik...",-,13 October 2001,tfrizzell,The Godfather Part II
2,A masterpiece that can never be beaten...,One of the all time greats. Or probably the al...,10,9 August 2019,umunir-36959,The Godfather Part II
3,The Greatest Film Ever Made,The original Godfather is a brilliant work. It...,10,7 May 1999,DanB-4,The Godfather Part II
4,"Terrific continuation of the ""Godfather"" seri...",This sequel is just as terrific as the first f...,10,23 August 2003,MovieAddict2016,The Godfather Part II

12 Angry Men

,titlu,text,rating,data,utilizator,film
0,"The over-used term ""classic movie"" really com...",This once-in-a-generation masterpiece simply h...,-,12 August 2002,uds3,12 Angry Men
1,No Dissonance,This film deserves to be on anyone's list of t...,-,26 April 2001,tedg,12 Angry Men
2,One of the great theatrical examples of what ...,Theater at its best is practically impossible ...,10,20 March 2017,mark.waltz,12 Angry Men
3,What a Character-Study Is Meant to Be.,Intense courtroom drama which has 12 very diff...,-,8 June 2002,tfrizzell,12 Angry Men
4,Dont judge by the age!,For a while I was not very receptive to watchi...,10,31 January 2020,henriquelrf,12 Angry Men

Schindler's List

,titlu,text,rating,data,utilizator,film
0,A three hour film that feels too short,This film tells the story of Nazi officer Oska...,-,19 October 2009,Gordon-11,Schindler's List
1,Awesome,"The movie started out pretty innocently, and f...",10,17 October 2005,ebiros2,Schindler's List
2,"Bring me the heads of Hitler, Himmler, Eichma...",Schindler's List is undoubtedly the best Holoc...,10,9 September 2013,Fella_shibby,Schindler's List
3,What he hell is wrong with the people that co...,"To all the ppl on the 1st four review pages, u...",9,16 August 2017,padawanmovies,Schindler's List
4,A SINGULAR ACHIEVEMENT,"I have only ever seen this film once, I only e...",-,11 December 2000,vtburns,Schindler's List

The Lord of the Rings: The Return of the King

,titlu,text,rating,data,utilizator,film
0,The best trilogy in the history of cinema,Best movie in the trilogy and sealed in the be...,10,28 September 2020,auuwws,The Lord of the Rings: The Return of the King
1,All Good Things come to an End!,All the threads of Tolkien's magnum opus come ...,10,22 November 2006,OttoVonB,The Lord of the Rings: The Return of the King
2,Great,Wonderful on every level. Love the characters ...,-,15 February 2020,MrHeraclius,The Lord of the Rings: The Return of the King
3,Nothing better,The greatest tragedy of the human race is that...,10,2 November 2020,diffguy,The Lord of the Rings: The Return of the King
4,Pretty much outstanding,"I admit it, I love all three Lord of the Rings...",10,9 March 2011,TheLittleSongbird,The Lord of the Rings: The Return of the King

Pulp Fiction

,titlu,text,rating,data,utilizator,film
0,The masterpiece without a message,"One of the early scenes in ""Pulp Fiction"" feat...",10,17 November 2005,kylopod,Pulp Fiction
1,Shotguns,I like the bit with the cheeseburger. It makes...,10,30 March 2020,bevo-13678,Pulp Fiction
2,A masterpiece of screenwriting,"This is Tarantino's masterpiece, there's no ot...",10,12 November 2020,SebMoz,Pulp Fiction
3,The rebirth of a genre – and film history,"I can only speak for myself, but I had never s...",10,24 July 2014,gogoschka-1,Pulp Fiction
4,The most rewatchable movie of all time,Possibly the most influential movie made in hi...,10,10 April 2020,gautammayya,Pulp Fiction

The Lord of the Rings: The Fellowship of the Ring

,titlu,text,rating,data,utilizator,film
0,"First, And Still The Best Of LOTR","Here is one film that lived up to its hype, an...",10,7 March 2006,ccthemovieman-1,The Lord of the Rings: The Fellowship of the Ring
1,How the hell did they film this thing,An incredible feat\nEnthrals anew every time\n...,10,7 March 2021,mosquitobite,The Lord of the Rings: The Fellowship of the Ring
2,"The Fellowship of the Ring: Not just a Movie,...",The first part of the Lord of the Rings trilog...,10,14 April 2006,bonnie91,The Lord of the Rings: The Fellowship of the Ring
3,Great,It is my firm belief that the standard version...,-,15 February 2020,MrHeraclius,The Lord of the Rings: The Fellowship of the Ring
4,An absolutely incredible film!,Simply incredible. Never before have I seen a ...,10,2 May 2002,NRGWasp,The Lord of the Rings: The Fellowship of the Ring

The Good, the Bad and the Ugly

,titlu,text,rating,data,utilizator,film
0,"For a girl who doesn't enjoy westerns much, t...","Gosh, The Good, the Bad, and the Ugly, I final...",10,29 June 2006,Smells_Like_Cheese,"The Good, the Bad and the Ugly"
1,"Brutal, brilliant, and one of the best Wester...",A sprawling Western epic that follows the adve...,10,16 April 2001,MadReviewer,"The Good, the Bad and the Ugly"
2,Sergio Leone's penultimate Italian-western; a...,...and though those last several words could a...,10,1 January 2004,Quinoa1984,"The Good, the Bad and the Ugly"
3,"The Good, the Better, the Best","The Good, the Bad and the Ugly or the Good, th...",10,19 February 2009,murtaza_mma,"The Good, the Bad and the Ugly"
4,the greatest of the great!,I wasn't sure if I was going to comment on thi...,10,24 August 2005,spider89119,"The Good, the Bad and the Ugly"

Forrest Gump

,titlu,text,rating,data,utilizator,film
0,Let's see the world through the eyes of Forre...,"""I've made about 20 films and 5 of them are pr...",10,10 June 2002,Smells_Like_Cheese,Forrest Gump
1,"In my opinion, no film has touched me more th...","Quite simply, the greatest film ever made.Humo...",10,14 May 2007,thomas-hardcastle-2,Forrest Gump
2,A beautiful fable for now and the future,I believe everyone has a right to their opinio...,10,8 April 2002,Zonieboy,Forrest Gump
3,Dropping My Keys,"I remember John Byner, the stand-up comic and ...",9,19 May 2016,inspectors71,Forrest Gump
4,Purity and innocence retained,I have seen this movie easily a half a dozen t...,10,31 May 2004,kenhe,Forrest Gump

Fight Club

,titlu,text,rating,data,utilizator,film
0,A great movie you can watch again and again,Because you'll probably be confused the first ...,10,11 February 2020,Pukeonthestreet,Fight Club
1,Superb,"Superb, and truly one of the greatest movies o...",10,19 April 2014,grantss,Fight Club
2,Fincher's tour de force is a bruising assault...,"David Fincher's dark, brooding assault on the ...",10,14 July 2016,Leofwine_draca,Fight Club
3,Welcome to movie heaven!,"Let's ignore the advice and talk about ""Fight ...",10,16 December 2013,gogoschka-1,Fight Club
4,"You love it or you hate it, personally I love...","Perhaps a little too long, but Fight Club is j...",9,18 May 2010,TheLittleSongbird,Fight Club

The Lord of the Rings: The Two Towers

,titlu,text,rating,data,utilizator,film
0,An Epic in every sense of the word.,Peter Jackson truly outdid himself when creati...,10,12 August 2010,Loving_Silence,The Lord of the Rings: The Two Towers
1,"""There's some good in this world Mr. Frodo, a...","""The Lord of the Rings"" continues it's epic qu...",10,28 December 2005,classicsoncall,The Lord of the Rings: The Two Towers
2,Great movie,Great movie I really enjoyed watching and bett...,10,28 September 2020,auuwws,The Lord of the Rings: The Two Towers
3,They Accomplished the Near-Impossible.,"""The Lord of the Rings: The Two Towers"" is ano...",-,25 March 2003,tfrizzell,The Lord of the Rings: The Two Towers
4,My personal favourite of the trilogy,I do love all three films of The Lord of the R...,10,8 March 2011,TheLittleSongbird,The Lord of the Rings: The Two Towers

Inception

,titlu,text,rating,data,utilizator,film
0,A one-of-a-kind mind-blowing masterpiece!,"My 3rd time watching this movie! Yet, it still...",10,1 March 2019,adrien_ngoc_1701,Inception
1,Is it possible the makers understand how incr...,You only get to watch this for the first time ...,10,22 December 2020,srcooper-756-646671,Inception
2,Inception was only less shocking to me than t...,"When you wake up from a good dream, you feel t...",10,9 August 2021,mrmocun,Inception
3,Insanely Brilliant ! Nolan has outdone himsel...,What is the most resilient parasite? An Idea! ...,10,10 July 2010,naman-avastol,Inception
4,"In a Decade, ""Inception"" May Be A Religion",Films about dreams and the subconscious are us...,10,13 July 2010,D_Burke,Inception

Star Wars: Episode V - The Empire Strikes Back

,titlu,text,rating,data,utilizator,film
0,All the fun of the original with a much bette...,The Rebellion has struck an important blow to ...,-,27 June 2002,bob the moo,Star Wars: Episode V - The Empire Strikes Back
1,"Excellent timeless classic, the best sequel o...",Star Wars: Episode V - The Empire Strikes Back...,10,25 April 2016,ivo-cobra8,Star Wars: Episode V - The Empire Strikes Back
2,I enjoy this one more than A New Hope,So much amazing action and beautiful cinematog...,10,16 January 2020,UniqueParticle,Star Wars: Episode V - The Empire Strikes Back
3,A worthy second (or 5th??) Star Wars installm...,My five children were all pre-teens when 'The ...,-,7 October 2004,TxMike,Star Wars: Episode V - The Empire Strikes Back
4,It's NOT the darkest of the trilogy - it's th...,`It avoids having the standard shoot-'em-up en...,10,26 October 1999,Spleen,Star Wars: Episode V - The Empire Strikes Back

The Matrix

,titlu,text,rating,data,utilizator,film
0,Just wow,"When this came out, I was living with a roomma...",10,1 November 2019,acedj,The Matrix
1,Benchmark forever.,The Matrix - 1999This was a real change in fil...,10,1 October 2020,suryanmukul,The Matrix
2,The timeless classic.,"This film doesn't age, it will be contemporary...",10,4 January 2021,xNecRosex,The Matrix
3,A watershed moment in film-making – and what ...,** May contain spoilers **There aren't many mo...,10,26 July 2014,gogoschka-1,The Matrix
4,One of the best action sci fi action movies o...,The film is as well crafted as the matrix itse...,-,23 February 2020,MrHeraclius,The Matrix

Goodfellas

,titlu,text,rating,data,utilizator,film
0,In one word: perfection,Needs to be seen to be believed; in one word: ...,10,17 December 2013,gogoschka-1,Goodfellas
1,An Offer You Can't Refuse...,"""As far back as I can remember, I've always wa...",10,31 March 2003,MovieAddict2016,Goodfellas
2,The best mobster film ever made,"After you see this movie, all other mobster mo...",10,18 November 2009,AlsExGal,Goodfellas
3,A great director at the peak of his talents,It is hard to describe the brilliance that is ...,10,9 January 2011,TheLittleSongbird,Goodfellas
4,One word: priceless,If there was one word that I could use to desc...,10,6 November 2004,mhasheider,Goodfellas

One Flew Over the Cuckoo's Nest

,titlu,text,rating,data,utilizator,film
0,The spirit of freedom vs. the spirit of legal...,"Set in the early 60s, the story involves R.P. ...",9,21 October 2012,Wuchakk,One Flew Over the Cuckoo's Nest
1,"Both uplifting and disheartening, sometimes b...",I went into this film with the knowledge that ...,10,14 January 2005,pyrocitor,One Flew Over the Cuckoo's Nest
2,"Touching and moving, a great cinematic experi...","Jack Nicholson is a great actor. No, not a gre...",10,3 July 2004,TBJCSKCNRRQTreviews,One Flew Over the Cuckoo's Nest
3,"""What an excellent movie"" is all that went th...","What a movie, what an excellent movie!!! That ...",10,14 September 2004,philip_vanderveken,One Flew Over the Cuckoo's Nest
4,A masterpiece,The seventies produced some of the most intere...,10,20 July 2018,perica-43151,One Flew Over the Cuckoo's Nest

Se7en

,titlu,text,rating,data,utilizator,film
0,Very grim and disturbing but you can't stop w...,Detective Lt. William Somerset (Morgan Freeman...,9,14 February 2008,preppy-3,Se7en
1,Dark and disturbing thriller that will stay w...,Rarely there has been a movie with such a good...,10,30 April 2004,Boba_Fett1138,Se7en
2,A brilliant postmodern film noir that is grim...,"From David Fincher, Se7en is a compelling and ...",10,18 May 2010,TheLittleSongbird,Se7en
3,Still manages to astound after 20 years of re...,After his calamitous experience working on his...,10,1 March 2014,tomgillespie2002,Se7en
4,He's experienced about as much pain and suffe...,Seven is directed by David Fincher and written...,10,4 March 2008,hitchcockthelegend,Se7en

Seven Samurai

,titlu,text,rating,data,utilizator,film
0,Solid Gold,I discovered 16 of Kurosawa's best known films...,10,8 January 2003,OttoVonB,Seven Samurai
1,Story-Telling At Its Finest,"Story-telling at its finest, ""Seven Samurai"" i...",-,28 November 2001,Snow Leopard,Seven Samurai
2,Kurosawa's triumphant epic- totally & success...,Akira Kurosawa was and is considered the maste...,10,7 December 2003,Quinoa1984,Seven Samurai
3,Memorable characters and one of the best acti...,Having seen Kurosawa's Seven Samurai at least ...,-,17 August 2004,gkbazalo,Seven Samurai
4,"Arguably, the best samurai film ever made",Though its biblical connotation is not the hap...,10,25 May 2010,Davor_Blazevic_1959,Seven Samurai

It's a Wonderful Life

,titlu,text,rating,data,utilizator,film
0,"""To My Big Brother George, The Richest Man In...",I've always thought that the reason It's A Won...,10,25 December 2005,bkoganbing,It's a Wonderful Life
1,A Great Influence...,No movie ever made has influenced me more than...,10,4 March 1999,Coxer99,It's a Wonderful Life
2,One of those quintessential Christmas movies....,It's a Wonderful Life is something truly speci...,10,28 March 2010,TheLittleSongbird,It's a Wonderful Life
3,A Wonderful Film and Timeless Classic,This film has become a Christmas tradition in ...,10,6 December 2000,FlickJunkie-2,It's a Wonderful Life
4,A wonderful film that should be watched again...,"This is one of the best films of all time, wit...",10,13 September 2002,PyrolyticCarbon,It's a Wonderful Life

The Silence of the Lambs

,titlu,text,rating,data,utilizator,film
0,"Dr.Lecter, I'd like to see you again...",The Silence of the Lambs runs two hours.Anthon...,10,22 October 2005,MaxBorg89,The Silence of the Lambs
1,In a Class by Itself,Brilliant Best Picture of 1991 that never gets...,-,21 July 2000,tfrizzell,The Silence of the Lambs
2,A Story And A Character That You Can't Forget,I'll never forget my first viewing of this mov...,10,17 January 2007,ccthemovieman-1,The Silence of the Lambs
3,Rare to experience a dark n twisted thriller ...,I first saw this in the early 90s on a vhs and...,10,11 August 2021,Fella_shibby,The Silence of the Lambs
4,"""The Godfather"" of all thrillers",I've seen way too many thrillers. You name it:...,10,28 August 2004,Smells_Like_Cheese,The Silence of the Lambs

Saving Private Ryan

,titlu,text,rating,data,utilizator,film
0,Hard to Rate ... been there,The first 23 minutes of this film is rated at ...,10,31 December 2019,j-a-julian,Saving Private Ryan
1,The only movie my grandfather couldn't finish,My grandfather fought in WW2 somehow surviving...,10,11 October 2018,keving4241,Saving Private Ryan
2,"""Sergeant, we have crossed some strange bound...",I read four or five pages of reviews for this ...,10,27 August 2011,classicsoncall,Saving Private Ryan
3,A war film you simply can't miss.,Possibly the most realistic depiction of grues...,-,23 February 2020,MrHeraclius,Saving Private Ryan
4,"War is hell, and ""Saving Private Ryan"" peeks ...",I'd heard a couple of startling things about t...,9,16 August 1999,ToldYaSo,Saving Private Ryan

City of God

,titlu,text,rating,data,utilizator,film
0,A Brazilian masterwork,Such an amazing film that deserves the accolad...,10,10 June 2017,TheLittleSongbird,City of God
1,Gangs of Rio,"If you're unlucky to be born into a socially, ...",-,17 May 2003,Decko_koji_obecava,City of God
2,"Magnificent, gut-wrenching and utterly compel...",Do not be fooled by the coy charm of the promo...,10,26 October 2004,tjcclarke,City of God
3,Stunning - in every sense of the word,Cidade de Deus seems to have a lot of praise o...,10,18 December 2004,trelloskilos-1,City of God
4,The Godfather of Rio,Li'l Zé and his gang is having fun chasing a r...,8,16 June 2015,SnoopyStyle,City of God

Interstellar

,titlu,text,rating,data,utilizator,film
0,Out of this world,A lot has been said and written about Interste...,10,31 May 2015,kosmasp,Interstellar
1,A visual and auditory marvel,Interstellar is a movie like no other. Unlike ...,10,13 April 2016,Jared_Andrews,Interstellar
2,Masterpiece,Amongst the best movies of all time. The story...,10,8 May 2022,e-jackson1985,Interstellar
3,I waited 5 years to watch it again,After watching this insane movie in the theatr...,10,26 June 2019,Ksa-2010,Interstellar
4,Masterpiece,A science-fiction masterpiece. Nolan executes ...,10,25 June 2022,aheaven2005,Interstellar

Life Is Beautiful

,titlu,text,rating,data,utilizator,film
0,Love is Beautiful...,"Emotional extremes abound, this story takes yo...",9,20 December 2021,Xstal,Life Is Beautiful
1,"Funny, entertaining, and amazingly intense an...",I find it sad that so many people are so narro...,10,27 March 2000,Anonymous_Maxine,Life Is Beautiful
2,Outstanding,This may be one of the best films ever made. I...,-,3 January 2000,Monika-5,Life Is Beautiful
3,One of the best movies ever.,This is one of those movies that have a lastin...,9,29 August 2000,amira_berzi,Life Is Beautiful
4,"A satire set in a concentration camp, tough a...",Mixing humor and the Holocaust isn't anything ...,10,4 September 2001,Nazi_Fighter_David,Life Is Beautiful

The Green Mile

,titlu,text,rating,data,utilizator,film
0,One of the most penetrating films of the past...,"THE GREEN MILE (1999) ****Starring: Tom Hanks,...",10,25 January 2000,Movie-12,The Green Mile
1,""" I knows you think I's a powerful man, but t...",The world is teeming with wretched prisons whe...,9,29 October 2009,thinker1691,The Green Mile
2,'m sorry for what I am,You tell God the Father it was a kindness you ...,10,5 May 2020,DemonKiki,The Green Mile
3,The Least Of us,I'm glad that a number of reviewers have infor...,10,7 December 2009,bkoganbing,The Green Mile
4,A one of a kind classic,This movie is a real gem. It is hard to find ...,10,17 June 2001,jlacerra,The Green Mile

Star Wars: Episode IV - A New Hope

,titlu,text,rating,data,utilizator,film
0,One of the most successful movies of all time...,What made this the hugely successful triumph i...,10,26 October 2003,FiendishDramaturgy,Star Wars: Episode IV - A New Hope
1,"A classics, phenomenal and arguably the best ...",Star Wars: Episode IV - A New Hope (1977) is a...,10,23 April 2016,ivo-cobra8,Star Wars: Episode IV - A New Hope
2,Legendary piece of cinema,Only seen the original Star Wars films a few t...,10,16 January 2020,UniqueParticle,Star Wars: Episode IV - A New Hope
3,"The Best of Sci-Fi Times,the Worst of sf Times","Though now known as ""Episode IV-A New Hope,"" f...",9,25 December 2005,Bogmeister,Star Wars: Episode IV - A New Hope
4,"The Force will be with you, always.","""A long time ago, in a galaxy far, far away......",10,27 July 2018,SantiagoDM1,Star Wars: Episode IV - A New Hope

Terminator 2: Judgment Day

,titlu,text,rating,data,utilizator,film
0,Note to Hollywood: This is how you make an ac...,"And yes, I'd consider this more of an action f...",10,30 August 2009,TOMASBBloodhound,Terminator 2: Judgment Day
1,Movie that everyone should see!,Greetings from Lithuania.WOW! The best word th...,10,13 March 2008,851222,Terminator 2: Judgment Day
2,This is the sequel that dreams are made of.,Normally when people tell you about a sequel t...,10,4 August 2002,Smells_Like_Cheese,Terminator 2: Judgment Day
3,"This Terminator Sequel, may prove to be the b...","After failing to kill Sarah Conner, the Machin...",10,5 February 2005,mjw2305,Terminator 2: Judgment Day
4,He Said He'd Be Back...and He Certainly is!,"Who said sequels aren't any good? ""Terminator ...",10,5 November 2003,MovieAddict2016,Terminator 2: Judgment Day

Back to the Future

,titlu,text,rating,data,utilizator,film
0,So good in so many ways,I love Back to the Future. While having a typi...,10,15 April 2010,TheLittleSongbird,Back to the Future
1,A Time -Travelling Classic,Zemeckis's 'Back To The Future' trilogy has be...,-,29 July 2008,Chrysanthepop,Back to the Future
2,How could anything be more fun than this?,Back To The Future is such an inventive and ex...,10,1 June 2000,Anonymous_Maxine,Back to the Future
3,Great movie,One of the last movies I went with sister to s...,10,28 November 2004,mm-39,Back to the Future
4,A classic masterpiece the original the only b...,What can I say about this movie that was alrea...,10,17 April 2017,ivo-cobra8,Back to the Future

Spirited Away

,titlu,text,rating,data,utilizator,film
0,"Strange, touching and beautiful","Personally, I've never seen anything as origin...",10,26 December 2013,gogoschka-1,Spirited Away
1,I don't really know what to say.,I enjoyed this movie but more towards the end....,7,29 December 2020,Morejambo54,Spirited Away
2,a minority dissenting view,In Hayao Miyazaki's Oscar-winning animated fea...,-,3 May 2003,Buddy-51,Spirited Away
3,Best animated film I have seen!,This is a wonderfully imaginative and fantasti...,10,2 April 2004,supertom-3,Spirited Away
4,An Amazing Achievement in Animation.,'Spirited Away' is the first Miyazaki I have s...,-,20 July 2004,Le-Samourai,Spirited Away

The Pianist

,titlu,text,rating,data,utilizator,film
0,"Excellent, depressing, but excellent","Man, I can not get this film out of my head. I...",10,1 November 2004,Smells_Like_Cheese,The Pianist
1,"A haunting film, one that you won't forget",I can remember when this film came out I was a...,-,27 March 2003,baumer,The Pianist
2,A Masterpiece. Awesome acting by Brody.,This is a truly heart-wrenching story of one m...,10,9 September 2013,Fella_shibby,The Pianist
3,An astonishing film,The Pianist is the true story of Wladyslaw Szp...,8,28 April 2003,FilmOtaku,The Pianist
4,To hell and back.,The Pianist is an incredible film in many aspe...,10,21 January 2003,jotix100,The Pianist

Psycho

,titlu,text,rating,data,utilizator,film
0,It's the Little Things,So much has been written about this film that ...,10,5 September 2001,telegonus,Psycho
1,Always holds me from beginning to end...,...from the first time I saw it at age 14 unti...,10,25 March 2017,AlsExGal,Psycho
2,"The More I See This, The Better It Gets",When I watched this for the first time in over...,10,25 October 2006,ccthemovieman-1,Psycho
3,Movie At The Crossroads Of Time,What can you say about a film that's been talk...,10,10 August 2004,slokes,Psycho
4,Anthony's Norman,"Getting into Hitchcock's Psycho, 57 years afte...",10,19 May 2017,arichmondfwc,Psycho

Parasite

,titlu,text,rating,data,utilizator,film
0,One of the best films of this decade,I am remarkably stingy with my 10/10 ratings. ...,10,5 July 2019,Jeremy_Urquhart,Parasite
1,"You name a genre, this movie covers it",I can't remember the last time I saw a movie t...,8,6 October 2019,jtindahouse,Parasite
2,Meritocracy: it's metaphorical,"In a meritocracy, success and fortune are rese...",10,25 August 2019,nehpetstephen,Parasite
3,Thoroughly entertaining,PARASITE is an excellent effort from Korean di...,10,1 November 2020,Leofwine_draca,Parasite
4,For those who didn't like the movie because o...,It's not really a review but my attempt to exp...,10,18 October 2019,mysticfall,Parasite

Léon: The Professional

,titlu,text,rating,data,utilizator,film
0,Masterful,I have long thought that owning films on DVD o...,10,29 March 2004,tjcclarke,Léon: The Professional
1,Being a good hitman takes more than merely a ...,I first saw this in the late 90s. Then again i...,9,24 September 2021,Fella_shibby,Léon: The Professional
2,Besson's masterpiece - action cinema with rea...,Despite having a mainly American cast and bein...,10,16 August 2016,Leofwine_draca,Léon: The Professional
3,A Perfect Chemistry,"In New York, León (Jean Reno) is an Italian pr...",10,7 December 2004,claudio_carvalho,Léon: The Professional
4,A shameful praise of a fantastic film.,Leon (Jean Reno) is a tortured soul. He lives ...,10,21 December 1999,Insincere Dave,Léon: The Professional

The Lion King

,titlu,text,rating,data,utilizator,film
0,One of my favorite movies of all time!,"Seriously, I know that sounds stupid as this i...",10,31 October 2003,Smells_Like_Cheese,The Lion King
1,The Best Animated Film I Have Ever Seen,The Lion King is a great film. Along with a g...,10,1 January 2000,Quinoa1984,The Lion King
2,A Film For All Ages,This is a film that can entertain anyone young...,10,20 January 2000,claudonio,The Lion King
3,"simply a wonderful, heartfelt tale for all ages",Delightful animated feature from Walt Disney P...,-,14 March 2002,Special-K88,The Lion King
4,So Good in So Many Ways.,Outstanding animated feature from Disney that ...,-,3 July 2002,tfrizzell,The Lion King

Gladiator

,titlu,text,rating,data,utilizator,film
0,They said you were a giant. They said you can...,Ridley Scott's Gladiator is not a perfect film...,10,6 August 2014,hitchcockthelegend,Gladiator
1,"As a matter of fact, Maximus, I AM entertained.",Gladiator is the best bread and circus. A movi...,8,11 October 2020,mahmus,Gladiator
2,One of the best films ever,There are so many iconic lines and quips in th...,10,6 April 2021,ajkbiotech,Gladiator
3,Are you entertained? Yes sir yes I am,"How good is Russell Crowe though, easily one o...",8,6 December 2020,nathanmanson,Gladiator
4,Great,Gladiator is a historical epic from director R...,-,24 February 2020,MrHeraclius,Gladiator

American History X

,titlu,text,rating,data,utilizator,film
0,One of the most powerful movies I have ever s...,I was expecting a kind of a moralistic movie w...,10,19 July 2005,Boba_Fett1138,American History X
1,Edward Norton owned this movie,I give this movie a 10 because1) Edward Norton...,10,6 August 2019,behbehseta,American History X
2,"""Has anything you've done made your life bett...",I've seen a lot of movies and have seen a lot ...,9,7 January 2012,classicsoncall,American History X
3,The Most Dangerous Person To Us Is Ourselves,American History X is a movie of its own. It h...,10,1 February 2009,alexkolokotronis,American History X
4,Changed My Life.,American History X really opened my eyes to th...,10,7 August 2005,seventhsamurai1954,American History X

The Departed

,titlu,text,rating,data,utilizator,film
0,Moles And Rats,When The Departed finally gained for Martin Sc...,10,7 December 2009,bkoganbing,The Departed
1,One of Scorsese's very best movies,Martin Scorsese returns to familiar territory ...,10,19 June 2016,Leofwine_draca,The Departed
2,Scorsese's best since Goodfellas!,"He has made good musicals (New York, New York)...",10,31 October 2006,MaxBorg89,The Departed
3,"Lies, Betrayal, Sacrifice. What will you beli...","First off, this is an American stylized remake...",-,28 January 2009,Billy_Costigan,The Departed
4,10 out of 10 and WOW does this film deserve i...,Blood Diamond (2006) was the film which turned...,10,23 November 2020,James_Denton,The Departed

The Usual Suspects

,titlu,text,rating,data,utilizator,film
0,the American thriller of the nineties,"One day in a bookshop, I flipped through a boo...",10,12 December 2005,dbdumonteil,The Usual Suspects
1,A stone cold CLASSIC!,'The Usual Suspects' has received a lot of com...,-,13 December 2001,Infofreak,The Usual Suspects
2,I'm Glad I Finally Got a Chance to See It,I don't know what the problem is. I had heard ...,9,8 December 2009,Hitchcoc,The Usual Suspects
3,""" The Greatest Trick The Devil Ever Pulled""",Out of the mind of Christorpher McQurrie comes...,9,12 July 2007,thinker1691,The Usual Suspects
4,The most enjoyment you'll have seeing a movie...,"Ah, the Usual Suspects. My personal favorite m...",10,8 September 2004,TIDQ,The Usual Suspects

The Prestige

,titlu,text,rating,data,utilizator,film
0,"Just As Intriguing The Second Time, Too!",I've seen this film twice now - about a year a...,10,29 September 2008,ccthemovieman-1,The Prestige
1,Fantastic.,"I won't say it's an underrated movie, but it h...",10,30 May 2018,NpMoviez,The Prestige
2,Are you watching closely?,"The Prestige, adapted from an award winning no...",10,7 September 2009,murtaza_mma,The Prestige
3,A Nutshell Review: The Prestige,"I've said it before, but I'll say it again. Ch...",10,20 October 2006,DICK STEEL,The Prestige
4,Give This Film Time to Sink In...,"Leaving the theater, I thought the film was ju...",10,28 October 2006,gavin6942,The Prestige

Whiplash

,titlu,text,rating,data,utilizator,film
0,Whiplash is a modern day masterpiece.,"I don't say that often, in fact...never. There...",10,2 March 2018,TheMovieDiorama,Whiplash
1,This is review #572....so is there really any...,"""Whiplash"" is a terrific film...no doubt about...",9,18 July 2015,planktonrules,Whiplash
2,An important hardened lesson in resilience an...,Taking the festival circuit by storm since its...,10,23 October 2014,Sergeant_Tibbs,Whiplash
3,Just My Tempo,Greetings again from the darkness. The pursuit...,8,26 October 2014,ferguson-6,Whiplash
4,Intense,This movie was far better than the trailer mad...,9,22 October 2014,bbickley13-921-58664,Whiplash

Casablanca

,titlu,text,rating,data,utilizator,film
0,The Fundamental Things Apply...,"""Casablanca"" remains Hollywood's finest moment...",10,16 January 2005,slokes,Casablanca
1,HOW TO WATCH THIS MOVIE,There are literally hundreds of comments about...,10,23 August 2003,Jaymay,Casablanca
2,Here's looking at Ingrid Bergman,Wow! Ingrid Bergman was at her best in this on...,10,30 November 2004,smatysia,Casablanca
3,".....it's still the same old story, a fight f...",It's one of the great Hollywood legends how Ge...,10,8 March 2006,bkoganbing,Casablanca
4,Greatest Film Ever for Me,Why do I consider this to be the greatest film...,10,1 April 2019,gpeevers,Casablanca

Harakiri

,titlu,text,rating,data,utilizator,film
0,Samurai Genre is Used to Exposively Indict Ja...,I saw Harakiri (Seppuku) in a new 35 mm print ...,10,16 September 2005,noralee,Harakiri
1,Disharmony of Sword and Pen,"I've said it once about another movie, inciden...",10,21 March 2007,Galina_movie_fan,Harakiri
2,Does to the Samurai genre what Wild Bunch did...,Having seen this film the mind becomes clouded...,10,7 October 2005,OttoVonB,Harakiri
3,Rituals and appearances aren't just about the...,"""Harakiri"" (""Seppuku"") (Japanese, 1962): It is...",-,17 July 2005,futures-1,Harakiri
4,200 Proof,This film is the purest distillation of the sp...,10,8 November 2001,Duree,Harakiri

Grave of the Fireflies

,titlu,text,rating,data,utilizator,film
0,A powerful film that shows the true cost of war,"""Grave of the Fireflies"" is one of the most am...",10,28 August 2004,dee.reid,Grave of the Fireflies
1,"A masterpiece, whose beauty is often overlooked","When I watched this movie, I steeled myself fo...",10,4 September 2004,Lupercali,Grave of the Fireflies
2,Powerful and Heartbreaking,"""September 21, 1945...That was the night I die...",-,11 November 2002,howard.schumann,Grave of the Fireflies
3,A Beautiful Unforgettable Masterpiece that sh...,I decided to watch Grave of the Fireflies yest...,10,16 June 2010,The_Fifth_Echo,Grave of the Fireflies
4,"Beautiful, haunting and emotionally devastating",What an amazing film! Very rarely have I been ...,10,3 April 2010,TheLittleSongbird,Grave of the Fireflies

The Intouchables

,titlu,text,rating,data,utilizator,film
0,One of the Most Unique and Beautiful Friendsh...,"Do not look at this through the prism of ""Fore...",10,27 November 2011,OttoVonB,The Intouchables
1,Touché ...,"In less than two months, ""Untouchable"" became ...",10,17 January 2012,ElMaruecan82,The Intouchables
2,"A magnificent, sensitive movie",It's not because I'm French that I appreciated...,10,11 December 2011,jvdesuit1,The Intouchables
3,Just excellent,I am now trying to find words to describe this...,10,10 January 2012,n-buenning,The Intouchables
4,A Film of True Humanity : Comedy in the Face ...,It has been 9 weeks now since Intoucblaes has ...,9,28 December 2011,bakor24-1,The Intouchables

Modern Times

,titlu,text,rating,data,utilizator,film
0,As relevant today as it was then - and still ...,"Part satire, part slapstick comedy, part melod...",9,17 December 2013,gogoschka-1,Modern Times
1,Individual Parts Greater Than the Whole,One of this movie's most famous images--Chapli...,7,7 December 2005,evanston_dad,Modern Times
2,Solid comedy with great story and drama,"Greetings from Lithuania.""Modern Times"" (1936)...",9,28 June 2015,851222,Modern Times
3,In the Pursuit of Happiness...,Never a dull moment with the vagrant antics of...,8,13 September 2020,Xstal,Modern Times
4,Excellent,This very well written story never lets down f...,8,18 May 2016,Horror-yo,Modern Times

Once Upon a Time in the West

,titlu,text,rating,data,utilizator,film
0,thumping good Western with an almost operatic...,"One of the great classics : a riveting, wildly...",9,5 October 2019,myriamlenys,Once Upon a Time in the West
1,More Western than 'The Western' itself,"In full silence, three mysterious men in long ...",10,24 April 2019,TheDragonTrader,Once Upon a Time in the West
2,It doesn't get any better than this: this is ...,This one only gets better with each viewing. L...,10,24 December 2013,gogoschka-1,Once Upon a Time in the West
3,"Without a doubt, one of the best Westerns of ...",I won't claim to have the ability to say anyth...,10,30 September 2017,Jeremy_Urquhart,Once Upon a Time in the West
4,"""When you've killed Four, it's easy to make i...","In the annals of western film lore, there are ...",9,27 June 2007,thinker1691,Once Upon a Time in the West

Rear Window

,titlu,text,rating,data,utilizator,film
0,A Deep & Entertaining Classic,"One of Hitchcock's greatest masterpieces, ""Rea...",-,20 June 2001,Snow Leopard,Rear Window
1,Well of course when you've got nothing better...,"Finally, I watched ""Rear Window"" by famous Alf...",10,3 December 2005,Smells_Like_Cheese,Rear Window
2,Another Hitchcock masterpiece,Alfred Hitchcock is considered by most to be t...,10,10 April 2001,FlickJunkie-2,Rear Window
3,"Sophisticated Hitchcock, with a wonderful per...",Rear Window is a one of the more sophisticated...,10,22 June 2009,TheLittleSongbird,Rear Window
4,"In the mid-fifties, Hitchcock brought remarka...",Many reviewers and critics have commented on A...,10,15 January 2004,Quinoa1984,Rear Window

Cinema Paradiso

,titlu,text,rating,data,utilizator,film
0,My favourite film of all time,It is by now well known that there are two ver...,-,20 February 2005,DrLenera,Cinema Paradiso
1,The Loves Of 'Toto' Beautifully Told,After seeing this special edition DVD which sh...,8,21 March 2006,ccthemovieman-1,Cinema Paradiso
2,Classic,This 1988 Italian film (released in the US in ...,10,1 July 2002,preppy-3,Cinema Paradiso
3,Every Filmmaker's Favorite Film,Giuseppe Tornatore's Nuovo cinema Paradiso (Ci...,10,12 February 2005,caspian1978,Cinema Paradiso
4,A beautiful film about the love of movies and...,I continue to be moved and deeply touched by t...,9,16 June 1999,doeadear,Cinema Paradiso

Alien

,titlu,text,rating,data,utilizator,film
0,Holds up as a classic.,"Alien remains one of the most original, terrif...",10,16 January 2020,Sleepin_Dragon,Alien
1,A Timeless Science Fiction Masterpiece,'Alien' is one of those special films that hav...,10,11 February 2018,gogoschka-1,Alien
2,One of the best classic sci-fi horror films o...,A masterpiece one of the best classic sci-fi h...,10,20 February 2018,ivo-cobra8,Alien
3,The facehugger scared me as a kid and i still...,Everything has already been said about this gr...,9,24 March 2021,Fella_shibby,Alien
4,The Purina Dog Chow company will expand and m...,Ridely Scott is such a minimalist in Alien tha...,10,6 April 2000,zetes,Alien

City Lights

,titlu,text,rating,data,utilizator,film
0,"Lady and the Tramp, before animation and at t...",If there is one Charlie Chaplin film to recomm...,10,12 September 2004,Quinoa1984,City Lights
1,Masterpiece,City Lights (1931) **** (out of 4)Charlie Chap...,-,26 February 2008,Michael_Elliott,City Lights
2,Chaplin's Masterpiece...and Oh Those Last Fiv...,Let me join the consensus and call Charlie Cha...,10,16 December 2005,EUyeshima,City Lights
3,Chaplin's Classic of Humor and Humanity,"Charlie Chaplin's ""City Lights"" contains a ble...",-,29 May 2001,Snow Leopard,City Lights
4,"You can't go wrong with Charlie Chaplin, but ...",Chaplin takes himself a little more seriously ...,10,22 December 2000,Anonymous_Maxine,City Lights

Apocalypse Now

,titlu,text,rating,data,utilizator,film
0,Redux: still brilliant - but now with new str...,In an updating of `Hearts of Darkness' a soldi...,-,27 March 2004,bob the moo,Apocalypse Now
1,This Is the End...,Apocalypse now is not only the best war film e...,10,23 March 2018,notoriousCASK,Apocalypse Now
2,My All Time Favourite Movie,I first saw APOCALYPSE NOW in 1985 when it was...,10,23 June 2004,Theo Robertson,Apocalypse Now
3,The most anti-war pro-war film ever made.,Coming out on the cusp of several other big aw...,10,22 January 2021,mark.waltz,Apocalypse Now
4,Crumbles under its own weight,I have nothing but respect for Francis Ford Co...,7,5 May 2015,Vartiainen,Apocalypse Now

Memento

,titlu,text,rating,data,utilizator,film
0,Genius thriller,This unique and well-crafted tale is a top-not...,9,28 August 2016,Leofwine_draca,Memento
1,I guessed and guessed... I never got close.,I know that it's a little late by now for this...,10,13 August 2020,nateahoey,Memento
2,Some memories are best forgotten. You have to...,Losing your memory would have to go close to o...,10,6 February 2003,Old Joe,Memento
3,Addictive and fun to figure out,"Christopher Nolan's ""Memento"" is truly a rare ...",-,1 September 2003,quixoboy,Memento
4,Innovative narrative structure makes for a po...,"FACT ONE: ""Just because there are things I don...",10,9 July 2002,wkbeason,Memento

Django Unchained

,titlu,text,rating,data,utilizator,film
0,Tarantino at his best,"(Jamie Fox, Christoph Waltz, Leonardo DiCaprio...",10,19 December 2020,shawnmikedryer,Django Unchained
1,It's not perfect but it's very good... and I'...,I just saw this film and I confess that I am c...,8,3 December 2020,filipemanuelneto,Django Unchained
2,Best Tarantino movie and you can't change my ...,Jango (D is silence) is just one of those movi...,10,25 April 2021,postolachivalentin,Django Unchained
3,The Perfect Movie,"For anyone who isn't much into cinema, I would...",10,16 June 2020,alexcole10,Django Unchained
4,Unmistakable Tarantino,Dr. King Schultz (Christoph Waltz) is a bounty...,9,24 August 2013,SnoopyStyle,Django Unchained

Indiana Jones and the Raiders of the Lost Ark

,titlu,text,rating,data,utilizator,film
0,Perpetually Entertaining...,"An army of fascists seek to plunder, an artefa...",9,6 June 2022,Xstal,Indiana Jones and the Raiders of the Lost Ark
1,When Harrison Ford was crapping gold,This is the first movie in the Indiana Jones s...,9,15 November 2019,acedj,Indiana Jones and the Raiders of the Lost Ark
2,There will never be another film like Raiders,It is a hot sunny day in South America. We see...,10,9 July 1999,baumer,Indiana Jones and the Raiders of the Lost Ark
3,Excellent movie and brilliantly crafted enter...,"I remember seeing this movie when I was young,...",10,24 December 2004,PyrolyticCarbon,Indiana Jones and the Raiders of the Lost Ark
4,Will stand the test of time forever.,I've seen Raiders of the Lost Ark numerous tim...,9,26 September 2006,CuriosityKilledShawn,Indiana Jones and the Raiders of the Lost Ark

WALL·E

,titlu,text,rating,data,utilizator,film
0,"Who says popular films can't be art? ""WALL·E""...",Who says popular films are not and cannot be a...,-,27 June 2008,ametaphysicalshark,WALL·E
1,Honestly? This is the best Disney/Pixar movie...,I'm starting to wonder if there is bad Disney/...,10,27 June 2008,Smells_Like_Cheese,WALL·E
2,Best movie of the century,"To this day, this is still my favorite pixar f...",-,15 February 2020,MrHeraclius,WALL·E
3,A Most Endearing Love Story In Space...And Back,Over the years I've become quite a sucker for ...,-,2 November 2008,Chrysanthepop,WALL·E
4,Simply amazing!,"I heard mixed reviews on WALL-E, there were th...",9,1 December 2009,TheLittleSongbird,WALL·E

The Lives of Others

,titlu,text,rating,data,utilizator,film
0,Outstandingly great movie,I wonder why there has been so little written ...,10,8 March 2007,wisewebwoman,The Lives of Others
1,"Masterpiece, a unique lesson on humanity",This is the first full feature film by Florian...,10,19 May 2015,Horst_In_Translation,The Lives of Others
2,The globe's best . . .,"""Who knows the secrets of the human heart?"" Co...",-,7 March 2007,JohnDeSando,The Lives of Others
3,We all have something to hide.,Das Leben der Anderen (2006) (The Lives of Oth...,10,26 March 2007,Red-125,The Lives of Others
4,The ghost of authoritarian regimes,I've been taking German lessons for about 2 mo...,10,11 March 2007,Hprog,The Lives of Others

Sunset Blvd.

,titlu,text,rating,data,utilizator,film
0,A true Hollywood horror story,Hack screenwriter Joe Gillis (William Holden) ...,10,15 March 2008,preppy-3,Sunset Blvd.
1,"""Madam is the greatest star of all.""",Sunset Blvd. could be looked at as a thesis on...,-,4 August 1999,bat-5,Sunset Blvd.
2,Best Performance in Film History: Gloria Swanson,The plot has been discussed at length in other...,-,11 January 2006,drednm,Sunset Blvd.
3,Another Billy Wilder masterpiece,I have yet to see a Billy Wilder film that I h...,9,11 April 2004,FilmOtaku,Sunset Blvd.
4,The Hollywood Myth FOREVER Shattered !!!,"Until 1950, American films were strictly enter...",10,22 April 1999,Don-102,Sunset Blvd.

Paths of Glory

,titlu,text,rating,data,utilizator,film
0,They Couldn't Take An Ant Hill,Almost one hundred years later the concept of ...,10,2 July 2006,bkoganbing,Paths of Glory
1,"""Let the men have a few minutes more""",Although Kubrick's films are marked by their m...,9,15 October 2006,Steffi_P,Paths of Glory
2,Kubrick at the height of his powers- a wonder...,I saw this movie for the first time on televis...,10,9 December 2009,TheLittleSongbird,Paths of Glory
3,Kubrick--a fully-formed genius in 1957.,At only 29 years of age and in only his second...,10,7 July 1999,Hermit C-2,Paths of Glory
4,Stands the Test of Time,An arrogant French general (a superb George Ma...,9,28 July 2007,WriterDave,Paths of Glory

The Shining

,titlu,text,rating,data,utilizator,film
0,"Forty years on, and it's still outstanding.","Kubrick, King and Nicholson, the writing was l...",10,18 October 2020,Sleepin_Dragon,The Shining
1,One of my favorite films,"The Shining, you know what's weird about this ...",10,23 November 2003,Smells_Like_Cheese,The Shining
2,An absolute classic. Even if it does stray aw...,While I can understand a lot of Stephen King's...,10,20 June 2022,b_kite,The Shining
3,A classic horror from a master director,When Jack Torrance (Nicholson) is offered a jo...,-,29 October 2001,bob the moo,The Shining
4,Eeriness surpassed by class,Sometimes all good horror needs is a good idea...,-,24 November 2008,chaos-rampant,The Shining

The Great Dictator

,titlu,text,rating,data,utilizator,film
0,The Man With Hitler's Face,"""The Great Dictator"" (United Artists, 1940), b...",9,9 January 2001,lugonian,The Great Dictator
1,Immortal classic movie with dual character fo...,This ingenious and innovate comedy packs many ...,8,3 March 2009,ma-cortes,The Great Dictator
2,'In this world there is room for everyone'...,... and in today's parlance that means regardl...,9,20 October 2020,Xstal,The Great Dictator
3,"""Can you hear that?""","Back at the dawn of the talkie era, Charlie Ch...",9,18 October 2010,Steffi_P,The Great Dictator
4,Chaplin's comment on fascism is his first tal...,"Hynkel, dictator of Tomania, is a spoiled chil...",8,14 September 2000,Nazi_Fighter_David,The Great Dictator

Avengers: Infinity War

,titlu,text,rating,data,utilizator,film
0,"Best movie of the MCU, incredible from start ...",Infinity War is remembered mostly for how it e...,10,24 January 2021,RJBrez,Avengers: Infinity War
1,Great,This movie portrays a villain that by far has ...,-,23 February 2020,MrHeraclius,Avengers: Infinity War
2,Best Cliffhanger of all Time,A meticulously planned film down to the last d...,10,5 February 2021,Alex_Lo,Avengers: Infinity War
3,Better than Endgame,Infinity war is one of the best MCU protects. ...,10,14 March 2021,grztxks,Avengers: Infinity War
4,EMOTIONAL ROLLER COASTER,Avengers infinity war is an emotional roller c...,9,16 February 2021,andreascaloni,Avengers: Infinity War

Witness for the Prosecution

,titlu,text,rating,data,utilizator,film
0,The Goal Is Always Justice,"In a recent biography of Billy Wilder, Agatha ...",9,6 March 2006,bkoganbing,Witness for the Prosecution
1,Dynamite courtroom drama,This is one of the absolute best courtroom mov...,10,16 July 2006,planktonrules,Witness for the Prosecution
2,EntertainingTrial Movie That Still Holds Up,"This is one of the best ""trial movies"" ever ma...",9,8 November 2005,ccthemovieman-1,Witness for the Prosecution
3,This had me to the bitter end!,"I love it when a movie captivates me, carries ...",9,10 March 2006,Hitchcoc,Witness for the Prosecution
4,Another triumph for cinematic genius Billy Wi...,Billy Wilder is a director with an understandi...,8,3 February 2005,The_Void,Witness for the Prosecution

Aliens

,titlu,text,rating,data,utilizator,film
0,A masterpiece - one of the best epic-action f...,Aliens (1986) is the best Epic Sci-Fi Classic ...,10,13 February 2018,ivo-cobra8,Aliens
1,One of the best films ever made.,So often when you think of sequels you imagine...,10,4 February 2020,Sleepin_Dragon,Aliens
2,Excellent sequel--matches the brilliance of t...,Series note: It is strongly advised that you w...,10,7 February 2005,BrandtSponseller,Aliens
3,James Cameron and Bill Paxton at their finest,There are really good movies and then there's ...,10,15 June 1999,baumer,Aliens
4,One of the most thrilling films ever- special...,James Cameron is an extremely talented action ...,10,31 August 2005,Derek237,Aliens

Spider-Man: Into the Spider-Verse

,titlu,text,rating,data,utilizator,film
0,Fantastic...but possibly overwhelming.,"""Spider-Man: Into the Spider-Verse"" is a fanta...",10,26 March 2019,planktonrules,Spider-Man: Into the Spider-Verse
1,So Much More Than I Expected!,"So many have commented, so I will be brief. Fr...",10,19 November 2019,Hitchcoc,Spider-Man: Into the Spider-Verse
2,How on God's green Earth did this work so wel...,The worlds of superhero movies and superhero c...,8,21 December 2018,matthewssilverhammer,Spider-Man: Into the Spider-Verse
3,Stan Lee Is Smiling Right Now,A movie worthy of Stan Lee's approval. Incredi...,10,17 December 2018,eaglescout910,Spider-Man: Into the Spider-Verse
4,Game Changer,Have you ever sat through a film and you knew ...,10,21 December 2018,cafesmitty,Spider-Man: Into the Spider-Verse

American Beauty

,titlu,text,rating,data,utilizator,film
0,Entertaining and Thought-Provoking.,"Of the 250+ films I've seen and rated on IMDb,...",10,15 January 2004,the-evil-cult,American Beauty
1,An Oscar well deserved.,This film is one of a kind. After seeing this...,10,29 May 2000,RueMorgue,American Beauty
2,An American Masterpiece,"This is by far one of the best, if not THE, mo...",10,14 August 2001,Smells_Like_Cheese,American Beauty
3,Beautiful...so beautiful,American Beauty is the greatest movie ever mad...,10,9 September 2000,Antithesys,American Beauty
4,Could be the best movie of the year.,And there were a lot of great ones this year. ...,-,16 September 1999,Rusty-61,American Beauty

Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb

,titlu,text,rating,data,utilizator,film
0,"""Gentlemen, you can't fight in here! This is ...",DR. STRANGELOVE.... is a satirical black comed...,10,29 July 2017,elvircorhodzic,Dr. Strangelove or: How I Learned to Stop Worr...
1,Sharp and outrageously entertaining,I never really bought into the Kubrick hype. I...,10,26 December 2013,gogoschka-1,Dr. Strangelove or: How I Learned to Stop Worr...
2,The only movie that makes you laugh at the en...,This movie is absolutely brilliant! It might n...,10,1 October 2005,Boba_Fett1138,Dr. Strangelove or: How I Learned to Stop Worr...
3,"Still laughing, long past the end credits...",Who'd have thought that Kubrick had such a gre...,10,22 December 2004,TBJCSKCNRRQTreviews,Dr. Strangelove or: How I Learned to Stop Worr...
4,Laughing at Fear,What makes this film so powerful is the messag...,10,14 August 1998,Sickfrog,Dr. Strangelove or: How I Learned to Stop Worr...

The Dark Knight Rises

,titlu,text,rating,data,utilizator,film
0,A wonderful conclusion to a wonderful trilogy.,"After eight years in seclusion, Batman resurfa...",9,1 January 2013,Geeky Randy,The Dark Knight Rises
1,Batman,Christopher Nolan's epic trilogy concludes in ...,-,12 February 2020,MrHeraclius,The Dark Knight Rises
2,Best comic movie trilogy ever,The Dark Knight Rises capped off what is proba...,10,19 January 2013,Maniac-9,The Dark Knight Rises
3,Epic,The Dark Knight Rises was a perfect sequel to ...,9,2 June 2013,CaptKeshav,The Dark Knight Rises
4,My personal favourite of the trilogy,"I think as a film stand point, the dark knight...",10,20 February 2021,Morejambo54,The Dark Knight Rises

Oldboy

,titlu,text,rating,data,utilizator,film
0,A cinematic bad boy,Oldboy really is an odd movie. It's totally un...,10,8 September 2016,Leofwine_draca,Oldboy
1,You Only Live Once...,"Imagine what you'd do, when you wake from a ba...",10,22 January 2022,Xstal,Oldboy
2,Excellent in it's sickness,I looked at program for today and I saw movie ...,10,22 July 2007,johnny-08,Oldboy
3,If only we were all living in Asia....,To start off; This is the one and only film th...,10,19 December 2007,bur_007,Oldboy
4,Freaked me out,I haven't written a comment on IMDb for about ...,9,29 July 2007,Genevieve_X,Oldboy

Inglourious Basterds

,titlu,text,rating,data,utilizator,film
0,I have NEVER seen such a performance ... ever!,"No, I'm not speaking of Brad Pitt; I'm speakin...",10,27 February 2020,tkarlmann,Inglourious Basterds
1,Quentin Tarantino's style and Christoph Waltz...,"In 1941 Nazi-occupied France, ""The Jew Hunter""...",8,30 May 2014,SnoopyStyle,Inglourious Basterds
2,I can't believe I just now watched this for t...,This is a perfect Tarantino movie. It's explos...,10,7 February 2020,laurabethc1,Inglourious Basterds
3,Tarantino's best? I think so,No joke – I believe this film to be Tarantino'...,10,5 August 2016,Leofwine_draca,Inglourious Basterds
4,People seem to be missing the point,"This review gives everything away, so see the ...",10,10 July 2012,ablewuzi,Inglourious Basterds

Amadeus

,titlu,text,rating,data,utilizator,film
0,One of those movies that you'll never forget,"I remember as a child, my sister told me to wa...",10,16 November 2003,Smells_Like_Cheese,Amadeus
1,The Movie That Made Me Appreciate Mozart,"Before I saw this movie, I respected Mozart's ...",9,26 November 2006,possumopossum,Amadeus
2,"Absolutely brilliant!- funny, charming and to...","I adore classical music, and Mozart is one of ...",10,7 March 2010,TheLittleSongbird,Amadeus
3,True Gem for Movie and Music Fans,I'd like to point out a few facts before I rev...,10,30 January 2007,miknnik,Amadeus
4,To give everything you have to music and come...,"At the tender age of 26, when I still thought ...",9,16 January 2010,AlsExGal,Amadeus

Coco

,titlu,text,rating,data,utilizator,film
0,Succeeds on all levels,Music is banned in Miguel's household after hi...,10,1 May 2018,neil-476,Coco
1,Shocked!,I knew absolutely nothing about this movie wal...,10,1 December 2017,jon-stokes21-539-17875,Coco
2,What's not to like?!,"I am very glad I saw ""Coco"" and understand exa...",10,31 October 2018,planktonrules,Coco
3,Coco is the number one Pixar cartoon I've see...,"There are no shortcomings in the picture, conn...",10,18 July 2020,h-42927-48851,Coco
4,I cried twice watching this.,I have always been a fan of Pixar. They are re...,10,2 December 2017,pramsalim,Coco

Toy Story

,titlu,text,rating,data,utilizator,film
0,Technically impressive with great script and ...,Andy's toys live a reasonable life of fun and ...,-,22 April 2003,bob the moo,Toy Story
1,"Excellent Viewing, Every Time!",This is a very clever animated story that was ...,10,18 February 2007,ccthemovieman-1,Toy Story
2,"Created a decade ago, but still stunning",I am a big fan of the animated movies coming f...,9,25 December 2004,philip_vanderveken,Toy Story
3,"""I can safely say that I have not enjoyed ani...",Toy Story – 5/5 starsChildren play with toys. ...,10,21 February 2003,MovieAddict2016,Toy Story
4,One of the Best Animated Films Ever!,Toy Story is a sheer delight to view on the sc...,10,13 February 2000,Quinoa1984,Toy Story

Joker

,titlu,text,rating,data,utilizator,film
0,I would not call it a masterpiece as some did,There is no doubt that the movie was well thou...,7,15 October 2019,TVpotatoCat,Joker
1,Not a spoon feeding of CGI fueled faux drama.,The movie affects you in a way that makes it p...,9,5 October 2019,brianmlucas,Joker
2,Is it great? I don't know.,When I heard everyone saying that this is the ...,7,25 October 2019,ernestoherreraf,Joker
3,Perfect in every aspect.,"Truly a masterpiece, The Best Hollywood film o...",10,1 September 2019,Aman_Goyal,Joker
4,"A psychological study, rather than a superher...",I have seen Joker yesterday at Venice an early...,10,1 September 2019,Come-and-Review,Joker

Braveheart

,titlu,text,rating,data,utilizator,film
0,"""Every man dies, not every man really lives.""",The Academy Award winning war epic Braveheart ...,-,24 February 2020,MrHeraclius,Braveheart
1,It's a Masterpiece. Best Movie of All Time,Braveheart is the best movie ever made in hist...,10,4 August 2019,heisenberg12,Braveheart
2,"Your Heart is Free, Have the Courage to Follo...","A simple message but even today, over seven hu...",8,6 September 2020,Xstal,Braveheart
3,One of the best modern movies of time,I'm talking just in the 90's. The 90's were a ...,10,21 April 2002,Smells_Like_Cheese,Braveheart
4,Freeeeeedooooommm....,It doesn't get any better than this. Mel Gibso...,10,12 March 2021,brentcollyer,Braveheart

The Boat

,titlu,text,rating,data,utilizator,film
0,Epic,"What impresses me the most about the film, as ...",-,1 April 2005,jaywolfenstien,The Boat
1,Probably the greatest WWII naval movie,"This is an amazing achievement, and it's obvio...",10,12 July 2006,planktonrules,The Boat
2,German Masterpiece,"In October 1941, the German Capt.-Lt. Henrich ...",10,25 November 2017,claudio_carvalho,The Boat
3,Emotionally Draining,My late father served in the Royal Navy in WWI...,10,7 December 2020,Essex_Rider,The Boat
4,"Believable, above all, and a WWII submarine m...",Das Boot (1981)Widely considered the most impr...,8,19 December 2010,secondtake,The Boat

Avengers: Endgame

,titlu,text,rating,data,utilizator,film
0,Not as good as infinity war..,But its a pretty good film. A bit of a mess in...,7,29 April 2019,MoistMovies,Avengers: Endgame
1,Not as good as infinity war but a great movie,Rating: 8.6Not as good as Infinity war pacing-...,8,13 December 2021,ACollegeStudent,Avengers: Endgame
2,Emotional but bit messy.,"So it all ends. I have loved most of the MCU, ...",7,27 April 2019,nickgray-12862,Avengers: Endgame
3,Crazy in every sense,This film is an emotional rollercoaster with s...,10,26 November 2021,davyjones-636363,Avengers: Endgame
4,Perfect ending,"After watching Infinity war, I was looking for...",10,8 May 2019,dhiraj-yahoo,Avengers: Endgame

Princess Mononoke

,titlu,text,rating,data,utilizator,film
0,one of the best films i've ever had the chanc...,"Princess Mononoke is, without a doubt, one of ...",10,7 November 1999,zetes,Princess Mononoke
1,Allegory on the balance between humans and na...,This seems to be Miyazake's most personal work...,10,15 April 2003,TanjBennett,Princess Mononoke
2,Absolutely breathtaking!,Princess Mononoke is one of the best animated ...,10,4 August 2009,TheLittleSongbird,Princess Mononoke
3,"Breathtaking. Watch with ""eyes unclouded.""","In its theatrical Japanese release of 1997, PR...",10,20 March 2005,JTurner82,Princess Mononoke
4,Princess Mononoke is Miyazaki's masterpiece.,"I've found it, I've finally found it. Studio G...",10,28 February 2018,TheMovieDiorama,Princess Mononoke

Once Upon a Time in America

,titlu,text,rating,data,utilizator,film
0,"Last, butchered, unappreciated, work from one...",... Directors of all time. Let's start with a ...,10,6 November 2013,A_Different_Drummer,Once Upon a Time in America
1,Make sure you get the director's cut!,"Many people compare ""Once Upon a Time in Ameri...",10,19 September 2004,philip_vanderveken,Once Upon a Time in America
2,A wonderful epic that is really only about on...,Noodles returns to the New York of his youth i...,-,21 September 2002,bob the moo,Once Upon a Time in America
3,Once a street teenager,"Years later, the desperate noodles returned to...",10,15 May 2020,w-71474,Once Upon a Time in America
4,"A sprawling, deliberately paced, and generall...","It's been said that when one watches a ""spaghe...",10,19 October 2003,Quinoa1984,Once Upon a Time in America

Good Will Hunting

,titlu,text,rating,data,utilizator,film
0,"A slow burner, a fine achievement","Sure, this film's plot is fairly predictable. ...",10,17 March 1999,Stephen-12,Good Will Hunting
1,Incredible,I don't think I have been this moved by a movi...,10,13 October 2011,TheLittleSongbird,Good Will Hunting
2,This movie has a brilliant script...,It appears the jury is hung... many people eit...,10,21 January 2001,rondine,Good Will Hunting
3,The Genius In Our Midst,So many personal projects of our best players ...,10,3 September 2008,bkoganbing,Good Will Hunting
4,"""I had to go see about a girl""",This is one of those films that you cant help ...,9,29 October 2008,RedRoadster,Good Will Hunting

Your Name.

,titlu,text,rating,data,utilizator,film
0,could be the greatest love story of all time,"In truth, the most competitive area of fiction...",10,2 February 2017,A_Different_Drummer,Your Name.
1,"Once seen, never forgotten- truly magnificent",'Your Name' is not just one of the best animes...,10,9 December 2016,TheLittleSongbird,Your Name.
2,Forget Disney! We have movies like Your Name.,Your Name is just a good movie. This movie fel...,10,8 February 2018,johnnybianchino,Your Name.
3,"Cosmically enchanting, touching and visually ...",It's been a while since I've seen something ou...,10,27 November 2016,SpoilerAlertReviews,Your Name.
4,"Yes, yes and yes!",Absolutely fantastic! Recommended for everyone...,10,10 September 2016,malcydon,Your Name.

3 Idiots

,titlu,text,rating,data,utilizator,film
0,Wonderfully entertaining.,"It's hard for me to review this film, as I hav...",10,2 June 2011,planktonrules,3 Idiots
1,Wow this American loves this movie,I asked my co-workers to recommend a Bollywood...,9,20 November 2011,donutpizza,3 Idiots
2,Finally a masterpiece from Bollywood. Aamir K...,Awesome film man. Saw this with my family in a...,10,9 September 2013,Fella_shibby,3 Idiots
3,THE BEST OF BOLLYWOOD; please sing along....,"When I was 13, I had my first movie-love;\nThe...",10,15 June 2021,pawanpunjabithewriter,3 Idiots
4,"Don't be fooled by its name, it's a great movie",The film not only shows the mistakes of the ed...,9,3 August 2021,jack_o_hasanov_imdb,3 Idiots

Singin' in the Rain

,titlu,text,rating,data,utilizator,film
0,Now that's entertainment!,Singin In the Rain is arguably the best movie ...,10,2 January 2011,AlsExGal,Singin' in the Rain
1,A fabulous musical romance about film technology,Don Lockwood (Gene Kelly) and Lina Lamont (Jea...,10,1 May 2005,BrandtSponseller,Singin' in the Rain
2,The talkies,The transition from the silent film era to the...,10,2 January 2006,jotix100,Singin' in the Rain
3,One of the best Hollywood musicals,This isn't my all time favorite (that goes to ...,10,22 January 2005,preppy-3,Singin' in the Rain
4,It Ain't Been in Vain for Nothing,Singin' in the Rain is one of the best movies ...,-,29 August 2005,drednm,Singin' in the Rain

Requiem for a Dream

,titlu,text,rating,data,utilizator,film
0,"Great movie, I hated every minute of it",This movie is about how drugs can affect your ...,9,5 September 2020,hwm-05554,Requiem for a Dream
1,A visual assault on the senses about the hell...,"Jared Leto, Marlon Wayans, Jennifer Connelly a...",10,23 August 2016,planktonrules,Requiem for a Dream
2,"Great direction, great acting, great score, g...",Harry and Tyrone are drug users who decide to ...,-,10 October 2004,bob the moo,Requiem for a Dream
3,Like being repeatedly punched in the back of ...,It's difficult to know what to say about Requi...,10,30 January 2002,Danfish,Requiem for a Dream
4,Powerful and Unforgettable.,"Fantastic, Oscar Worthy Acting. Beautiful Dire...",9,1 August 2020,mikerudakov,Requiem for a Dream

High and Low

,titlu,text,rating,data,utilizator,film
0,"If you like ransom/police storiesmysteries, a...","High and Low, like Yojimbo and Throne of Blood...",10,30 August 2004,Quinoa1984,High and Low
1,Kurosawa at his best and most subtle,This is one of those rare movies I had to watc...,10,1 August 2004,jemmytee,High and Low
2,"The film ""Ransom"" could have been.","""High and Low"" is one of those deceptive detec...",10,27 July 2004,kmscb-1,High and Low
3,Intense and Highly Entertaining,"""High and Low"" could be considered two movies....",10,10 October 2001,dorlago,High and Low
4,"""I'd rather be told the cruel truth than to b...",Up till now I've only seen Toshiro Mifune in K...,8,6 April 2018,classicsoncall,High and Low

Toy Story 3

,titlu,text,rating,data,utilizator,film
0,"An amazing third ""Story""","Lee Unkrinch directed ""Toy Story 3,"" the third...",10,4 November 2010,dee.reid,Toy Story 3
1,Wonderful and Touching for Adults Imagine fo...,Andy is now seventeen years old and is going t...,10,15 November 2010,claudio_carvalho,Toy Story 3
2,A Nutshell Review: Toy Story 3,It was in 1995 that Toy Story signaled the arr...,10,17 June 2010,DICK STEEL,Toy Story 3
3,~One of the Best Trilogies of All Time~,I attended a special screening for Toy Story 3...,10,27 May 2010,The_Fifth_Echo,Toy Story 3
4,By delivering an amazing finale to an amazing...,Star Wars. Indiana Jones. Fistful of Dollars. ...,10,18 June 2010,diac228,Toy Story 3

Capernaum

,titlu,text,rating,data,utilizator,film
0,Capernaum,Zain Al Rafeea is a terrific revelation in thi...,-,13 February 2020,MrHeraclius,Capernaum
1,Well made but very difficult to watch....and ...,"""Capernaum"" is a very unpleasant film that dea...",8,23 July 2020,planktonrules,Capernaum
2,I Also Accuse My Parents,Watch this and you'll never feel poor again. Y...,9,24 August 2020,thesar-2,Capernaum
3,The Best Foreign Film Ever Made?,I have taken so long to review this film becau...,-,16 November 2018,andrewestrella,Capernaum
4,Made a grumpy old white guy cry,This movie was almost unwatchable for me at ti...,10,12 July 2019,bugsmoran29,Capernaum

Star Wars: Episode VI - Return of the Jedi

,titlu,text,rating,data,utilizator,film
0,The most peculiar Star Wars and under appreci...,Totally should've won at least some of the awa...,10,16 January 2020,UniqueParticle,Star Wars: Episode VI - Return of the Jedi
1,Good,I didn't watch this movie when I was a kid.It ...,8,22 August 2021,jack_o_hasanov_imdb,Star Wars: Episode VI - Return of the Jedi
2,"The Boy Who Loved ""Star Wars""","A long time ago, in a galaxy far, far away.......",10,2 December 2005,evanston_dad,Star Wars: Episode VI - Return of the Jedi
3,Good,I like the bit when the ewoks crush an ATST wi...,10,30 March 2020,bevo-13678,Star Wars: Episode VI - Return of the Jedi
4,One Of The Best In The Series,Up until the sixth and last episode of the Sta...,9,12 February 2006,ccthemovieman-1,Star Wars: Episode VI - Return of the Jedi

Eternal Sunshine of the Spotless Mind

,titlu,text,rating,data,utilizator,film
0,"""Eternal Sunshine of the Spotless Mind"" is a ...","""How happy is the blameless vestal's lot! The ...",10,2 June 2004,MovieAddict2016,Eternal Sunshine of the Spotless Mind
1,Meet me in Montauk...,How happy is the blameless vestal's lot! The w...,10,26 March 2004,tccandler,Eternal Sunshine of the Spotless Mind
2,Absolutely wonderful,When I first saw Eternal Sunshine of the Spotl...,10,24 November 2010,TheLittleSongbird,Eternal Sunshine of the Spotless Mind
3,an modern artistic triumph for all involved,"Michel Gondry, credited as the director and co...",10,27 October 2004,Quinoa1984,Eternal Sunshine of the Spotless Mind
4,Perfect - a movie that puts 99% of all contem...,"There's only one way to describe ""Eternal Suns...",10,2 July 2004,Superunknovvn,Eternal Sunshine of the Spotless Mind

2001: A Space Odyssey

,titlu,text,rating,data,utilizator,film
0,Unmatched accomplishment,Sometimes reading the user comments on IMDB fi...,10,17 June 2003,simon_booth,2001: A Space Odyssey
1,Legendary,"A stand-alone monument in cinema history, Stan...",10,14 April 2018,Wesley-Wang,2001: A Space Odyssey
2,It's a puzzlement...,There are two schools of thought about 2001: A...,-,17 June 2002,Doylenf,2001: A Space Odyssey
3,The Sci-Fi That Put The Science In Science Fi...,"Putting the science in science-fiction, 2001: ...",-,2 September 2013,CinemaClown,2001: A Space Odyssey
4,Ahead of its time but...,I felt the need to review this movie after rea...,7,24 June 2013,suws1,2001: A Space Odyssey

Reservoir Dogs

,titlu,text,rating,data,utilizator,film
0,For all I know you are the rat; and this migh...,Reservoir Dogs is the debut of director and wr...,9,26 August 2010,hitchcockthelegend,Reservoir Dogs
1,Quentin Tarantino begins his directing career...,Reservoir Dogs is a testament to the idea that...,10,18 August 2000,Anonymous_Maxine,Reservoir Dogs
2,"Simply brilliant; short, tight and taut",Crime boss Joe Cabot brings together a group o...,-,28 January 2004,bob the moo,Reservoir Dogs
3,A stylish and excellent example of expert sto...,After watching this half a dozen times with a ...,8,31 May 2006,TBJCSKCNRRQTreviews,Reservoir Dogs
4,"These 'Dogs' bark a lot, but they bite, too ...","Bloodily violent, irreverently shocking, polit...",10,9 May 2011,ElMaruecan82,Reservoir Dogs

Come and See

,titlu,text,rating,data,utilizator,film
0,One of the greatest wars films ever made,"One of the greatest of all war films, Klimov's...",10,29 December 2004,FilmFlaneur,Come and See
1,Masterpiece alert!,"Even before the final credits rolled, I strong...",10,3 May 2007,Asa_Nisi_Masa2,Come and See
2,Jaw-droppingly powerful and truly disturbing ...,"""Come and See"" has to be one of the most power...",10,6 July 2006,HumanoidOfFlesh,Come and See
3,horrors of war in 1940s Belarus,Elem Klimov's final film is a devastating look...,10,7 January 2017,lee_eisenberg,Come and See
4,Overwhelming masterpiece of a child's awakeni...,This is one of the most realistic war films ev...,10,26 April 2021,clanciai,Come and See

The Hunt

,titlu,text,rating,data,utilizator,film
0,Once Again: The Children's Hour,Having worked as a teacher for some forty year...,8,30 January 2014,Hitchcoc,The Hunt
1,He doesn't have a basement....,There is a moment in this masterpiece when you...,10,6 December 2013,FlashCallahan,The Hunt
2,excellent drama that is tough to watch,The thing about Thomas Vinterberg's The Hunt t...,10,21 May 2015,Quinoa1984,The Hunt
3,The scary thing is that this could happen to ...,One of my favorite foreign language films it T...,9,18 January 2014,planktonrules,The Hunt
4,A film for those who stupidly believe there's...,Sometimes children lie. Sometimes good people...,10,5 December 2012,TheSquiss,The Hunt

Citizen Kane

,titlu,text,rating,data,utilizator,film
0,"CITIZEN KANE may let some people down, but it...",It's a difficult undertaking for someone of my...,-,2 May 2004,Cowman,Citizen Kane
1,The Citizen Kane of Movies,"The most frequently acclaimed ""greatest film e...",10,6 December 2020,Cineanalyst,Citizen Kane
2,"A great piece of cinema, a magnificent exampl...",I've heard so much told about Citizen Kane and...,10,21 October 2004,TBJCSKCNRRQTreviews,Citizen Kane
3,All That Ballyhoo!,On the Criterion Collection DVD of Orson Welle...,8,5 May 2008,WriterDave,Citizen Kane
4,An Expert On What People Will Think,The problem with writing about a film like Cit...,10,25 April 2007,bkoganbing,Citizen Kane

M

,titlu,text,rating,data,utilizator,film
0,Ahead of its time,This is a very interesting film on so many lev...,9,16 January 2010,AlsExGal,M
1,Fritz Lang's (sound) masterpiece- a taut and ...,"The first time I saw M, by Fritz Lang, I almos...",10,29 July 2005,Quinoa1984,M
2,Moments of menace..,"The economy, austerity and directness of the f...",8,31 January 2002,Nazi_Fighter_David,M
3,A masterpiece of visual drama; brilliantly ac...,"M / (1931) **** \t""M"" is a cinematic masterpie...",10,1 June 2000,Movie-12,M
4,Influential and unforgettable masterpiece.,Fritz Lang's highly influential career as a fi...,10,31 March 2006,EThompsonUMD,M

Lawrence of Arabia

,titlu,text,rating,data,utilizator,film
0,Makes a Strong Case for Best Film Ever.,"The definitive epic of the cinema's history. ""...",-,6 August 2002,tfrizzell,Lawrence of Arabia
1,Majesty in the Desert,The moment David Lean makes you aware you are ...,10,29 April 2005,evanston_dad,Lawrence of Arabia
2,a memento from the days when they made real m...,"It is, in a way, depressing to watch this movi...",9,15 June 1999,rupie,Lawrence of Arabia
3,"Peter O'Toole as Lawrence, what a treat!",Did you know that Cary Grant had been approach...,10,10 July 2018,maureenmcqueen,Lawrence of Arabia
4,One of the greatest films of all time.,Disobedient Army officer Lawrence attempts to ...,10,25 December 2022,Sleepin_Dragon,Lawrence of Arabia

North by Northwest

,titlu,text,rating,data,utilizator,film
0,What an Action Thriller Should Be.,VERTIGO did nothing to advance Hitchcock's car...,10,11 April 2005,nycritic,North by Northwest
1,Classic thriller - I love it!,Roger Thornhill is an advertising man. Howeve...,-,27 July 2002,bob the moo,North by Northwest
2,Strangers on a train,"Alfred Hitchcock's ""North by Northwest"" is one...",10,30 October 2005,jotix100,North by Northwest
3,Enormously entertaining film from Alfred Hitc...,"My favourite director, Alfred Hitchcock has di...",9,9 June 2009,TheLittleSongbird,North by Northwest
4,I finally get how great it is: Hitch infuses ...,"Its Hitch's most briskly entertaining movie, a...",8,24 July 2004,Ben_Cheshire,North by Northwest

Vertigo

,titlu,text,rating,data,utilizator,film
0,Distinctive & Unforgettable Masterpiece,One of the many things that made Hitchcock suc...,-,19 June 2001,Snow Leopard,Vertigo
1,Let there be color!,Since there are already so many real good comm...,10,26 January 2005,slabihoud,Vertigo
2,You're not lost. Mother's here.,"John ""Scottie"" Ferguson is a San Francisco cop...",10,19 July 2009,hitchcockthelegend,Vertigo
3,Creepy and engaging.,It's rather strange that this film was a box o...,9,31 August 2012,planktonrules,Vertigo
4,Detective Obsessed,Although it got at best mixed reviews when fir...,9,3 December 2005,bkoganbing,Vertigo

Ikiru

,titlu,text,rating,data,utilizator,film
0,"""Only when he learned he would die did he sta...","Ikiru (""to live"")is a Kurosawa film devoid of ...",10,11 January 2003,OttoVonB,Ikiru
1,a cinematic experience that's a near-nexus of...,Akira Kurosawa knew how to get in touch with h...,10,19 May 2004,Quinoa1984,Ikiru
2,"The Older You Get, the More It Means",I too have seen all the Samurai films. It was ...,9,12 October 2009,Hitchcoc,Ikiru
3,Complex and thought-provoking masterpiece,Ikiru is a film about life. Constantly complex...,8,16 December 2004,The_Void,Ikiru
4,To Live in Death,Probably one of the most difficult aspects a f...,10,11 June 2004,Serge_Zehnder,Ikiru

The Apartment

,titlu,text,rating,data,utilizator,film
0,"""I've Decided to Take My Doctor's Advice, I'm...",In the recent biography of Billy Wilder by Ed ...,10,14 June 2006,bkoganbing,The Apartment
1,"Likewise, it's a love-fest Lemmon-wise","One of the finest examples of smart, satiric c...",10,28 June 2001,moonspinner55,The Apartment
2,Becoming A Mensch,"Ohhh - after my 4th or 5th viewing, I think th...",10,21 January 2005,davidals,The Apartment
3,WILDER'S GREATEST ACCOMPLISHMENT,"Billy Wilder's ""The Apartment is his greatest ...",10,24 May 2001,KatMiss,The Apartment
4,A classic in every sense of the word,"My local cinema does ""Secret Movie Night"" once...",10,11 May 2018,bankofmarquis,The Apartment

Amélie

,titlu,text,rating,data,utilizator,film
0,This is rated so highly cause it deserves it,"A slice of heaven right here on earth, ""Amelie...",10,1 March 2003,Boyo-2,Amélie
1,Finds its charm in the little things,'Le Fabuleux Destin d'Amélie Poulain' finds it...,9,14 August 2004,rbverhoef,Amélie
2,What is left to say about this glorious joy r...,I had heard superlative comments on this film ...,10,15 March 2002,wisewebwoman,Amélie
3,"A hilarious, warm movie in a world all its own.",Not a lot of movies create their own sort of u...,10,19 December 2001,alastair_m,Amélie
4,She makes ME fall in love too!,"To start off with, I heard a lot of good thing...",10,2 January 2003,mucronate,Amélie

A Clockwork Orange

,titlu,text,rating,data,utilizator,film
0,One of those films you have to watch multiple...,It's hard to judge a film such as this. Its co...,10,28 April 2002,Agent10,A Clockwork Orange
1,One of Kubrick's best,To say that the Alex character from Stanley Ku...,10,25 February 2004,MovieAddict2016,A Clockwork Orange
2,We Are Seeing Our Future,Having read Anthony Burgess's novel years ago ...,9,14 March 2006,Hitchcoc,A Clockwork Orange
3,"A great, but hard watch",I've struggled a bit with this film more than ...,8,26 November 2019,davidmvining,A Clockwork Orange
4,Kubrick and the Art of Violence.,Stanley Kubrick has a way of telling stories a...,10,6 November 2005,nycritic,A Clockwork Orange

Double Indemnity

,titlu,text,rating,data,utilizator,film
0,"One of the best films noir ever, Double Indem...","This is one of the best films of all time, not...",10,8 November 2000,Anonymous_Maxine,Double Indemnity
1,Justifiably At The Top Of Most Film Noir Lists,This is one of the best-liked classic films of...,10,23 December 2005,ccthemovieman-1,Double Indemnity
2,Absorbing and worthy suspense film about blac...,"Vintage Noir Film with gritty interpretation ,...",8,30 June 2015,ma-cortes,Double Indemnity
3,"Some times, when they least expect it.....",There are occasional times when all the elemen...,10,17 July 2005,jotix100,Double Indemnity
4,It fits together like a watch,"I've now seen this movie 14 times in 25 years,...",9,2 May 2004,Spondonman,Double Indemnity

Full Metal Jacket

,titlu,text,rating,data,utilizator,film
0,Paint It Black,"""With flowers and my love both never to come b...",10,16 November 2009,Lechuguilla,Full Metal Jacket
1,Very well made--tough to watch.,Warning--This movie is NOT for young kids or t...,9,1 July 2009,planktonrules,Full Metal Jacket
2,'Born To Kill' - The best Vietnam war movie o...,SPOILER: Full Metal Jacket is a 1987 realistic...,10,14 October 2015,ivo-cobra8,Full Metal Jacket
3,A film of two halves,'Full Metal Jacket' was a film that I had been...,6,9 September 2013,tr91,Full Metal Jacket
4,The movies finally got Parris Island right,Though I've read only a couple of dozen of the...,8,22 December 2006,brujay-1,Full Metal Jacket

Scarface

,titlu,text,rating,data,utilizator,film
0,"A stone cold, 100% gangster classic",Words alone cannot express how much I love thi...,10,10 December 2016,Leofwine_draca,Scarface
1,"""You wanna play rough?? OKAY!""","""Scarface"" has a major cult following even now...",10,19 December 2005,Aditya_Gokhale,Scarface
2,Exceed to Excess,Every great gangster movie has under-currents ...,9,12 September 2004,akpiggott,Scarface
3,The Real Scarface.,"""A Classic is something that everybody wants t...",10,28 January 2007,TruPretender,Scarface
4,One Word: PERFECT!!!!!!!,"Scarface has a great storyline, brutal violenc...",-,24 February 2020,MrHeraclius,Scarface

Hamilton

,titlu,text,rating,data,utilizator,film
0,just superb,Greetings again from the darkness. You know wh...,9,4 July 2020,ferguson-6,Hamilton
1,Musical history,'Hamilton' was a major surprise for me when se...,10,13 July 2020,TheLittleSongbird,Hamilton
2,Really enjoyed it,"I am not even a fan of musicals, but this is e...",-,4 July 2020,Gordon-11,Hamilton
3,"Grateful for the captions, the pause button, ...",I started watching this out of curiosity and t...,8,4 July 2020,rebekahrox,Hamilton
4,BEAUTIFUL,I'm a mexican boy who has never got the chance...,10,3 July 2020,guapo_andres,Hamilton

Top Gun: Maverick

,titlu,text,rating,data,utilizator,film
0,The truly epic blockbuster we needed.,"Wow. The first Top Gun is a classic, and as we...",10,23 May 2022,Top_Dawg_Critic,Top Gun: Maverick
1,This is slightly different to the other revie...,If you were a late teen or in your early twent...,10,26 May 2022,scottedwards-87359,Top Gun: Maverick
2,Best Sequel yet,In one of the more memorable lines in the orig...,10,25 May 2022,goshamorrell,Top Gun: Maverick
3,This is why we go to the movies,This is one sequel that looked like it would n...,10,27 May 2022,dtucker86,Top Gun: Maverick
4,Let me just say...,"I was reluctantly dragged into the theater, th...",10,26 May 2022,lovefalloutkindagamer,Top Gun: Maverick

Incendies

,titlu,text,rating,data,utilizator,film
0,A stunning and powerful thriller,Want to see where one of the modern era's hott...,10,8 May 2018,eddie_baggins,Incendies
1,One word: INCREDIBLE!,"Initially, the film can be a bit confusing due...",8,16 November 2019,paulclaassen,Incendies
2,Our Love Became a Funeral Pyre,"When people watch the Oscars, they don't usual...",9,26 March 2011,alexart-1,Incendies
3,Unforgettable,A bona fide masterpiece. As simple as that. It...,10,15 October 2010,corrosion-2,Incendies
4,A work of devastating power...,"""Incendies (Scorched)"" opened in town this Fri...",9,26 January 2011,ilpintl,Incendies

To Kill a Mockingbird

,titlu,text,rating,data,utilizator,film
0,One of the most important films of all time,To Kill a Mockingbird is the movie based on th...,10,9 November 2003,FilmOtaku,To Kill a Mockingbird
1,"Not just film, but film history",The first time I saw To Kill A Mockingbird was...,10,1 April 2004,clydestuff,To Kill a Mockingbird
2,Perpetually & Eternally Outstanding...,"It's a story that's riven with themes, of prej...",9,5 September 2022,Xstal,To Kill a Mockingbird
3,Amazing film,After hearing nothing but critical acclaim for...,10,4 September 2004,TBJCSKCNRRQTreviews,To Kill a Mockingbird
4,Wonderful Social Classic That Echoes Issues o...,TO KILL A MOCKINGBIRD is presented like a play...,9,30 March 1999,Don-102,To Kill a Mockingbird

Heat

,titlu,text,rating,data,utilizator,film
0,You find yourself rooting for both sides the ...,Heat (1995) is a movie that is in my DVD colle...,10,20 December 2021,kevin_robbins,Heat
1,Exceptionally well done though it's not the s...,I have very little interest in most action fil...,9,23 April 2011,planktonrules,Heat
2,Michael Mann's finest work,A brilliant character driven action thriller w...,10,17 August 2021,lareval,Heat
3,One Of The Best Crime Films Ever,I really believe this is one the great crime m...,10,15 February 2006,ccthemovieman-1,Heat
4,Brilliant,This is a brilliant film. While clocking in at...,10,9 January 2011,TheLittleSongbird,Heat

The Sting

,titlu,text,rating,data,utilizator,film
0,Working The Big Con,"The Sting, evoking a bygone era of gangsters a...",10,5 March 2007,bkoganbing,The Sting
1,Everything's Jake In Second Trip To Well,"The fix is in, the odds are set, and the boys ...",9,29 December 2004,slokes,The Sting
2,The clever plot makes multiple viewings manda...,THE STING is so full of twists and turns at ev...,9,14 May 2005,Doylenf,The Sting
3,The Moral Order Restored,Johnny Hooker and Luther Coleman are 'grifters...,9,15 March 2004,JamesHitchcock,The Sting
4,Classy bit of story telling,Small time conmen Johnny Hooker and Luther Col...,-,23 March 2003,bob the moo,The Sting

Up

,titlu,text,rating,data,utilizator,film
0,Real tear jerker opening,Carl Fredricksen (Ed Asner) as a young quiet k...,9,30 December 2013,SnoopyStyle,Up
1,Best animated movies ever made,This film is possibly one of the best animated...,-,15 February 2020,MrHeraclius,Up
2,"In my personal opinion, this is Pixar's funni...",I love Pixar and feel they have been pretty co...,10,17 May 2010,TheLittleSongbird,Up
3,"Imaginative, fun and moving - as close to per...",Carl Frederickson (Ed Asner) has lived a long ...,10,29 May 2009,DonFishies,Up
4,It's Just a House,Greetings again from the darkness. Another cra...,9,31 May 2009,ferguson-6,Up

A Separation

,titlu,text,rating,data,utilizator,film
0,Mankind Is Flawed,"In Tehran, the teacher Simin (Leila Hatami) ha...",10,13 January 2012,claudio_carvalho,A Separation
1,Do yourself a favor - make sure you see this ...,"Caught ""A Separation"" in Amsterdam last night,...",9,2 September 2011,krisrox,A Separation
2,Maybe the movie of the year,And it comes from Iran. The first thing you re...,9,10 October 2011,stensson,A Separation
3,The Swan Song of Iranian cinema?,Asghar Farhadi's new film after the ingenious ...,10,16 February 2011,Radu_A,A Separation
4,Wow! Just.. wow!,-- www.Ramascreen.com --Wow! I didn't have any...,10,28 December 2011,Ramascreen,A Separation

Metropolis

,titlu,text,rating,data,utilizator,film
0,Heart is the Mediator Between Brains and Musc...,"In the future, the society of Metropolis is di...",10,26 January 2006,claudio_carvalho,Metropolis
1,Early science fiction story that presents a p...,Who ever heard of an epic science fiction film...,10,16 February 2001,Anonymous_Maxine,Metropolis
2,So old and yet so futuristic!,Fritz Lang's groundbreaking landmark remains o...,8,25 August 2005,Coventry,Metropolis
3,Movie Milestone and Masterpiece!,Metropolis is surely one of the greatest films...,-,1 February 2000,BaronBl00d,Metropolis
4,The father of sci-fi cinema.,Silent movies are not for everyone. Neither ar...,9,24 April 1999,PIST-OFF,Metropolis

Taxi Driver

,titlu,text,rating,data,utilizator,film
0,A classy character study of a disturbed indiv...,Insomniac Vietnam veteran Travis Bickle (Rober...,7,5 April 2015,BA_Harrison,Taxi Driver
1,Disturbing Look into a Disturbed Mind,Travis Bickle (Robert DeNiro) is a disturbed e...,9,5 September 2013,SnoopyStyle,Taxi Driver
2,A wonderfully engaging and convincing slide i...,Travis Bickle is a Vietnam veteran who cannot ...,-,13 February 2006,bob the moo,Taxi Driver
3,Ladies and gentlemen: Mr. Robert De Niro!,"Taxi Driver, the classic that made Robert DeNi...",10,20 November 2003,Smells_Like_Cheese,Taxi Driver
4,Still has the power to shock...,"Not only one of Scorsese's best films, but one...",10,9 January 2011,TheLittleSongbird,Taxi Driver

L.A. Confidential

,titlu,text,rating,data,utilizator,film
0,"A ""Chinatown"" for the 1990s","""L.A. Confidential"" is brilliant. The screenp...",-,25 June 2000,tfrizzell,L.A. Confidential
1,A fascinating look at life in the big city,Give a collection of great actors a great stor...,8,19 August 2005,hall895,L.A. Confidential
2,Superb film-making,As a fan of mysteries and thrillers and who li...,10,11 June 2017,TheLittleSongbird,L.A. Confidential
3,I Wish This Film Had Been Five Hours Long,What happens when a squad of corrupt cops in t...,9,18 September 2006,gavin6942,L.A. Confidential
4,Three Phenomenal Actors Give The Performances...,"Six years ago, a director by the name of Curti...",-,1 September 2003,flipgirl38,L.A. Confidential

Die Hard

,titlu,text,rating,data,utilizator,film
0,Not only the best of the Die Hard franchise b...,Even if the non-action parts are a tad slow in...,10,15 May 2010,TheLittleSongbird,Die Hard
1,It can't be bettered,This original action classic has been hugely i...,10,25 June 2016,Leofwine_draca,Die Hard
2,The greatest bad-ass best action movie hands ...,Die Hard (1988) the first action film is by fa...,10,4 February 2018,ivo-cobra8,Die Hard
3,Was there Action Films before Die Hard?? Who ...,Of course the Action Genre existed before Die ...,10,7 February 2007,Robert_duder,Die Hard
4,Wham Bam Action Classic,Die Hard (1988) *** (out of 4)Enjoyable and te...,-,27 January 2013,Michael_Elliott,Die Hard

Snatch

,titlu,text,rating,data,utilizator,film
0,There are few films that can make me laugh li...,"`Snatch', written and directed by Guy Ritchie ...",9,24 August 2004,FilmOtaku,Snatch
1,Perfect,This movie is perfect in all its categories: c...,10,17 February 2003,LivingDog,Snatch
2,"Lock, Stock, and Many Smoking Barrels","The release of Tarantino's ""Pulp Fiction"" in 1...",8,14 January 2001,Shiva-11,Snatch
3,The pinnacle of Guy Ritchie's career,"This sleek, stylish and very effective black c...",10,23 December 2016,Leofwine_draca,Snatch
4,"I liked it, is that so wrong?",I am a 33 year old woman in a flowered dress w...,-,6 February 2002,sllovejoy,Snatch

Indiana Jones and the Last Crusade

,titlu,text,rating,data,utilizator,film
0,The third entry in the installment is one of ...,Indiana Jones and the Last Crusade (1989) is a...,10,16 October 2015,ivo-cobra8,Indiana Jones and the Last Crusade
1,Perpetually Entertaining...,"An army of fascists seek to plunder, an artefa...",9,6 June 2022,Xstal,Indiana Jones and the Last Crusade
2,The best of the Indiana Jones trilogy,"Indiana Jones, the man, the legend, the whip. ...",10,23 November 2003,Smells_Like_Cheese,Indiana Jones and the Last Crusade
3,The Last Crusade is the best of the Indy tril...,Rating: **** out of ****My opinion of Indiana ...,-,2 November 2003,Li-1,Indiana Jones and the Last Crusade
4,You call this archaeology? Sure do!,One thing you gotta say for this series: it is...,10,19 August 1999,Mister-6,Indiana Jones and the Last Crusade

Bicycle Thieves

,titlu,text,rating,data,utilizator,film
0,Quiet Desperation---Italian Style.,In post-World War II Italy poverty is a dire r...,-,2 May 2003,tfrizzell,Bicycle Thieves
1,Another one to add to my top 50- a delicate s...,Vittorio De Sica's ground/heartbreaking motion...,10,8 April 2003,Quinoa1984,Bicycle Thieves
2,No small thing.,This movie changed my life. It changed it in t...,-,11 April 2004,ItalianGerry,Bicycle Thieves
3,Powerful and dramatic,It is post-war Rome and much of the city's res...,8,1 August 2004,FilmOtaku,Bicycle Thieves
4,A Heartbreaking Masterpiece of the Italian Ne...,"In the post-war Rome, after more than two-year...",10,23 March 2010,claudio_carvalho,Bicycle Thieves

Like Stars on Earth

,titlu,text,rating,data,utilizator,film
0,"'My child always comes first in class', this ...",The film brings to light what it is truly like...,10,5 November 2013,Fella_shibby,Like Stars on Earth
1,Best Depiction of Dyslexia Ever in a Fictiona...,As I just became aware of this film a few week...,10,9 October 2011,drpakmanrains,Like Stars on Earth
2,Among the best films I've ever seen...and the...,I love Indian films and have seen more than mo...,10,20 August 2021,planktonrules,Like Stars on Earth
3,Every Child is Special,I'm not always a fan of the Bollywood style of...,8,27 June 2017,ThomasDrufke,Like Stars on Earth
4,Two Celestial Bodies Make Three...,"The performance of Darsheel Safary, as convinc...",8,28 October 2020,Xstal,Like Stars on Earth

1917

,titlu,text,rating,data,utilizator,film
0,"""He travels the fastest who travels alone""","There are some great WW1 films out there, the ...",10,13 April 2021,TheLittleSongbird,1917
1,Reasonably accurate in showing the hell that ...,I am not particularly a huge fan of war films....,9,10 April 2020,planktonrules,1917
2,Another Day In One Long Take,The command has realized that the Germans have...,8,10 January 2020,boblipton,1917
3,An achievement,It's a stunning watch from start to finish. Th...,9,12 December 2019,aivilovee,1917
4,We're living in such wonderful times...,"1917 is a poem.\nIs the most deep, impressive ...",10,7 January 2020,diegosays,1917

Downfall

,titlu,text,rating,data,utilizator,film
0,"The Most Impressive, Depressive and Realistic...","""Der Untergang"" is certainly the most impressi...",10,19 January 2006,claudio_carvalho,Downfall
1,"""You have to feel that Hitler was a human bei...",The first internationally released German prod...,9,24 August 2005,Galina_movie_fan,Downfall
2,A magnificent piece of cinema. Spectacular in...,Truly great movies are few and far between the...,8,21 April 2005,The_Void,Downfall
3,The last days at the bunker,This magnificent film goes where no one else d...,10,19 March 2005,jotix100,Downfall
4,A mesmerizing experience and one that will ho...,"All I can say about ""Der Untergang"" is: WOW! T...",10,18 January 2005,Coventry,Downfall

Dangal

,titlu,text,rating,data,utilizator,film
0,"""You have to fight in a way that people remem...",Most of the reviewers for this film here on IM...,7,4 March 2018,classicsoncall,Dangal
1,Wrestle With Your Emotions...,Let this incredibly sincere biopic wrestle wit...,9,1 November 2020,Xstal,Dangal
2,Awesome film n wonderful performance by Aamir...,I saw this with my family in a theatre. Awesom...,10,23 December 2016,Fella_shibby,Dangal
3,Aamir is back with a stellar performance of a...,DANGAL is a masterpiece. A terrific film that ...,9,21 December 2016,gskrocks,Dangal
4,Movie of the year. Its much better than sulta...,"""Direction was superb and Aamir's performance ...",9,22 December 2016,ridinbal,Dangal

For a Few Dollars More

,titlu,text,rating,data,utilizator,film
0,Lee Van Cleef outstanding,Col. Douglas Mortimer (Lee Van Cleef) and Monc...,9,21 September 2013,SnoopyStyle,For a Few Dollars More
1,One of my favorite westerns- a fitting middle...,As the second of the three films legendary fil...,10,23 December 2003,Quinoa1984,For a Few Dollars More
2,An Ushering Into A New Era,Completely defying the tried & tested Hollywoo...,-,28 March 2014,CinemaClown,For a Few Dollars More
3,"Not as good as The Good, The Bad and The Ugly...",Just for the record I happen to love all three...,10,30 August 2012,TheLittleSongbird,For a Few Dollars More
4,The best spaghetti western ever?,Leone's 'A Fistful Of Dollars' is a bona fide ...,-,4 July 2003,Infofreak,For a Few Dollars More

Batman Begins

,titlu,text,rating,data,utilizator,film
0,Why do we fall? So we can learn to pick ourse...,It sickened me in the past to see the Batman m...,10,15 August 2005,pyrocitor,Batman Begins
1,"A darker, stormier knight.",Christopher Nolan (and cast) have pulled off w...,10,5 June 2005,tenten76,Batman Begins
2,Mature Batman Origin Story With Enough Comic ...,Batman Begins was a massive breath of fresh ai...,8,10 September 2015,jaredpahl,Batman Begins
3,A reboot that works,British director Christopher Nolan is better k...,9,16 October 2015,Leofwine_draca,Batman Begins
4,One Super-Hero Film With Tremendous Depth!,"From PASTO, COLOMBIA-Via: L. A. CA; CALI, COLO...",10,28 July 2016,KissEnglishPasto,Batman Begins

The Kid

,titlu,text,rating,data,utilizator,film
0,A Must-See Silent Comedy,While perhaps not as celebrated now as some of...,-,4 March 2002,Snow Leopard,The Kid
1,Emphatically Outstanding...,It takes your breath away over 100 years later...,9,20 September 2020,Xstal,The Kid
2,One Of The Most Memorable Silent Films Ever,"Wow, is this a memorable film! It is one of th...",9,24 November 2005,ccthemovieman-1,The Kid
3,Smiling and Tearing,"""The Kid"" is a powerfully emotional and wonder...",9,29 August 2005,Cineanalyst,The Kid
4,Chaplin understands how close slapstick is to...,I've always thought there's a great beauty and...,-,4 March 2007,J. Spurlin,The Kid

Some Like It Hot

,titlu,text,rating,data,utilizator,film
0,Two musicians dressed as women join an all-gi...,Legendary comedy masterpiece from filmmaker Bi...,8,30 October 2012,ma-cortes,Some Like It Hot
1,One of the Best Comedies of the Cinema History,"In 1929, in Chicago, the musicians and friends...",10,1 October 2010,claudio_carvalho,Some Like It Hot
2,What's Not To Like?,Some people still say this is the greatest com...,10,15 November 2005,ccthemovieman-1,Some Like It Hot
3,A Legendary Comedy,"With Billy Wilder's steady direction, the grea...",9,5 August 2008,EijnarAmadeus,Some Like It Hot
4,"In this brilliant comedy, Marilyn was breatht...",Any camera loved Marilyn the best In all her ...,8,27 June 2007,Nazi_Fighter_David,Some Like It Hot

The Father

,titlu,text,rating,data,utilizator,film
0,A look at dementia from the opposite angle.,This movie was shot in May 2019 just a few mon...,-,2 August 2021,TxMike,The Father
1,"""I don't know what's happening anymore.""",This movie brings you inside the mind of someo...,9,13 April 2021,classicsoncall,The Father
2,So close to perfect and so personal,This is one of the hardest movie reviews I've ...,10,12 April 2021,waltermwilliams,The Father
3,Excellent but deeply upsetting,I cannot say what I want to say about this fil...,9,1 July 2021,neil-476,The Father
4,Hopkins has never been better.,"I haven't seen the play on which ""The Father"" ...",10,4 April 2021,MOscarbradley,The Father

All About Eve

,titlu,text,rating,data,utilizator,film
0,"A Magnificent Timeless Tale of Ambition, Mani...",The ambitious Eve Harrington (Anne Baxter) get...,10,17 October 2005,claudio_carvalho,All About Eve
1,"Wow, an 11 if possible!","All About Eve is my idea of a perfect film,(an...",10,4 June 2009,TheLittleSongbird,All About Eve
2,Just Brilliant!,"Brilliantly acted and cleverly characterized, ...",10,30 August 2017,JohnHowardReid,All About Eve
3,Superb Acting And Dialogue,"What a movie! It's the cinematic ideal, the st...",9,20 February 2010,Lechuguilla,All About Eve
4,All About Great Writing and Great Acting...,"In show business, there is probably an Eve Har...",10,20 March 1999,Don-102,All About Eve

The Wolf of Wall Street

,titlu,text,rating,data,utilizator,film
0,High energy and wonderfully excessive as it d...,This film arrived in the UK with awards and Os...,-,17 January 2014,bob the moo,The Wolf of Wall Street
1,SELL ME THIS PEN,Golden Globe winner Leonardo DiCaprio stars in...,9,4 October 2018,nogodnomasters,The Wolf of Wall Street
2,"Awesome movie, watched it multiple times","This film is every definition of the word ""imp...",-,23 February 2020,MrHeraclius,The Wolf of Wall Street
3,Oscar worthy,The movie Leonardo DiCaprio should have gotten...,10,29 December 2020,karolin-99263,The Wolf of Wall Street
4,It really is a comedy,There is a reason this is called Wolf of Wall ...,9,18 June 2014,kosmasp,The Wolf of Wall Street

Green Book

,titlu,text,rating,data,utilizator,film
0,I Was Captivated,I saw Don Shirley perform in college in 1966. ...,10,19 January 2019,Hitchcoc,Green Book
1,"A captivating watch, with sensational acting.",Not often these days so I give ten stars to a ...,10,23 January 2021,Sleepin_Dragon,Green Book
2,Green Book,This film proves why movies can be so powerful...,-,14 February 2020,MrHeraclius,Green Book
3,Ranks #5 on my IMDb Top 25 Best Buddy Films L...,Ignore the sour grapes criticism from Spike Le...,9,26 June 2020,Instant_Palmer,Green Book
4,"""Green Book"" is Gold",We loved Green Book along with the sold-out cr...,10,25 November 2018,taylor_king-890-815491,Green Book

Judgment at Nuremberg

,titlu,text,rating,data,utilizator,film
0,"Fantastic acting, script, and direction in a ...",Outstanding film. Star-studded with several fa...,9,11 September 2017,gbill-74877,Judgment at Nuremberg
1,Cinematic Theater Of A Remarkable Kind,"Beyond its compelling subject matter ""Judgemen...",9,1 February 2007,littlemartinarocena,Judgment at Nuremberg
2,"""My counsel says we were not aware of the ext...",This quote is one of the most shocking and yet...,10,28 January 2009,alexkolokotronis,Judgment at Nuremberg
3,A Film Of Enduring Value,They say that time heals all heartache. In the...,10,8 May 2005,Lechuguilla,Judgment at Nuremberg
4,Hollywood's best in an important film,It is so easy to dismiss this as a story of ot...,8,11 April 2008,lastliberal,Judgment at Nuremberg

Casino

,titlu,text,rating,data,utilizator,film
0,"""Now it looks like Disney Land""",This is one of the best films of the 90's hand...,10,30 October 2003,Smells_Like_Cheese,Casino
1,"I enjoyed this more than ""Goodfellas"".",I generally avoid violent films...which is why...,9,29 December 2021,planktonrules,Casino
2,I Know I Am In The Minority When I Say This W...,I saw Goodfellas first and more times than Cas...,10,22 July 2015,Movie-ManDan,Casino
3,The most uncompromising studio picture of the...,"A complex, multilayered, beautifully directed ...",10,20 February 2000,contronatura,Casino
4,"Robert De Niro, an icon of the contemporary H...","Based on a true story, Martin Scorsese ""Casino...",8,22 May 2007,Nazi_Fighter_David,Casino

Ran

,titlu,text,rating,data,utilizator,film
0,My third favorite Kurosawa film- deliberately...,"I would agree with Ebert's review on a point, ...",10,16 August 2004,Quinoa1984,Ran
1,The Best Film based on one of Shakespeare Bes...,"Akira Kurosawa's 1985, Ran, is based one of Sh...",10,19 August 2010,Loving_Silence,Ran
2,A film requiring patience with huge rewards f...,The 'Kurosawa' adaptation of King Lear in his ...,9,26 July 2001,smakawhat,Ran
3,Be prepared to be awe-struck!,With RAN (1985) Akira Kurosawa seems to be set...,-,20 November 2001,boris-26,Ran
4,Jester and Warlord,"'Ran' is the Japanese word for chaos, riot, di...",10,3 November 2005,zolaaar,Ran

Pan's Labyrinth

,titlu,text,rating,data,utilizator,film
0,Stop the Abuse,An incredibly creative piece of cinema. It inc...,10,8 January 2017,Hitchcoc,Pan's Labyrinth
1,"A fey, beautiful and dark masterpiece",Set during Franco's mopping up exercise after ...,9,23 November 2006,j30bell,Pan's Labyrinth
2,Just magical,I saw the film at FrightFest in London a coupl...,10,27 August 2006,mizhelenuk,Pan's Labyrinth
3,A masterpiece,1944. Franco's authoritarian fascist regime is...,10,22 November 2006,Chris_Docker,Pan's Labyrinth
4,In Depth Analysis of Interpretations,Sixth viewing: My appreciation only grows. Int...,10,27 May 2018,Wesley-Wang,Pan's Labyrinth

The Truman Show

,titlu,text,rating,data,utilizator,film
0,An unassuming film that is thought provoking ...,Truman Burbank is an ordinary guy in an ordina...,-,29 October 2004,bob the moo,The Truman Show
1,Life is Starting to Imitate Satire,"Life is starting to imitate satire. ""The Truma...",10,31 August 2005,JamesHitchcock,The Truman Show
2,Prophetic,The Truman Show is a film I never got around t...,9,19 July 2019,skepticskeptical,The Truman Show
3,A good film for those who think they hate Jim...,I have never liked Jim Carey's humor. I have f...,9,16 February 2014,planktonrules,The Truman Show
4,Genius,I asked a friend to describe The Truman Show. ...,10,12 June 1999,Altaira,The Truman Show

There Will Be Blood

,titlu,text,rating,data,utilizator,film
0,The Truth Hurts,People did not like this movie for a simple re...,10,15 March 2008,alexkolokotronis,There Will Be Blood
1,"Excellent, gutsy filmmaking",This is a compelling family drama charting one...,9,13 March 2012,Leofwine_draca,There Will Be Blood
2,"Phenomenal acting, not personally gripped by ...",It has been a while since I watched a film whe...,7,31 January 2022,breezey-120-833995,There Will Be Blood
3,There Will be Praise,The world of cinema has seen and marveled a pl...,10,29 September 2009,murtaza_mma,There Will Be Blood
4,Daniel Day-Lewis does a great job playing a m...,"I had heard about what a great movie ""There Wi...",9,17 April 2008,lee_eisenberg,There Will Be Blood

Unforgiven

,titlu,text,rating,data,utilizator,film
0,That's right. I'm just a fella now. I ain't n...,William Munny (Clint Eastwood taking the lead ...,10,15 March 2011,hitchcockthelegend,Unforgiven
1,This aint just a great western. Its an incred...,Saw this in the late nineties on a vhs n revis...,10,9 March 2018,Fella_shibby,Unforgiven
2,Masterpiece,"Ford, Hawks, Leone, Peckinpah, all of them big...",10,19 February 2007,jluis1984,Unforgiven
3,Unforgettable,"""Unforgiven"" may well be Clint Eastwood's grea...",9,6 June 2000,cathyyoung1,Unforgiven
4,A classic feel of Western with the added bril...,"I have heard quite a bit for ""Unforgiven"", als...",8,29 November 2005,Smells_Like_Cheese,Unforgiven

The Sixth Sense

,titlu,text,rating,data,utilizator,film
0,Still Very Good Even When You Know The Ending,"This was hyped big-time when it came out and, ...",9,8 November 2006,ccthemovieman-1,The Sixth Sense
1,"Even if someone spoiled the ending for you, i...","There are over 2000 IMDb reviews for ""The Sixt...",8,1 September 2014,rooprect,The Sixth Sense
2,An appropriate spoiler-free review,"The surprise ending to ""The Sixth Sense"" has g...",10,31 December 2005,kylopod,The Sixth Sense
3,Brilliantly crafted and well worth seeing.......,I am making 100% sure I don't in any way revea...,10,11 July 2011,planktonrules,The Sixth Sense
4,One of the best films of 1999!,I am embarrassed to admit that the only reason...,9,3 February 2000,Xophianic,The Sixth Sense

Shutter Island

,titlu,text,rating,data,utilizator,film
0,One of the most memorable plot twists of this...,I originally saw this film when it came out bu...,9,22 July 2019,jackgdemoss,Shutter Island
1,"""Men like you are my specialty, you know?""",There are a number of films I've seen more tha...,10,30 August 2010,classicsoncall,Shutter Island
2,The movie is perfect psycho drama,"Shutter Island is the story of Teddy Daniels, ...",10,24 September 2017,ruhsa,Shutter Island
3,love this movie highly recommend.,"Visually beautiful, wonderfully acted, and rel...",-,23 February 2020,MrHeraclius,Shutter Island
4,Shutter Island is at the top of its genre,Martin Scorsese has done it again. He pays att...,9,22 May 2010,napierslogs,Shutter Island

A Beautiful Mind

,titlu,text,rating,data,utilizator,film
0,"Powerful, quiet, effortless Crowe",A Beautiful Mind\nDirector Ron Howard has expe...,9,23 January 2002,dfranzen70,A Beautiful Mind
1,A Beautiful Movie,I think its a good idea to know as little as p...,10,17 December 2001,Boyo-2,A Beautiful Mind
2,Crowe Does It Again!,"The more I watch Russell Crowe, the more I am ...",9,1 February 2006,ccthemovieman-1,A Beautiful Mind
3,A Mind is a Terrible Thing to Lose.,The story of John Forbes Nash doesn't seem lik...,9,25 August 2005,nycritic,A Beautiful Mind
4,A Beautiful Film,It's not that common people knew John Forbes N...,10,18 January 2003,shanfloyd,A Beautiful Mind

Jurassic Park

,titlu,text,rating,data,utilizator,film
0,A rare breed of film seldom seen anymore: a t...,'Jurassic Park (1993)' is a landmark achieveme...,10,10 June 2018,Pjtaylor-96-138044,Jurassic Park
1,A time when I thought dinosaurs were real,My first epic movie to see on the big screen w...,9,18 November 2003,Smells_Like_Cheese,Jurassic Park
2,"With a bazillion other reviews, I'll keep thi...",By now there are nearly a thousand (not really...,9,11 May 2013,planktonrules,Jurassic Park
3,"A Groundbreaking, Heart Stomping, Dino Sized ...","In the year 1993, Hollywood saw something unli...",10,5 September 2005,FrankBooth_DeLarge,Jurassic Park
4,The Movie to define a Generation.,"If you were born in the 90s or before, you had...",10,11 June 2019,josiahliljequist,Jurassic Park

Yojimbo

,titlu,text,rating,data,utilizator,film
0,"""You don't mind if I kill all of you?"" ""What?...","Akira Kurosawa's Yojimbo is a not too long, no...",10,24 December 2003,Quinoa1984,Yojimbo
1,Kurosawa.,Only a handful of directors know atmosphere th...,10,26 September 1999,Peach-2,Yojimbo
2,The epitome of cinema cool.,If you ever watched Pulp Fiction and thought: ...,9,6 February 2004,Ben_Cheshire,Yojimbo
3,For sheer entertainment value 'Yojimbo' is ha...,I'm not going to waste time debating which was...,-,15 May 2004,Infofreak,Yojimbo
4,First class samurai action tale with philosop...,Classic samurai action pic; often imitated but...,10,9 November 2002,funkyfry,Yojimbo

The Treasure of the Sierra Madre

,titlu,text,rating,data,utilizator,film
0,"Just a great movie all around, but a very dar...",This film is a sharp-edged study of the effect...,9,10 August 2016,AlsExGal,The Treasure of the Sierra Madre
1,God Has a Sense of Humor,I think the great lesson of The Treasure of th...,10,8 September 2005,bkoganbing,The Treasure of the Sierra Madre
2,One of Warner Brother's triumphs of the forties,Having had his day as an idolized star and rom...,8,6 April 2005,Nazi_Fighter_David,The Treasure of the Sierra Madre
3,"All that glitters is ""gone with the wind....""",John Huston's genius as a director is undeniab...,10,27 June 2004,jotix100,The Treasure of the Sierra Madre
4,"""If you want somebody NOT to find it, . . . P...","In the 1920's, labor was hard to find. If you ...",8,7 September 2007,thinker1691,The Treasure of the Sierra Madre

Monty Python and the Holy Grail

,titlu,text,rating,data,utilizator,film
0,WHAT is the capital of Assyria? I don't know ...,"I do know, however, that Monty Python and the ...",10,28 March 2006,MaxBorg89,Monty Python and the Holy Grail
1,the ultimate nonsense comedy,"Well, this is unquestionably one of the funnie...",-,27 August 2003,vladymirror,Monty Python and the Holy Grail
2,They could grab it by the husk.....,King Arthur and his Knights of the Round Table...,10,16 February 2004,Manthorpe,Monty Python and the Holy Grail
3,Monty Python at their best,"In the Realm of King Arthur, the Monty Python ...",9,22 January 2005,mjw2305,Monty Python and the Holy Grail
4,The King of Comedies!,The first time I saw this was on CBS at 11:30 ...,10,18 May 2003,lambiepie-2,Monty Python and the Holy Grail

The Great Escape

,titlu,text,rating,data,utilizator,film
0,"""We Intend To Watch This Basket Very Closely.""",The Great Escape tells the amazing story of a ...,10,17 September 2006,bkoganbing,The Great Escape
1,"Not just great, simply magnificent more like!","""Wait a minute, you aren't seriously suggestin...",10,4 March 2008,hitchcockthelegend,The Great Escape
2,"If you're going to critique the history, then...",I find it difficult to believe that some revie...,-,31 January 2003,FABabe,The Great Escape
3,The Great Movie,"The Germans, ""with madness in their method"" ha...",10,13 January 2022,boblipton,The Great Escape
4,"A vast, multi-star war epic with great score ...",'The Great Escape' had the advantage of a fine...,9,18 July 2001,Nazi_Fighter_David,The Great Escape

No Country for Old Men

,titlu,text,rating,data,utilizator,film
0,Marvellous Ending,The message of this film is that there is no s...,10,1 March 2018,chaswe-28402,No Country for Old Men
1,How Much Violence Can You Handle?,This film grabs you and doesn't let go. There ...,9,12 January 2010,Hitchcoc,No Country for Old Men
2,No Country For Old Men - Explanation - Spoilers,The meaning of Sheriff Bell's dream was that h...,8,9 September 2020,FLASHP01NT,No Country for Old Men
3,A Look into an Abyss,I expect a film like 'No Country for Old Men' ...,10,20 June 2013,Sonic_Ocean,No Country for Old Men
4,Some Interesting Characters,"While on a hunting trip, a sportsman (Josh Bro...",9,13 July 2008,Lechuguilla,No Country for Old Men

Kill Bill: Vol. 1

,titlu,text,rating,data,utilizator,film
0,Cinema has rarely been this exciting!,"Having seen Tarantino's 3 previous films, goin...",10,28 October 2015,gogoschka-1,Kill Bill: Vol. 1
1,Kill Bill Is One Hell Of A Thrill,Pros:\n1. The bright colour palette does a won...,9,10 September 2020,dommercaldi,Kill Bill: Vol. 1
2,"I love this movie, I don't know why, but I ju...","This is movie is unusual, but it works for me....",9,26 April 2019,SafReviews,Kill Bill: Vol. 1
3,Amazing wonderful fantastic,The music first is breathtaking. The action is...,10,17 November 2020,sjanders-86430,Kill Bill: Vol. 1
4,Tarantino's Blue Period is OVER!,"Just saw Kill Bill: Vol. 1 and was surprised, ...",9,10 October 2003,emperorpasta,Kill Bill: Vol. 1

Rashomon

,titlu,text,rating,data,utilizator,film
0,A brilliant masterpiece from a masterful dire...,"""Rashomon"" was Akira Kurosawa's first national...",10,8 April 2006,MovieAddict2016,Rashomon
1,Most of the time we can't even be honest with...,To have a film that holds the coveted title of...,8,5 January 2006,film-critic,Rashomon
2,"Kurosawa's first milestone, one of the top fo...","Akira Kurosawa was one of those directors, the...",10,2 August 2003,Quinoa1984,Rashomon
3,To what extent does subjectivity affect perce...,"""Rashomon"" tells a very simple tale in a very ...",-,9 September 2007,ametaphysicalshark,Rashomon
4,What did we just see?,'People forget the unpleasant things. They on...,-,10 February 2002,rogierr,Rashomon

Spider-Man: No Way Home

,titlu,text,rating,data,utilizator,film
0,Loved every second,This Spiderman is really fantastic. It captiva...,-,15 December 2021,Gordon-11,Spider-Man: No Way Home
1,"Great concept, mediocre execution",A tough one to rate. It certainly has entertai...,6,31 March 2022,gbill-74877,Spider-Man: No Way Home
2,Phenomenal conclusion,Spider-Man: No Way Home is a phenomenal conclu...,10,15 December 2021,masonsaul,Spider-Man: No Way Home
3,I consider myself to be a big fan of Marvel a...,Awful movie. The plot sucked and had awful pac...,5,19 March 2022,Neptune165,Spider-Man: No Way Home
4,Nonsense And Nostalgia,Review By Kamal KI don't think this film was w...,4,21 December 2021,IPyaarCinema,Spider-Man: No Way Home

The Thing

,titlu,text,rating,data,utilizator,film
0,A classic that still holds up to this very day,"""I know I'm human. And if you were all these t...",10,26 July 2004,MovieAddict2016,The Thing
1,"""The Thing"" is John Carpenter's masterpiece a...","A classic film. John Carpenter's ""The Thing"" i...",10,31 October 2015,ivo-cobra8,The Thing
2,Flips the scenario round from the original to...,John Carpenter shows how much he loves the 195...,10,4 March 2008,hitchcockthelegend,The Thing
3,The tagline is no mere jest,"""The ultimate in alien terror,"" it says. It's ...",10,19 December 2020,I_Ailurophile,The Thing
4,"Right up there with ""Halloween""--one of Carpe...","Remake of the classic 1951 ""The Thing From Ano...",10,6 December 2003,preppy-3,The Thing

Finding Nemo

,titlu,text,rating,data,utilizator,film
0,"Yes, it's THAT good !!",I'll be totally honest and confirm to you that...,8,10 December 2003,Coventry,Finding Nemo
1,Pixar's best feature to date,I have enjoyed most of the computer-animated f...,9,15 October 2005,kylopod,Finding Nemo
2,amazing visuals,Has there ever been a better-looking feature-l...,-,28 November 2003,Buddy-51,Finding Nemo
3,Another Disney/Pixar Classic,Those guys and girls at Disney/Pixar have done...,8,22 January 2005,mjw2305,Finding Nemo
4,Swimming with Sharks is a Whale of a Time,"Marlin, a nervous and neurotic clownfish is he...",10,20 March 2006,PizzicatoFishCrouch,Finding Nemo

The Elephant Man

,titlu,text,rating,data,utilizator,film
0,Almost Too Heart-Wrenching To Watch,"Man, this is a powerful and great movie. We ar...",9,1 November 2005,ccthemovieman-1,The Elephant Man
1,A Beautiful Mind,"THE ELEPHANT MAN (1980) **** John Hurt, Anthon...",10,12 March 2003,george.schmidt,The Elephant Man
2,David Lynch's most accessible work. A truly r...,I first watched 'The Elephant Man' over twenty...,-,3 February 2004,Infofreak,The Elephant Man
3,"An elephant never forgets, and ""The Elephant ...",Anthony Hopkins is so associated with Hannibal...,10,19 December 2005,lee_eisenberg,The Elephant Man
4,The most moving masterpiece of all time!,You have got to love the Elephant Man. There i...,10,9 February 2009,TheLittleSongbird,The Elephant Man

Chinatown

,titlu,text,rating,data,utilizator,film
0,I hated this movie,The first time I saw it. After one of my buddi...,9,4 November 2019,ArtVandelayImporterExporter,Chinatown
1,"A very classy, consistently engaging and dark...",Jake Gittes is a former cop turned private det...,-,3 January 2005,bob the moo,Chinatown
2,Capturing the True Spirit of Film-noir,The seventies were the last years of great (Am...,10,10 September 2004,nycritic,Chinatown
3,Marvelous,"There is a word, impossible to spell, that des...",10,30 January 2002,rmax304823,Chinatown
4,Great 'modern' film noir,Set in late '30s Los Angeles this 1974 film op...,10,15 November 2018,Tweekums,Chinatown

Raging Bull

,titlu,text,rating,data,utilizator,film
0,Essential masterpiece; powerful De Niro; simp...,"""Raging Bull"" isn't the average, stereotypical...",10,5 April 2004,MovieAddict2016,Raging Bull
1,Impressive From A Filmmaking Standpoint But L...,Bringing the life story of one of the roughest...,-,29 September 2018,CinemaClown,Raging Bull
2,Scorsese's Best? De Niro's Best? The 1980s' B...,"""Raging Bull"" is a cinematic masterpiece which...",-,28 September 2000,tfrizzell,Raging Bull
3,Scorcese robbed,"Well, I don't think I've ever been more disapp...",5,25 June 2006,blanche-2,Raging Bull
4,Bovine Pugilist & Paranoid Misogynist...,There's very little to like about the characte...,8,30 September 2020,Xstal,Raging Bull

V for Vendetta

,titlu,text,rating,data,utilizator,film
0,"""People should not be afraid of their governm...","Placed in futuristic Britain, this movie tells...",8,3 March 2018,Bored_Dragon,V for Vendetta
1,My Personal Favourite Movie of All Time,It's been quite a few years since I first saw ...,10,31 October 2016,seige-hound,V for Vendetta
2,Terrifying and inspirational,This is a very unique film. Watching it again ...,9,17 November 2020,benxrichardson,V for Vendetta
3,More relevant than ever,"Here we are, 2021, almost 2022Do I even need t...",10,14 November 2021,beschuitfluiter,V for Vendetta
4,A Bloody Masterpiece!,I am speechless. I just came back from the the...,10,19 March 2006,atzimo,V for Vendetta

Gone with the Wind

,titlu,text,rating,data,utilizator,film
0,Georgia on my mind,This film shows the best of the American cinem...,10,22 February 2005,jotix100,Gone with the Wind
1,Scarlett's So High Spirited And Vivacious,"Before I ever saw Gone With the Wind, I was we...",10,21 October 2006,bkoganbing,Gone with the Wind
2,About as good as it gets in 1930s Hollywood,I've done so many reviews on IMDb and despite ...,10,5 August 2006,planktonrules,Gone with the Wind
3,The tragedy of Scarlet the wise 2020 review,"At first you would think, the main theme of th...",10,12 June 2020,Turanic,Gone with the Wind
4,A Tempestuous Hurricane of a Tornado...,When a film is consistently recognised through...,9,29 September 2020,Xstal,Gone with the Wind

Lock, Stock and Two Smoking Barrels

,titlu,text,rating,data,utilizator,film
0,Pure Bloody Genius,Guy Ritchie has a skill: the skill to take mul...,10,21 February 2006,gavin6942,"Lock, Stock and Two Smoking Barrels"
1,"The essence of late 90's cinema -- hip, highl...","Guy Ritchie's hip, highly stylized 'Lock, Stoc...",-,19 February 2003,doktor d,"Lock, Stock and Two Smoking Barrels"
2,Have a butchers...,I was a total and complete sucker for this fil...,10,1 March 2002,Quag7,"Lock, Stock and Two Smoking Barrels"
3,Guy Ritchie's Hilarious Feature Debut,This is one seriously funny movie. I've probab...,8,23 December 2007,brando647,"Lock, Stock and Two Smoking Barrels"
4,"As T.C. said, this movie rocks!",You all may know the story at how Tom Cruise s...,9,14 January 2000,SKG-2,"Lock, Stock and Two Smoking Barrels"

Inside Out

,titlu,text,rating,data,utilizator,film
0,Classic for the new generation? Yes!,I just knew this was gonna be amazing. Such a ...,9,26 September 2021,pickle-92642,Inside Out
1,Not for young children,I confess that I had to watch this twice befor...,-,1 January 2021,Phil_Chester,Inside Out
2,Mandatory watch for children and parents alike.,I did exactly what I was supposed to when watc...,10,23 November 2017,Animany94,Inside Out
3,Pixar's best film since Toy Story 3 and one o...,Most of Pixar's films are wonderful (short fil...,10,24 July 2015,TheLittleSongbird,Inside Out
4,Best Pixar Since Toy Story,"After some ho-hum years and too many sequels, ...",10,26 June 2015,matthewssilverhammer,Inside Out

Dial M for Murder

,titlu,text,rating,data,utilizator,film
0,M for masterful,A treat for the eyes and exercise for the brai...,7,4 September 2010,Lejink,Dial M for Murder
1,The stage-originated dialogue sings with inte...,There is a lot to admire about Alfred Hitchcoc...,9,26 November 2012,TheUnknown837-1,Dial M for Murder
2,The perfect film for the perfect murder...,After earning an Academy award nomination for ...,9,21 February 2007,jluis1984,Dial M for Murder
3,Tense and exciting.,"Tony Wendice (Ray Milland), an ex-tennis playe...",9,15 October 2006,PizzicatoFishCrouch,Dial M for Murder
4,Excellent,What gets me about this film every time I see ...,8,21 January 2013,Spondonman,Dial M for Murder

The Secret in Their Eyes

,titlu,text,rating,data,utilizator,film
0,A Story of Passion and Commitment,I can't add a lot to what has been written. Th...,10,27 February 2016,Hitchcoc,The Secret in Their Eyes
1,Speaking Eyes,"""El Secreto de sus Ojos"" hit me with unspeakab...",8,19 August 2009,billion_mucks,The Secret in Their Eyes
2,How to Live an Empty Life?,The retired justice officer Benjamín Espósito ...,9,18 September 2010,claudio_carvalho,The Secret in Their Eyes
3,"""How do you live a life full of nothing?""",This is only the second Argentinian movie I've...,10,21 November 2017,classicsoncall,The Secret in Their Eyes
4,you really don't need another review,Not often I come to an IMDb review page and th...,10,16 February 2016,A_Different_Drummer,The Secret in Their Eyes

Howl's Moving Castle

,titlu,text,rating,data,utilizator,film
0,A wild and surreal trip into the mind of a ma...,I think this is possibly Miyazaki's most intri...,10,20 March 2005,surenm,Howl's Moving Castle
1,This is art,Howl's Moving Castle is as marvelous and magic...,10,6 June 2005,soanim8ed,Howl's Moving Castle
2,Try to decode the story ...,Probably many people find the story confusing....,10,5 February 2006,kengoogloo,Howl's Moving Castle
3,"Ghibli's messiest, most nonsensical movie is ...","This is a very good movie, but I have a lot of...",6,27 July 2020,mahmus,Howl's Moving Castle
4,Confusing as Hell,I tried liking this movie. I don't get what al...,6,4 September 2021,robertrutledge,Howl's Moving Castle

Three Billboards Outside Ebbing, Missouri

,titlu,text,rating,data,utilizator,film
0,Anger begets more anger,Frances McDormand is a grieving mother who put...,8,7 December 2017,blanche-2,"Three Billboards Outside Ebbing, Missouri"
1,A thought-provoking and darkly comedic drama ...,"""Three Billboards outside Ebbing, Missouri"" ma...",9,4 December 2017,tyson-hunsaker,"Three Billboards Outside Ebbing, Missouri"
2,"Anger, what it begets, and what to do about it","When you think about great cinema, you often i...",9,17 February 2018,Semisonic,"Three Billboards Outside Ebbing, Missouri"
3,"Extremely funny film about grief, anger, reve...",It seemed that the pregnant police detective M...,9,16 October 2017,rubenm,"Three Billboards Outside Ebbing, Missouri"
4,Beware the p(l)ot holes near the billboards,"I will say that I enjoyed this film, mostly du...",7,25 November 2017,chicagopoetry,"Three Billboards Outside Ebbing, Missouri"

The Bridge on the River Kwai

,titlu,text,rating,data,utilizator,film
0,Still Stirring Wartime Adventure and Compelli...,After years of more intimate British films and...,10,1 June 2006,EUyeshima,The Bridge on the River Kwai
1,Nothing less than a masterpiece...,About as Oscar-worthy as any film made in the ...,-,5 April 2003,Doylenf,The Bridge on the River Kwai
2,The Definitive Guinness Performance,"Within the Conflict that was World War II, the...",10,9 June 2001,jhclues,The Bridge on the River Kwai
3,They don't make movies like this anymore.,I recently saw The Bridge on the River Kwai at...,10,19 February 1999,bat-5,The Bridge on the River Kwai
4,"Unlike The Bridge, This Movie Holds Up","SPOILER: This film is long (161 minutes), is a...",10,25 April 2006,ccthemovieman-1,The Bridge on the River Kwai

Trainspotting

,titlu,text,rating,data,utilizator,film
0,Now I See Why,I'm an old guy. I'm also a movie fan with an o...,9,16 November 2019,Hitchcoc,Trainspotting
1,"Hilarious, imaginative and very anti-drugs",Renton is a heroin addict. He is one of a gro...,-,20 January 2004,bob the moo,Trainspotting
2,Choose life,"Trainspotting is a magnetic, exhilarating, rep...",8,19 December 2016,Prismark10,Trainspotting
3,A triumphant masterpiece,"Danny Boyle's ""Trainspotting"" is a film in whi...",-,12 March 2008,ametaphysicalshark,Trainspotting
4,One Of THE Defining Movies Of The 90s And A M...,I remember what a raw shock of creative energy...,10,4 June 2018,gogoschka-1,Trainspotting

Prisoners

,titlu,text,rating,data,utilizator,film
0,Excellent but not for all audiences,"A few words of warning about ""Prisoners"" befor...",10,7 September 2021,planktonrules,Prisoners
1,More than just one meaning,"If you think of someone being a prisoner, you ...",10,2 June 2014,kosmasp,Prisoners
2,Hard to Watch but Really Well Done,Two very good actors ply their trade very well...,9,24 April 2017,Hitchcoc,Prisoners
3,Wonderful Mystery That Keeps You Guessing Til...,Prisoners (2013) **** (out of 4) Incredibly we...,-,21 November 2013,Michael_Elliott,Prisoners
4,"""Finish all the mazes and you can go home.""",I didn't realize until I came to some of the r...,9,28 November 2017,classicsoncall,Prisoners

Warrior

,titlu,text,rating,data,utilizator,film
0,"""The devil you know is better than the devil ...",There aren't many fight movies I'd rate as hig...,10,4 November 2017,classicsoncall,Warrior
1,Joel and Tom are magical.,"At first, I thought, ""man, should have shown a...",9,27 August 2020,ansharora-12638,Warrior
2,Oh my god,I'm hard to break when it comes to emotions. I...,9,11 January 2020,Vuraxis,Warrior
3,A powerful masterpiece about desperate men,Tom Hardy and Joel Edgerton feud as estranged ...,10,27 July 2021,severindringel,Warrior
4,breakout performances,Tommy (Tom Hardy) becomes an internet sensatio...,8,18 August 2013,SnoopyStyle,Warrior

Fargo

,titlu,text,rating,data,utilizator,film
0,Don't Forgo Fargo,"Boy, is this a good movie. In its bare bones i...",10,4 February 2005,rmax304823,Fargo
1,Another jewel from the Coens,"This movie opens with the words ""This is a tru...",9,31 July 2015,AlsExGal,Fargo
2,The Best Effort From A Number Of People,I didn't see this in the theater but saw it th...,10,24 November 2006,ccthemovieman-1,Fargo
3,One of Those Rare Gems in the Cinema,With all the sorry films these days it is good...,-,25 June 2000,tfrizzell,Fargo
4,I'd score this a 10/10 and is an American fil...,Fargo (1996) is a movie I recently watched aga...,10,19 June 2021,kevin_robbins,Fargo

Gran Torino

,titlu,text,rating,data,utilizator,film
0,Yet another Eastwood gem,I feel like I should let everyone reading this...,-,15 December 2008,ametaphysicalshark,Gran Torino
1,Gran Torino,Clint Eastwood is simply great both in front o...,9,21 January 2021,dk777,Gran Torino
2,Clint's best performance since Million Dollar...,I saw Gran Torino opening weekend and after he...,9,22 March 2009,Smells_Like_Cheese,Gran Torino
3,Clint Eastwood shows you why he still should ...,With his performance Eastwood shows you why pe...,10,16 December 2008,woljm45,Gran Torino
4,Eastwood excels at storytelling,Gran Torino - They don't make them like they u...,-,14 December 2008,Kevin-42,Gran Torino

My Neighbor Totoro

,titlu,text,rating,data,utilizator,film
0,Stunning,"I am a huge Studio Ghibli/Miyazaki fan, and My...",10,23 November 2010,TheLittleSongbird,My Neighbor Totoro
1,Another miracle from Hayao Miyazaki,I absolutely agree with Roger Ebert who called...,10,15 October 2007,Galina_movie_fan,My Neighbor Totoro
2,I loved the film but know there are now three...,Although so many reviews have been written her...,10,24 June 2005,planktonrules,My Neighbor Totoro
3,cute and sweet,Professor Tatsuo Kusakabe moves his daughters ...,8,16 October 2016,SnoopyStyle,My Neighbor Totoro
4,This is a great film!,There is no compulsory villain in this wonderf...,10,1 January 2005,Spectravideo,My Neighbor Totoro

Catch Me If You Can

,titlu,text,rating,data,utilizator,film
0,Witty con man.,From the opening credits design we get in the ...,10,24 January 2003,jotix100,Catch Me If You Can
1,A lot of fun,While watching 'Catch Me If You Can' I had so ...,9,8 June 2003,rbverhoef,Catch Me If You Can
2,"Top-notch, brilliantly crafted entertainment,...",What a terrific piece of film-making! From the...,-,5 June 2010,J. Spurlin,Catch Me If You Can
3,Very good film has those Spielberg edges!,At first I thought I was going to see a lightw...,7,18 March 2003,rosscinema,Catch Me If You Can
4,Hard to believe its true,I Don't know how accurate these events are but...,8,17 January 2005,mjw2305,Catch Me If You Can

Million Dollar Baby

,titlu,text,rating,data,utilizator,film
0,Million Dollar Baby,"A very sad movie, Frankie and Maggie's relatio...",9,9 December 2020,auuwws,Million Dollar Baby
1,A movie that will last,"""Million Dollar Baby"" has great characters, bu...",-,8 January 2005,NoArrow,Million Dollar Baby
2,It Doesn't Get Better Than This,I'm not sure Clint Eastwood shouldn't have jus...,10,17 May 2008,bkoganbing,Million Dollar Baby
3,A Punch In The Stomach,"I don't know why, but I went into the theater ...",9,20 March 2005,marcosaguado,Million Dollar Baby
4,Superb!,Clint Eastwood is a legendary film personality...,8,21 August 2010,namashi_1,Million Dollar Baby

Children of Heaven

,titlu,text,rating,data,utilizator,film
0,a work of art,"The wonderful Iranian film ""Children of Heaven...",-,4 January 2000,Buddy-51,Children of Heaven
1,Wonderfully heartwarming,"Wow, what can I say? Every bit of this film is...",-,9 March 2003,Gordon-11,Children of Heaven
2,"This Film So Overwhelmed Me With Joy, I Feel ...","From Pasto, Colombia--Via: L. A. CA., CALI, CO...",10,25 October 2013,KissEnglishPasto,Children of Heaven
3,Wholesome 100% natural cinematic staple -- we...,This translates to MUST-SEE! It's a credulous ...,10,16 February 1999,ruby_fff,Children of Heaven
4,Oh those golden childhood days...,Majid Majidi's Bacheha-Ye Aseman is a fascinat...,9,1 March 2011,Peter_Young,Children of Heaven

Blade Runner

,titlu,text,rating,data,utilizator,film
0,A Milestone Of Science Fiction And A Cyberpun...,A feast for the eyes. Dark and uncompromising....,-,11 February 2018,gogoschka-1,Blade Runner
1,"A glorious, timeless nightmare","Dark, deep, uncertain, unsettling  imagine th...",10,25 July 2006,Flagrant-Baronessa,Blade Runner
2,An incredibly beautiful-looking film as one w...,"But it's almost like an art movie, the first s...",8,11 August 2008,Nazi_Fighter_David,Blade Runner
3,Best movie ever,Just my personal opinion. Everything is perfec...,10,10 May 2020,imuckenschnabl,Blade Runner
4,Still outshines the others 17 years later,Blade Runner belongs on a list of 2 or 3 movie...,9,5 August 1999,Ivan-28,Blade Runner

The Gold Rush

,titlu,text,rating,data,utilizator,film
0,Chaplin's best--what a film!,I've seen both version of this film--the origi...,10,28 April 2006,planktonrules,The Gold Rush
1,You just can't beat Charlie Chaplin!,The 1898 Gold Rush to Alaska may have been har...,10,13 May 2005,lee_eisenberg,The Gold Rush
2,A Worthy Silent Classic,This silent classic has many strong points - i...,-,6 August 2001,Snow Leopard,The Gold Rush
3,Charlie Chaplin at his best.,"The Gold Rush is one of Chaplin's best films, ...",10,15 May 2001,Anonymous_Maxine,The Gold Rush
4,Striking Gold Again and Again.,"Charles Chaplin's ""The Gold Rush"" is arguably ...",-,7 November 2003,tfrizzell,The Gold Rush

Before Sunrise

,titlu,text,rating,data,utilizator,film
0,"A Perfect Chemistry, In One of the Most Beaut...","While traveling by train through Europe, the A...",10,30 March 2005,claudio_carvalho,Before Sunrise
1,Casablanca for the 1990's - pure cinematic gold,Before Sunrise is romance for the slacker gene...,9,11 February 2005,The_Void,Before Sunrise
2,refreshing first date,American tourist Jesse (Ethan Hawke) meets Fre...,8,9 April 2015,SnoopyStyle,Before Sunrise
3,Love Still Exists.,This has to be one of the most sincere and tou...,10,14 August 1998,Sickfrog,Before Sunrise
4,One of the best films of the 1990s,I had never heard of this film before a couple...,10,8 February 2001,zetes,Before Sunrise

Klaus

,titlu,text,rating,data,utilizator,film
0,"In a sea of generic Christmas movies, Klaus s...",Klaus is an amusing new twist on a very old st...,8,22 December 2019,cricketbat,Klaus
1,"Wow, we finally have a new Christmas classic","Okay, when it comes to Christmas movies to me ...",9,14 November 2019,Joejoesan,Klaus
2,"Never thought I'd give a ""sappy"" cartoon a 10...","Sure, sappiness is cute, and fun to indulge in...",10,16 November 2019,andymhancock,Klaus
3,My Christmas watchlist just got a little longer,Everything about this droll take on the Santa ...,10,9 December 2019,CubsandCulture,Klaus
4,Claus.,Whilst I was vaguely aware of the title from s...,10,28 December 2020,morrison-dylan-fan,Klaus

12 Years a Slave

,titlu,text,rating,data,utilizator,film
0,Slavery is an evil that should befall none,12 Years a Slave tells the true story of Solom...,10,25 October 2013,BackFire83,12 Years a Slave
1,Roll Jordan Roll,A random and encounter has led Solomon Northup...,9,18 October 2013,dvc5159,12 Years a Slave
2,nothing can show us the full brutality of sla...,Solomon Northup's story of his kidnapping and ...,10,20 April 2014,lee_eisenberg,12 Years a Slave
3,McQueen's epic is beautiful and tragic anchor...,Read More @ The Awards Circuit (http://www.awa...,10,14 September 2013,ClaytonDavis,12 Years a Slave
4,"Live, not just Survive",Greetings again from the darkness. Should this...,8,27 October 2013,ferguson-6,12 Years a Slave

Harry Potter and the Deathly Hallows: Part 2

,titlu,text,rating,data,utilizator,film
0,"Gives meaning to the phrase, save the best un...",I have enjoyed all the films and love the book...,9,16 July 2011,TheLittleSongbird,Harry Potter and the Deathly Hallows: Part 2
1,LIGHTNING HAS STRUCK,Perhaps this is the best place to review the s...,10,3 December 2018,nogodnomasters,Harry Potter and the Deathly Hallows: Part 2
2,The series ends on a very strong note.,The conclusion to the series hits some of the ...,8,30 April 2018,Pjtaylor-96-138044,Harry Potter and the Deathly Hallows: Part 2
3,Satisfying end to the series,This movie continues right after the death of ...,7,2 January 2014,SnoopyStyle,Harry Potter and the Deathly Hallows: Part 2
4,End of an era... End of our childhoods... End...,What can I say... This was by far the most ama...,-,15 July 2011,vila-ddt,Harry Potter and the Deathly Hallows: Part 2

On the Waterfront

,titlu,text,rating,data,utilizator,film
0,Kazan's film constitutes an extraordinary tou...,"""On the Waterfront"" is basically the story of ...",10,4 May 2008,Nazi_Fighter_David,On the Waterfront
1,"Powerful portrait of N.Y. docks , being stunn...",This compelling and dynamic drama is set on Ne...,8,4 May 2012,ma-cortes,On the Waterfront
2,A Few Side Remarks on a Consensus Classic,"No need to echo consensus points, except to sa...",-,9 March 2014,dougdoepke,On the Waterfront
3,A classic for all the right reasons,"Watching On The Waterfront nowadays, two scene...",9,31 March 2008,ExpendableMan,On the Waterfront
4,Magnificent statement about the power of one,"""All that is necessary for the triumph of evil...",10,6 February 2007,blanche-2,On the Waterfront

Ben-Hur

,titlu,text,rating,data,utilizator,film
0,Epic,When I first saw 'Ben Hur' I was 8 years old a...,10,15 November 2015,gogoschka-1,Ben-Hur
1,The Tale of all Tales...,"In the ears and minds of any movie lover, the ...",10,4 January 2018,ElMaruecan82,Ben-Hur
2,pretty much sets the bar for epic entertainment,We are by nature a cynical and critical group....,10,10 March 2015,A_Different_Drummer,Ben-Hur
3,One of the Top Five Films of All Time!,Anyone want to know how to make a darned good ...,10,20 April 2003,lambiepie-2,Ben-Hur
4,Film-making on a truly epic scale,What's not to love about BEN-HUR? It's a film ...,10,22 June 2012,Leofwine_draca,Ben-Hur

The Grand Budapest Hotel

,titlu,text,rating,data,utilizator,film
0,A hotel well worth revisiting more than once,That it was directed by Wes Anderson (who has ...,9,5 August 2016,TheLittleSongbird,The Grand Budapest Hotel
1,Strange and pretty much impossible to describe.,Wes Anderson's films are really hard to descri...,8,15 June 2014,planktonrules,The Grand Budapest Hotel
2,"Absurd, funny, exciting, violent and colourful","Can a film be absurd, funny, exciting, violent...",8,15 March 2014,rubenm,The Grand Budapest Hotel
3,Keep your hands off my lobby boy!,"The Grand Hotel Budapest is a zany, colorful a...",8,4 February 2015,lastliberal-853-253708,The Grand Budapest Hotel
4,A Grand Adventure,Wes Anderson is one of the most original film ...,-,8 February 2014,corrosion-2,The Grand Budapest Hotel

Gone Girl

,titlu,text,rating,data,utilizator,film
0,What a crime thriller should be,I like it when a movie can keep me guessing un...,8,11 October 2018,cricketbat,Gone Girl
1,"Mixed feelings, hear me out.",There's no denying that this is a great film a...,9,18 May 2020,cmalpelli,Gone Girl
2,"A Cynical, Masterful Caricature of Modern Rel...","Amy and Nick Dunne are young, stylish and char...",10,1 August 2017,manisimmati,Gone Girl
3,"Gone, but definitely not forgotten","Wow, actually a thriller that's pretty good. Y...",8,22 April 2015,bowmanblue,Gone Girl
4,Interesting end,This is a 2.5 hour movie and sometimes these d...,8,7 August 2018,bgar-80932,Gone Girl

Wild Strawberries

,titlu,text,rating,data,utilizator,film
0,exceptionally well made,Although I'm not the biggest Ingmar Bergman fa...,9,10 July 2005,planktonrules,Wild Strawberries
1,When film was an art form,In this symbolic tale of an old man's journey ...,10,21 June 2004,DennisLittrell,Wild Strawberries
2,Stunning Bergman Masterpiece -- Maybe His Best?,"""Wild Strawberries"" profoundly moved me. The t...",10,20 September 2006,evanston_dad,Wild Strawberries
3,"One of Master's Most Optimistic, Profound, An...","I first saw ""Wild Strawberries"" many years ago...",10,7 July 2005,Galina_movie_fan,Wild Strawberries
4,One last time around the strawberry patch.,(Slight Spoilers) A man's life journey is all ...,8,29 December 2006,sol-kay,Wild Strawberries

The General

,titlu,text,rating,data,utilizator,film
0,The Genius of Buster Keaton,"Probably Buster Keaton's best film, and oddly ...",9,17 April 2001,MadReviewer,The General
1,Loco and Motive,"No one will top Keaton for physical risk, and ...",-,14 May 2008,tedg,The General
2,Understated Perfection,Buster Keaton once said that if he hadn't been...,10,21 June 2006,imogensara_smith,The General
3,Buster Keaton at his best,It's 1861. Johnnie Gray (Buster Keaton) is a t...,8,19 February 2014,SnoopyStyle,The General
4,The Greatest War Comedy ?,"It is ""generally"" (or should I pun and say ""Ge...",10,27 May 2006,theowinthrop,The General

The Third Man

,titlu,text,rating,data,utilizator,film
0,fantastic film that takes place in postwar Vi...,"Even today in Vienna, one can take the ""Third ...",10,6 February 2016,blanche-2,The Third Man
1,A Few Personal Notes,No need to recap the oft-repeated plot. So why...,-,9 November 2015,dougdoepke,The Third Man
2,Simply Beautiful,I don't know why this movie always hooks me th...,10,11 December 2015,gogoschka-1,The Third Man
3,Vienna Without a Waltz,"Although I am as old as this movie, produced i...",9,26 October 2016,frankwiener,The Third Man
4,Confused ethics in a devastated world,"""The Third Man"" is widely considered as the be...",10,31 March 2016,Teyss,The Third Man

In the Name of the Father

,titlu,text,rating,data,utilizator,film
0,Guilty Until Proven Innocent...,You're left wondering how many people over the...,8,6 October 2020,Xstal,In the Name of the Father
1,Stunning.,Words cannot accurately describe how affecting...,10,29 March 2001,Howlin Wolf,In the Name of the Father
2,"Extremeley Powerful, With Superb Performances",A film fully deserving to be in IMDb's top 250...,10,2 September 2005,jcanettis,In the Name of the Father
3,Innocence Is Not An Absolute,"Like MIDNIGHT EXPRESS , IN THE NAME OF THE FAT...",7,9 August 2002,Theo Robertson,In the Name of the Father
4,A Very Sharp Film,What a clever film this was. Quite modest yet ...,-,25 July 1999,genius-15,In the Name of the Father

The Deer Hunter

,titlu,text,rating,data,utilizator,film
0,It was 1978 and everyone in the audience was ...,"No, this is not the best film about the Vietna...",10,6 April 2006,yawn-2,The Deer Hunter
1,It's been given a fairly bad reputation over ...,"""One shot is what it's all about. A deer has t...",10,7 July 2004,MovieAddict2016,The Deer Hunter
2,A War Like All Wars A Film Like No Other,"""The Deer Hunter"" is 32 years old. How extraor...",10,31 January 2010,abelardo64,The Deer Hunter
3,Hard to Watch At Times!,1978's The Deer Hunter is one of the more pola...,9,18 October 2017,gab-14712,The Deer Hunter
4,War is a gamble.,I am a combat veteran of Afghanistan.We don't ...,10,20 October 2019,richardratliff,The Deer Hunter

Barry Lyndon

,titlu,text,rating,data,utilizator,film
0,Great Paintings Come To Life,Some movies - I wish there were more of them -...,10,20 April 2009,ccthemovieman-1,Barry Lyndon
1,I can't believe that there are people who fin...,In fact it's one of Kubrick's most gripping pi...,10,11 March 2002,Spleen,Barry Lyndon
2,""" good or bad, handsome or ugly, rich or poo...","The beauty, the depth, and the mystery of this...",10,18 May 2007,Galina_movie_fan,Barry Lyndon
3,The World of Stanley Kubrick: A young rapscal...,Barry Lyndon (1975) has to be Stanley Kubrick'...,10,3 November 2004,Captain_Couth,Barry Lyndon
4,A man at war with the cosmos,"Kubrick's ""Barry Lyndon"" project was initially...",-,18 July 2007,tieman64,Barry Lyndon

Hacksaw Ridge

,titlu,text,rating,data,utilizator,film
0,Hacksaw Ridge,Another WWII movie but instead of D-Day and th...,-,11 February 2020,MrHeraclius,Hacksaw Ridge
1,War movie masterwork,Mel Gibson is a director with two masterpieces...,10,10 September 2017,Leofwine_draca,Hacksaw Ridge
2,At The Very Center Of It All,We knew already that Mel Gibson is a filmmaker...,9,28 January 2017,littlemartinarocena,Hacksaw Ridge
3,Back on the battlefield with Mel...,I was lucky enough to sneak into a cast & crew...,8,9 October 2016,DukeEman,Hacksaw Ridge
4,Welcome back Mr Gibson,"When thinking about war films, it's very hard ...",10,25 September 2016,bartonj2410,Hacksaw Ridge

The Wages of Fear

,titlu,text,rating,data,utilizator,film
0,"Tense, fearless","In The Wages of Fear, four men in a remote Sou...",8,9 July 2016,dfranzen70,The Wages of Fear
1,A gripping action film and a powerful study o...,"""The Wages of Fear"" was awarded by unanimous v...",9,19 November 2006,Galina_movie_fan,The Wages of Fear
2,A brilliant thriller. One of the most suspens...,Clouzot rarely gets the attention he deserves....,-,3 February 2003,Infofreak,The Wages of Fear
3,"Enthralling, nail-biting drama","In a remote South American town, four men are ...",9,26 May 2018,grantss,The Wages of Fear
4,it starts off slow and ends with a bang!,The first quarter of this movie was not partic...,9,16 July 2005,planktonrules,The Wages of Fear

Memories of Murder

,titlu,text,rating,data,utilizator,film
0,The Shaman's Eyes,"Joon-ho Bong directs ""Memories of Murder"". A p...",-,23 February 2009,tieman64,Memories of Murder
1,The Slow Development of a Masterpiece,This is probably the best crime thriller I've ...,9,15 July 2005,WriterDave,Memories of Murder
2,Great serial killer drama,I'm one of those people who tend to think that...,9,1 January 2005,AKS-6,Memories of Murder
3,Must See,After two women are found dead in a rural comm...,8,10 December 2004,dbborroughs,Memories of Murder
4,"Do watch out for The flying kick, my favorite...",I first saw this more than a decade ago n love...,10,2 June 2021,Fella_shibby,Memories of Murder

Sherlock Jr.

,titlu,text,rating,data,utilizator,film
0,Astounding Creativity,It's almost impossible to describe the astound...,-,19 July 2001,Snow Leopard,Sherlock Jr.
1,Through the Movie Screen,Buster Keaton's most surreal movie sprang from...,9,13 September 2006,imogensara_smith,Sherlock Jr.
2,Anything but Elementary...,You can only marvel at the craft of Buster Kea...,8,17 September 2020,Xstal,Sherlock Jr.
3,marvellous and inventive,This Keaton classic is both funny and extremel...,9,16 September 2006,didi-5,Sherlock Jr.
4,A World of Possibilities,"Not only is this Buster Keaton's best film, bu...",10,5 March 2006,up2u,Sherlock Jr.

Wild Tales

,titlu,text,rating,data,utilizator,film
0,"I love, Love, LOVE this film.","Not only is the acting fantastic, but every si...",9,15 May 2020,Her-Excellency,Wild Tales
1,Brilliant,Perhaps the best omnibus dark comedy ever made...,10,20 July 2018,perica-43151,Wild Tales
2,The Edge Of Reason,"Hilarious and very, very black comedy consisti...",8,11 February 2018,gogoschka-1,Wild Tales
3,animals of the human world,"Damián Szifron's ""Relatos salvajes"" (""Wild Tal...",10,19 July 2015,lee_eisenberg,Wild Tales
4,Big things have small beginnings,Never watched any Argentine/Spanish film befor...,8,21 May 2015,ahegde3149,Wild Tales

Mr. Smith Goes to Washington

,titlu,text,rating,data,utilizator,film
0,A National Treasure,James Stewart and Frank Capra. One needn't kn...,10,6 June 2000,FlickJunkie-2,Mr. Smith Goes to Washington
1,A 40ft Dive into a Tub of Water...,"Accomplished, honest and heartfelt, this will ...",9,27 September 2020,Xstal,Mr. Smith Goes to Washington
2,Want to Get Your View Across? Why Not Filibus...,"The media and those in Washington, D.C. cringe...",-,30 April 2004,tfrizzell,Mr. Smith Goes to Washington
3,Capra & Stewart Make It Work Very Well,Frank Capra and James Stewart were nearly unsu...,-,27 September 2004,Snow Leopard,Mr. Smith Goes to Washington
4,"Sure It's Cheesy, But Also Oh So Aspirational","Critics of ""Mr. Smith Goes to Washington"" will...",9,4 March 2017,zkonedog,Mr. Smith Goes to Washington

Mad Max: Fury Road

,titlu,text,rating,data,utilizator,film
0,Pure action spectacle,MAD MAX: FURY ROAD is the finest piece of pure...,10,24 February 2016,Leofwine_draca,Mad Max: Fury Road
1,Finally yes Finally I have seen a good Action...,When I wrote this review 3 years ago I had no ...,10,3 October 2015,ivo-cobra8,Mad Max: Fury Road
2,It Never Stops,I have to say that I tried really hard to like...,5,12 October 2015,Hitchcoc,Mad Max: Fury Road
3,Extremely Inflated,"Like the previous ""Mad Max"" movies this film t...",5,7 August 2015,Uriah43,Mad Max: Fury Road
4,What A Lovely Day!,The rationale behind the success of 'Fury Road...,-,25 May 2015,CalRhys,Mad Max: Fury Road

The Seventh Seal

,titlu,text,rating,data,utilizator,film
0,A masterpiece,In the magnificent 1957 classic The Seventh Se...,-,26 May 2003,howard.schumann,The Seventh Seal
1,The Quintessential Bergman Picture,One thing that can be certain after watching t...,10,25 July 2002,Quinoa1984,The Seventh Seal
2,"Chilling, audacious, and awe-inspiring. An un...",The mysteries of religion and death have long ...,-,5 May 2004,Cowman,The Seventh Seal
3,"Ingmar Bergman questions the meaning of life,...","Antonius Block - ""Who are you?"" Death - ""I am ...",10,1 January 2005,ACitizenCalledKane,The Seventh Seal
4,The Curse of Existence...,"An abstraction of your fears, conjured progres...",10,21 April 2020,Xstal,The Seventh Seal

Mary and Max

,titlu,text,rating,data,utilizator,film
0,Unforgettable and Heartbreaking Bleak Tale of...,"In 1976, in Australia, the misfit and outcast ...",9,3 September 2010,claudio_carvalho,Mary and Max
1,Refreshing and engaging given the home-grown ...,"In Australia in 1976, a young girl named Mary ...",8,10 April 2009,Likes_Ninjas90,Mary and Max
2,"Solitude, Isolation & Loneliness...","Masterfully directed, edited and animated to p...",8,25 October 2020,Xstal,Mary and Max
3,Mary & Max - wonderfully unique and personal ...,There's a constant stream of animated films th...,8,14 April 2009,MatthewInSydney,Mary and Max
4,lovely oddball and admirably complex,"Coming from Australia, Mary and Max is one of ...",10,22 March 2010,manicman84,Mary and Max

How to Train Your Dragon

,titlu,text,rating,data,utilizator,film
0,A Nutshell Review: How to Train Your Dragon,If this is done following the same old beat up...,10,18 March 2010,DICK STEEL,How to Train Your Dragon
1,One of the most Breathtaking Animated Films o...,I watched How to Train Your Dragon about 5 tim...,10,20 June 2010,The_Fifth_Echo,How to Train Your Dragon
2,Will enamour kids and enthrall adults,With a somewhat unwieldy tile and the lack of ...,9,12 April 2010,Simon_Says_Movies,How to Train Your Dragon
3,One of my favorite films of the last decade...,"...not that this is necessarily saying much, s...",9,13 May 2018,AlsExGal,How to Train Your Dragon
4,Truly Moving Picture,"I saw this film in early March, of 2010 in Ind...",10,8 March 2010,tollini,How to Train Your Dragon

Room

,titlu,text,rating,data,utilizator,film
0,Imagine yourself as a 5 year old child discov...,SPOILER: At the 2015 Toronto International Fil...,10,20 September 2015,Ed-Shullivan,Room
1,The acting is phenomenal!,Marvelous film. Captivating plot filled with m...,-,22 February 2020,MrHeraclius,Room
2,"A brilliant movie, but painful to watch",Room (2015/I) was directed by Lenny Abrahamson...,10,14 December 2015,Red-125,Room
3,A tense and compelling film,Lenny Abrahamson's Room opens in a 10 x 10 roo...,9,8 November 2015,howard.schumann,Room
4,A Harrowing Film with Incredible Performances!,Based on the novel of the same name by Emma Do...,9,19 December 2015,namashi_1,Room

Monsters, Inc.

,titlu,text,rating,data,utilizator,film
0,"Adorable, funny, perfect voice casting for th...",I thought Billy Crystal and John Goodman were ...,-,31 October 2004,vchimpanzee,"Monsters, Inc."
1,"Does For Monsters What ""Toy Story"" Did For Toys!","Monsters, Inc.We were all, at one time, scared...",10,12 March 2003,MovieAddict2016,"Monsters, Inc."
2,Adorable movie with top class entertainment.,The best way to describe this movie in one wor...,10,21 January 2004,Boba_Fett1138,"Monsters, Inc."
3,Nothing To Criticize Here - Very Solid Animat...,This is a very entertaining animated film. I'v...,9,10 July 2006,ccthemovieman-1,"Monsters, Inc."
4,"`Monsters, Inc.' is the best animated feature...",You may admire the hair detail on Sully the Ye...,-,25 October 2001,JohnDeSando,"Monsters, Inc."

Jaws

,titlu,text,rating,data,utilizator,film
0,"So Much More Than Just A ""Shark Movie""","Reputationally-speaking, ""Jaws"" will forever b...",10,6 March 2017,zkonedog,Jaws
1,One of the experiences that made me fall in l...,I will never forget the first time I saw Jaws....,10,17 December 2013,gogoschka-1,Jaws
2,Jaws,A man eating shark is terrorising the holiday ...,10,12 June 2008,hitchcockthelegend,Jaws
3,"Even with very dated technology, this is a gr...","Back in 1975, ""Jaws"" made a huge splash (pardo...",9,1 January 2022,planktonrules,Jaws
4,A monster of a movie,I re-watched this film recently and was blown ...,9,23 May 2017,fairlesssam,Jaws

Dead Poets Society

,titlu,text,rating,data,utilizator,film
0,A powerful antidote to conformism,There are certain films that get under your sk...,10,22 August 2001,fjhuerta-2,Dead Poets Society
1,Thank You Captain,It was with a sad reason that I re watched Dea...,9,12 August 2014,CMTiago,Dead Poets Society
2,Seize the Day- One of the Greatest Movies Ever!,Dead Poets Scoiety. I suppose if you were in H...,10,17 November 2008,fred-kolb,Dead Poets Society
3,A masterful tribute to teaching at its best,"Dead Poets Society is, to use a cliché, a cine...",10,3 March 2006,roghache,Dead Poets Society
4,The 9/10 movie I'll never watch again.,Personal Rating: 9/10This movie shattered me. ...,9,17 June 2020,Sethtro,Dead Poets Society

The Big Lebowski

,titlu,text,rating,data,utilizator,film
0,The film with the highest rewatchability fact...,It's actually kind of hard to describe this mo...,-,3 November 2015,gogoschka-1,The Big Lebowski
1,The Most Quotable Film of All Time,Those Coen brothers have an ear for language. ...,10,5 December 2002,OttoVonB,The Big Lebowski
2,My favourite Coen brothers movie and one of t...,My favourite Coen brothers movie changes over ...,-,27 December 2002,Infofreak,The Big Lebowski
3,Simply Beautiful,It's a travesty that most critics only read Th...,-,16 October 2004,butterfinger,The Big Lebowski
4,indeed a cult classic,More than 20 years it took me to have a look a...,8,12 April 2021,trashgang,The Big Lebowski

Tokyo Story

,titlu,text,rating,data,utilizator,film
0,Ozu's Quietly Brilliant Masterpiece Deserves ...,I think this movie is amazing for reasons I wa...,10,12 December 2005,EUyeshima,Tokyo Story
1,Universal appeal of Tokyo Story,"As with every great work, the film has its own...",9,22 March 2004,Galina_movie_fan,Tokyo Story
2,A cinema of tears,I can vividly remember the first time i saw th...,10,8 April 2007,GyatsoLa,Tokyo Story
3,Things are the way that they are and it is pe...,Ozu's Tokyo Story is a serene and contemplativ...,-,21 April 2003,howard.schumann,Tokyo Story
4,The excuses we make to justify our neglect of...,An appreciation of this movie may demand some ...,9,14 May 2002,KFL,Tokyo Story

The Passion of Joan of Arc

,titlu,text,rating,data,utilizator,film
0,"an incredible directorial vision, and a devas...",Carl Th. Dreyer's The Passion of Joan of Arc w...,10,7 February 2004,Quinoa1984,The Passion of Joan of Arc
1,When Film Becomes Transcendental Art.,It so often happens that some films take the l...,10,2 August 2005,nycritic,The Passion of Joan of Arc
2,Overwhelming Masterpiece...,I'm not sure what's more overwhelming in this ...,10,11 May 2020,Xstal,The Passion of Joan of Arc
3,The Good & Bad Of 'The Passion Of Joan Of Arc',"If you'll pardon the rambling, here are my tho...",8,16 January 2007,ccthemovieman-1,The Passion of Joan of Arc
4,When viewing it we look at it as looking in a...,What can one say about this work of art that h...,10,27 December 2004,GulyJimson,The Passion of Joan of Arc

Hotel Rwanda

,titlu,text,rating,data,utilizator,film
0,A fantastic and powerful film,I was fortunate to see this film at the Toront...,10,9 November 2004,Surecure,Hotel Rwanda
1,a great one,I have no doubt that this is the only movie fo...,-,4 January 2005,wl323,Hotel Rwanda
2,Shaming and compelling,Anything I say in this review is probably redu...,10,19 December 2004,larajane,Hotel Rwanda
3,A brilliant movie that deserved a Best Pictur...,"At one point in ""Hotel Rwanda,"" our hero Paul ...",8,16 February 2005,anhedonia,Hotel Rwanda
4,This year's Schindler's List,I was fortunate to see it at the Toronto Inter...,9,15 September 2004,Proud_Canadian,Hotel Rwanda

Ford v Ferrari

,titlu,text,rating,data,utilizator,film
0,special,I love Christian Bale. For each of his roles. ...,-,29 August 2020,Kirpianuscus,Ford v Ferrari
1,Entertaining In Every Way A Film Can Be,I've never watched a car race in my life. I ha...,9,17 February 2020,zkonedog,Ford v Ferrari
2,old fashion greatness,Racing champ Carroll Shelby (Matt Damon) has t...,8,24 February 2020,SnoopyStyle,Ford v Ferrari
3,Best Race Car Movie Ever?,Gut level racing movie with no need to manufac...,10,15 March 2022,Instant_Palmer,Ford v Ferrari
4,Puts my faith in the movie business again,This is what cinema is supposed to be! Amazing...,10,16 November 2019,g_cotterell,Ford v Ferrari

Rocky

,titlu,text,rating,data,utilizator,film
0,"""He doesn't know it's a show. He thinks it's ...",One gains a certain degree of perspective with...,10,2 January 2010,classicsoncall,Rocky
1,Yo!,Rocky Balboa (Sylvester Stallone) is a struggl...,10,24 February 2016,BA_Harrison,Rocky
2,The Raging Bull Named Rocky...,"""Rocky"" is about a man. It is the story of a m...",10,5 May 2003,MovieAddict2016,Rocky
3,A classic! the best and the original movie of...,Rocky (1976) It is still today one of the best...,10,3 November 2015,ivo-cobra8,Rocky
4,"""I ain't no bum, Mick. I ain't no bum.""",A first-rate film that's about as close to per...,10,6 July 2015,utgard14,Rocky

Platoon

,titlu,text,rating,data,utilizator,film
0,The quintessential Vietnam war movie,"It's September 1967, and Chris (Charlie Sheen)...",9,28 November 2013,SnoopyStyle,Platoon
1,A Realistic Vietnam film Oliver's Stone's mas...,Platoon is a 1986 American war film written an...,10,14 October 2015,ivo-cobra8,Platoon
2,Uncomfortable but very worthy view of war's i...,"At the height of the Vietnam War, America's te...",-,3 July 2002,bob the moo,Platoon
3,One Of The Best Movies Of The 1980s,The 1980s in general and the mid 1980s in part...,9,3 September 2003,Theo Robertson,Platoon
4,"""When I﻿ die, bury me upside-down, so the wor...",A+ Undoubtedly one of the best war films ever ...,10,4 January 2011,gigan-92,Platoon

Ratatouille

,titlu,text,rating,data,utilizator,film
0,"""Not everyone can become a great artist; but ...","That's what the food critic, Anton Ego, says i...",10,9 November 2018,cinephile-27690,Ratatouille
1,One of Pixar's best,This film is exactly what Pixar needed to stea...,10,9 July 2007,planktonrules,Ratatouille
2,Among the Greatest Animated Features,The absolutely absurd premise of a rat becomin...,10,4 May 2019,Hitchcoc,Ratatouille
3,A Feast for the Soul...,Taking great ingredients including but not lim...,9,18 October 2020,Xstal,Ratatouille
4,Best Animated Film in Creation,The combination of Disney and Pixar never ceas...,10,17 June 2007,PoisonKeyblade,Ratatouille

Spotlight

,titlu,text,rating,data,utilizator,film
0,It will leave you shaken....,"Before you consider watching ""Spotlight"", I ST...",10,9 August 2016,planktonrules,Spotlight
1,A heavy subject dealt with rivetingly,'Spotlight' to me was a very worthy Best Pictu...,10,12 June 2017,TheLittleSongbird,Spotlight
2,One of the greatest horror films of all time,... because by the time the credits roll and y...,10,23 December 2015,A_Different_Drummer,Spotlight
3,Not often that a film truly entertains as wel...,"Sometimes, a film of this type makes a real im...",9,17 June 2020,0w0,Spotlight
4,A movie that qualifies as strong meat a.k.a. ...,This movie undid something inside of me. It's ...,10,16 March 2016,miriam-seraia,Spotlight

The Terminator

,titlu,text,rating,data,utilizator,film
0,This is the movie that made a big break throu...,The Terminator is one of those films that no m...,10,4 August 2002,Smells_Like_Cheese,The Terminator
1,The best of the best in its genre...,Rarely has a film so frightened an audience as...,10,5 June 2003,MovieAddict2016,The Terminator
2,Nice night for a walk.,Is there a better person to play a cyborg than...,10,15 July 1999,baumer,The Terminator
3,Schwarzenegger's my personal favorite best ac...,"The Terminator (1984) is a masterpiece, the be...",10,5 January 2018,ivo-cobra8,The Terminator
4,The Terminator has heart. Cameron might be we...,Many people look back at the films of James Ca...,10,28 January 2011,axlrhodes,The Terminator

Logan

,titlu,text,rating,data,utilizator,film
0,Perfect film to end Wolverine's story,This really is one of the best superhero movie...,10,5 December 2020,artgutierrez,Logan
1,Logan,No words can explain the epicness & greatness ...,-,12 February 2020,MrHeraclius,Logan
2,"A gritty, more adult Wolverine film",It is 2029 and Logan is getting old and tired....,9,7 May 2018,Tweekums,Logan
3,The Wolverine movie we've all been waiting for,Thank you Deadpool for opening the door to R-r...,9,29 December 2018,vithiet,Logan
4,"Brutally violent, emotional, and character-dr...","""Logan"" is directed by James Mangold and stars...",10,2 March 2017,TheJediWay9,Logan

Stand by Me

,titlu,text,rating,data,utilizator,film
0,It's not a GUY'S film only,Without a doubt this movie is probably the bes...,10,3 December 2003,Smells_Like_Cheese,Stand by Me
1,One of the best adaptations of a Stephen King...,Stand By Me is yet another one of the stories ...,10,2 April 2001,Anonymous_Maxine,Stand by Me
2,World Before WiFi...,"If you grew up in the world before WiFi, a hig...",8,7 September 2020,Xstal,Stand by Me
3,Unforgettable,I saw Stand By Me yesterday for the first time...,10,10 August 2009,TheLittleSongbird,Stand by Me
4,A small masterpiece.,Growing up isn't easy for anyone. There are ti...,10,5 July 1999,Peach-2,Stand by Me

Rush

,titlu,text,rating,data,utilizator,film
0,Was really surprised by how good this was,"Despite not being an auto racing fan, the stor...",9,10 March 2016,TheLittleSongbird,Rush
1,Bound to win Academy Award nominations - and ...,"In 1976, the rivalry between two brilliant rac...",-,15 September 2013,rogerdarlington,Rush
2,Thrilling character study,As Asif Kapadia's gripping and extremely movin...,8,19 January 2014,tomgillespie2002,Rush
3,"A Gripping, Adrenaline-Ridden Fuel Ride From ...",Just come out the cinema in York from watching...,-,28 September 2013,CalRhys,Rush
4,A super cool movie,A super cool movie Beautiful story and wonderf...,9,3 June 2020,auuwws,Rush

Network

,titlu,text,rating,data,utilizator,film
0,"It Is More Than a Film, It Is Like a Crystal ...","""Network"". If there was ever a film that fores...",-,24 August 2001,tfrizzell,Network
1,The Age of Network,Thirty years after its release to public prais...,10,22 February 2005,nycritic,Network
2,One of the best of all time.,I can't put it more perfectly than Turner Clas...,10,8 January 2008,dead47548,Network
3,Prescient...,It is the only word I can come up with to desc...,9,28 August 2005,cchase,Network
4,A Great Film About 20 Years After & Before It...,"This film though not noticed enough now, is on...",9,19 February 2017,DKosty123,Network

Before Sunset

,titlu,text,rating,data,utilizator,film
0,The only problem...,...is that it ends. This is a fantastic film. ...,10,13 December 2004,ivko,Before Sunset
1,I'm designed to feel slightly dissatisfied!,I will be the first to announce that I was not...,10,20 November 2004,film-critic,Before Sunset
2,"Linklater, Delpy & Hawke make an impossible s...","""Before Sunrise"" was one of the most beautiful...",8,19 June 2004,Superunknovvn,Before Sunset
3,Suave sequel: a new genre is born,"""Before Sunset"" is one of those movies that lo...",-,30 July 2004,Chris Knipp,Before Sunset
4,Wow! Satisfying at so many levels,I had not seen the prequel to this although my...,10,14 August 2004,Bob Pr.,Before Sunset

Into the Wild

,titlu,text,rating,data,utilizator,film
0,"Beautiful Film, Even Better Than The Book",For a movie to be even better than a good book...,10,21 July 2009,ccthemovieman-1,Into the Wild
1,"""Is anybody here?""",I come away from this movie somewhat conflicte...,7,6 November 2017,classicsoncall,Into the Wild
2,"TIFF07, review 3: Facing the blind deaf stone...",Sean Penn's new movie Into the Wild arrives on...,9,16 September 2007,jaredmobarak,Into the Wild
3,missing the point...,I'm finding it hard to see why this film has t...,8,22 December 2009,komic09,Into the Wild
4,Sneaks Up On You,INTO THE WILD definitely works as a film - I h...,10,24 October 2007,shark-43,Into the Wild

The Wizard of Oz

,titlu,text,rating,data,utilizator,film
0,Still Has Its Magic,"Judy Garland's portrayal of Dorothy, Dorothy's...",-,27 September 2004,Snow Leopard,The Wizard of Oz
1,Timeless classic still entertaining the masse...,Dorothy is a young girl living on a Kansas far...,10,26 December 2008,hitchcockthelegend,The Wizard of Oz
2,My childhood favourite!,"I am 16, and I still love this movie. I grew u...",10,12 February 2009,TheLittleSongbird,The Wizard of Oz
3,A fantasy rooted in the landscape of your chi...,I have a theory that this movie has probably b...,-,30 May 2004,The_Film_Cricket,The Wizard of Oz
4,Finding Her Way Back Home -- To Our Hearts.,Even with the advance of special effects there...,10,13 November 2005,nycritic,The Wizard of Oz

Pather Panchali

,titlu,text,rating,data,utilizator,film
0,Absolutely Perfect. One of the best films eve...,It is a little known fact that India produces ...,10,21 October 2000,zetes,Pather Panchali
1,My favorite movie of all time.,I've been asked what my favorite film of all t...,-,26 August 2006,ItalianGerry,Pather Panchali
2,An Indian Classic,"Ray's ""Pather Panchali,"" the first of his unfo...",10,1 March 1999,harry-76,Pather Panchali
3,Am I missing something?,I usually don't like realistic slice-of-life d...,4,24 June 2022,briancham1994,Pather Panchali
4,An Asymmetric Kaleidoscope in Monochrome...,... but definitely not black and white. The li...,9,29 September 2021,Xstal,Pather Panchali

Groundhog Day

,titlu,text,rating,data,utilizator,film
0,Best romantic comedy ever,* May contain spoilers *Let's face it: everyon...,10,16 December 2013,gogoschka-1,Groundhog Day
1,"A perfect blend of comedy, clever plotting, a...",Even the funniest movies eventually stop makin...,10,21 October 2005,kylopod,Groundhog Day
2,Neglected Masterpiece,I thought the film was terrific when I saw it ...,10,21 August 2005,Ric-7,Groundhog Day
3,"Clever film making, showing substance and tal...","This is one warm, intelligent movie. It really...",10,29 August 2019,perica-43151,Groundhog Day
4,I got you babe,It's 2019 and I still watch this movie from ti...,9,30 June 2019,elijah-alcantara,Groundhog Day

The Best Years of Our Lives

,titlu,text,rating,data,utilizator,film
0,The People's War Veterans Return Home,One of the great things about The Best Years o...,10,23 April 2007,bkoganbing,The Best Years of Our Lives
1,Highly structured but flawless and really mov...,The Best Years of Our Lives (1946)The whole po...,10,4 October 2010,secondtake,The Best Years of Our Lives
2,Those Left Behind,Three WWII veterans return home to small-town ...,8,1 December 2014,gavin6942,The Best Years of Our Lives
3,Over 60 years old and still a classic!,"In 2004, I wrote the following statements on a...",10,22 February 2005,GMJames,The Best Years of Our Lives
4,The Troops are Coming Home.....,Though we had a plethora of films about troops...,9,9 May 2012,tim-764-291856,The Best Years of Our Lives

The Exorcist

,titlu,text,rating,data,utilizator,film
0,The truth about the Exorcist.,There's a lot of anxiety that goes into viewin...,-,21 September 2005,jaywolfenstien,The Exorcist
1,An intense and very terrifying movie that wil...,The Exorcist is one of the best movies to come...,10,3 August 2001,Smells_Like_Cheese,The Exorcist
2,The Devil Made Her Do It,"In late 1973 and early 1974, women and men wer...",10,20 July 2004,clydestuff,The Exorcist
3,The Exorcist,"Stunning visuals, effects and overall horror f...",8,21 October 2018,knersisman,The Exorcist
4,Still A Masterpiece After 45 Years,I recently revisited this film on Blu-ray afte...,10,6 August 2018,agro_sydney,The Exorcist

To Be or Not to Be

,titlu,text,rating,data,utilizator,film
0,A question of taste,A number of interest points here. A brilliant ...,10,17 April 2019,TheLittleSongbird,To Be or Not to Be
1,The Nazis have never been mocked better,Comedies rarely stand the test of time - this ...,10,20 December 2013,gogoschka-1,To Be or Not to Be
2,An Immortal Comedy,I'm not sure how many time I've seen it but it...,10,27 December 2018,littlemartinarocena,To Be or Not to Be
3,"Fiction can make fun of reality, that's the r...","""To Be or Not To Be"" doesn't trivialize the ba...",8,25 June 2019,ElMaruecan82,To Be or Not to Be
4,An indecent masterpiece,"As Adolf Hitler starts ravaging Europe, a poli...",9,17 June 2019,FrenchEddieFelson,To Be or Not to Be

The Incredibles

,titlu,text,rating,data,utilizator,film
0,One of the best films ever made,"17 years after incredibles was released, it co...",10,20 February 2021,evansjoshyr,The Incredibles
1,My favorite film from Pixar in over five year...,Writer-director Brad Bird here has something t...,10,5 November 2004,Quinoa1984,The Incredibles
2,"A Truly, Pardon the Pun, Incredible Movie",This is one of the finest animated films I hav...,-,13 November 2004,Sargebri,The Incredibles
3,Charming and fun,Shortly after Dreamworks screwed up with the u...,9,24 December 2004,basrutten,The Incredibles
4,"Wonderful, beautiful to watch, all in all, in...",WOW! What a movie. I can honestly say this is ...,10,21 November 2004,PyrolyticCarbon,The Incredibles

La haine

,titlu,text,rating,data,utilizator,film
0,"""...it's not how you fall that matters. It's ...",After watching this film I reflected back on a...,10,1 December 2017,classicsoncall,La haine
1,The most relevant French film of the last 20 ...,'Mean Streets' in french - and so much more. W...,10,22 December 2013,gogoschka-1,La haine
2,Hate Begets Hate,Reminiscent of Costas-Gavras' film Z with its ...,-,26 August 2002,howard.schumann,La haine
3,Great achievement. One of the most unforgetta...,La Haine aka Hate is a story about three frien...,10,17 May 2002,Bogey Man,La haine
4,the most important thing isn't the fall but t...,"""La Haine"", probably one of the most momentous...",8,2 May 2006,dbdumonteil,La haine

Pirates of the Caribbean: The Curse of the Black Pearl

,titlu,text,rating,data,utilizator,film
0,"""That's got to be the best pirate I've ever s...",If you're ever in the mood for just a flat out...,9,10 November 2017,classicsoncall,Pirates of the Caribbean: The Curse of the Bla...
1,"""You better start believing in ghost stories....",What a great line to describe probably the gre...,9,16 November 2020,mark.waltz,Pirates of the Caribbean: The Curse of the Bla...
2,Johnny Depp is fantastic!,"Awesome action and swashbuckling adventure, gr...",-,23 February 2020,MrHeraclius,Pirates of the Caribbean: The Curse of the Bla...
3,Terrific!,You will always remember this as the movie tha...,9,29 September 2005,MaxBorg89,Pirates of the Caribbean: The Curse of the Bla...
4,Phenomenal!,"If there was a minor quibble with the movie, i...",10,13 May 2009,TheLittleSongbird,Pirates of the Caribbean: The Curse of the Bla...

The Battle of Algiers

,titlu,text,rating,data,utilizator,film
0,No winners,Perhaps no other cinematic depiction of revolt...,-,23 February 2004,Chris Knipp,The Battle of Algiers
1,"It's hard to make a good movie, even harder 2...",..who had lived through the real battle.Direct...,10,3 August 2021,Fella_shibby,The Battle of Algiers
2,An unforgettable study of occupation and defeat.,In 1962 after more than 130 years of French co...,-,13 May 2004,JohnDeSando,The Battle of Algiers
3,Should be mandatory viewing for every American,"""Battle of Algiers"" is simply one of the great...",-,30 January 2004,Tony43,The Battle of Algiers
4,Excellent movie,I ask myself why we never see these kind of mo...,8,11 August 1999,Sigmund,The Battle of Algiers

Jai Bhim

,titlu,text,rating,data,utilizator,film
0,Jai Bhim,Excellent Movie. Everybody acted well in the m...,10,2 November 2021,santhosh-10290,Jai Bhim
1,OSCAR LEVEL 🔥,This is a movie which all the people in India ...,10,2 November 2021,ahamedmn,Jai Bhim
2,What a great film,I'm not a native tamil speaker but I had seen ...,7,2 November 2021,magadalwarmayur,Jai Bhim
3,Suriya's Jai Bhim Deserves To Get An Oscar Aw...,"In a scene in Jai Bhim, a group of tribals man...",10,3 November 2021,cs_rahul_kumar,Jai Bhim
4,The Powerful Film,The film is based on true story which was happ...,10,2 November 2021,rosheenkan,Jai Bhim

The Grapes of Wrath

,titlu,text,rating,data,utilizator,film
0,Economic Dislocation,John Ford's film of John Steinbeck's novel has...,10,1 October 2006,bkoganbing,The Grapes of Wrath
1,John Ford's stark portrayal of a poor family ...,The Grapes of Wrath is the story of the Joad f...,10,13 February 2001,Anonymous_Maxine,The Grapes of Wrath
2,"Not the Book, But Beautiful in Its Own Right","It's difficult on a first viewing of ""The Grap...",9,10 February 2006,evanston_dad,The Grapes of Wrath
3,Everyone should see Grapes of Wrath and be th...,"In rural Oklahoma, Tom Joad (Henry Fonda) is w...",10,16 April 2018,inkblot11,The Grapes of Wrath
4,A masterpiece...,"During most of the decade of the 30s, the Unit...",10,4 May 2007,jluis1984,The Grapes of Wrath

Hachi: A Dog's Tale

,titlu,text,rating,data,utilizator,film
0,Unprecedented loyalty in a story of age-old f...,"Knowing the real-life story behind it, Hachiko...",9,4 January 2010,Davor_Blazevic_1959,Hachi: A Dog's Tale
1,Couldn't stop crying,"I'm not at all an emotional person,but this mo...",10,4 December 2009,elish-enuma-1,Hachi: A Dog's Tale
2,Enough to make a grown man cry!,Hachi is a movie based on the true story about...,10,23 August 2009,JapanGaijin,Hachi: A Dog's Tale
3,Extremely Emotional,Well what can i say. I'm a guy i don't cry abo...,10,2 February 2010,surfer-lancealot,Hachi: A Dog's Tale
4,"""You want to wait for him, don't you?""","Oh my, hold everything. You want to be prepare...",8,29 November 2017,classicsoncall,Hachi: A Dog's Tale

My Father and My Son

,titlu,text,rating,data,utilizator,film
0,"""When a person grows up, do his dreams become...",I'm gradually becoming less and less surprised...,8,3 April 2018,classicsoncall,My Father and My Son
1,A masterpiece that must be seen by everyone!,A masterpiece that must be seen by everyone!It...,10,1 January 2010,denpolites,My Father and My Son
2,One of the best Turkish movies ever,The movie starts on the days of military gover...,8,5 December 2005,ydurgut,My Father and My Son
3,This movie will touch your soul and will not ...,**** 10 out of 10 for this movie **** One of t...,10,2 October 2006,matrixus-1,My Father and My Son
4,An Incredible Movie,"As I watched that movie, I saw the Turkish rel...",10,12 December 2005,ethernaldreams,My Father and My Son

Amores Perros

,titlu,text,rating,data,utilizator,film
0,A smartly modern elegy.,There is a character in 'Amores perros' who lo...,8,22 May 2001,the red duchess,Amores Perros
1,Doggie Holocaust makes for Best Mexican Film ...,Some people just won't want to sit through thi...,9,11 June 2003,WriterDave,Amores Perros
2,Brilliant movie! One of the best this decade...,'Amores Perros' impressed the hell out of me. ...,-,24 May 2002,Infofreak,Amores Perros
3,What a masterful feature film debut,Alejandro González Iñárritu's debut feature fi...,10,9 June 2017,TheLittleSongbird,Amores Perros
4,On Men And Dogs,This Mexican movie was surprisingly good. I co...,9,25 April 2003,dromasca,Amores Perros

Rebecca

,titlu,text,rating,data,utilizator,film
0,A film with a nameless protagonist and an inv...,This was Alfred Hitchcock's first American-mad...,9,15 January 2017,AlsExGal,Rebecca
1,If you want to be totally enthralled for two ...,"Hitchcock felt 'Rebecca', his first Hollywood ...",-,8 July 2004,Infofreak,Rebecca
2,Chilling and dramatic- a must see for Hitchco...,"I am 17, and I love this movie. One definite p...",10,15 June 2009,TheLittleSongbird,Rebecca
3,What Atmospheric Gothic-horror Should Be.,Alfred Hitchcock was and is still the undisput...,10,5 March 2005,nycritic,Rebecca
4,Place Holder,Hitchcock - never won an Oscar - not in the Be...,10,10 July 2021,kosmasp,Rebecca

Cool Hand Luke

,titlu,text,rating,data,utilizator,film
0,What we have here is no failure,Greetings again from the darkness. I went way ...,9,21 June 2012,ferguson-6,Cool Hand Luke
1,"""Luke"" is a character Newman was born to play...",This film got me from the first frame to the l...,10,18 December 2013,gogoschka-1,Cool Hand Luke
2,Newman's Brilliance,Cool Hand Luke (1967) **** (out of 4) Paul New...,-,13 October 2008,Michael_Elliott,Cool Hand Luke
3,"Not just a prison film, but an excellent film...",Having had the advantage of reading Donn Pearc...,10,10 February 2004,clydestuff,Cool Hand Luke
4,Prison classic with a career-best Newman,"On the face of it, Cool Hand Luke tells a simp...",9,5 February 2017,Leofwine_draca,Cool Hand Luke

The Handmaiden

,titlu,text,rating,data,utilizator,film
0,Engaging and attractively packaged and delivered,"I knew nothing about this film coming into it,...",-,29 March 2017,bob the moo,The Handmaiden
1,Masterclass Cinema,This is hands down the most perfect film I hav...,10,7 July 2016,ctowyi,The Handmaiden
2,Just amazing,"""The Handmaiden"" is a crazily imaginative and ...",10,5 August 2016,tenshi_ippikiookami,The Handmaiden
3,Classy South Korean Erotic Thriller Divided i...,"In Korea, the pickpocket Sook-Hee (Tae-ri Kim)...",8,1 January 2017,claudio_carvalho,The Handmaiden
4,will need a 2nd viewing. I mean that as a com...,The Handmaiden is a film that unfolds with a c...,8,20 November 2016,Quinoa1984,The Handmaiden

The 400 Blows

,titlu,text,rating,data,utilizator,film
0,"""N'Oublie Pas Les Ordures""","So here it is, the landmark film which ushered...",-,5 August 2000,stryker-5,The 400 Blows
1,One of the shining stars of the French New Wave,"Every day life, however 'real' and gritty it m...",8,20 September 2004,FilmOtaku,The 400 Blows
2,Truffaut's powerful and moving look at adoles...,THE FOUR HUNDRED BLOWS (François Truffaut - Fr...,-,18 November 2006,Camera-Obscura,The 400 Blows
3,Memorable Story With Thoughtful Direction By ...,"The memorable story of young, troubled Antoine...",-,17 May 2005,Snow Leopard,The 400 Blows
4,Deserved Truffaut Classic Benefits Significan...,"As the seminal work of the French New Wave, th...",9,20 May 2006,EUyeshima,The 400 Blows

The Sound of Music

,titlu,text,rating,data,utilizator,film
0,"Pure cinematic magic, won Best Picture of the...","Capitalizing on two ""hot"" properties of the ea...",10,11 December 2016,jacobs-greenwood,The Sound of Music
1,Fantastic family friendly musical classic,The Sound of Music (1965) is an all time class...,10,26 October 2017,davispittman,The Sound of Music
2,Just a classic that will never get old,Song and dance is definitely not my thing. How...,10,28 April 2018,brett-76260,The Sound of Music
3,Would you even want to solve a problem like M...,Sound of Music is one of the best musicals of ...,10,23 February 2005,Smells_Like_Cheese,The Sound of Music
4,We are alive with The Sound Of Music,"Let me confess I'm not a Catholic, I don't hav...",10,12 April 2017,duffjerroldorg,The Sound of Music

It Happened One Night

,titlu,text,rating,data,utilizator,film
0,The Hero As Comedian,"In his autobiography, The Name's Above the Tit...",10,24 December 2005,bkoganbing,It Happened One Night
1,"A Pleasant, Funny Classic","This is a pleasant, funny classic that shows i...",-,13 September 2001,Snow Leopard,It Happened One Night
2,Clean Sweep,"Consider this, ""It Happened One Night"" was mad...",9,8 November 2005,aimless-46,It Happened One Night
3,'The Limb is Mightier than the Thumb'...,"Many things don't mix or go together, quite of...",8,29 September 2020,Xstal,It Happened One Night
4,A cute romantic comedy that was a pioneer of ...,It Happened One Night is one of those films th...,8,11 December 2003,FilmOtaku,It Happened One Night

Persona

,titlu,text,rating,data,utilizator,film
0,A very powerful personal experience,"Ingmar Bergman's mystifying masterpiece, Perso...",-,21 October 2002,howard.schumann,Persona
1,'The human face is the great subject of the c...,"When talking of Bergman, critics and viewers u...",10,18 June 2004,Galina_movie_fan,Persona
2,A Masterpiece,PERSONA may well be Ingmar Bergman's most comp...,10,21 April 2005,gftbiloxi,Persona
3,"A brilliant film, but is not for everybody I ...",I can understand the viewpoints of those who l...,10,5 September 2012,TheLittleSongbird,Persona
4,"Complex, beautiful, and difficult. It's also ...",Four-fifths of the way into my second viewing ...,10,25 November 2019,davidmvining,Persona

Life of Brian

,titlu,text,rating,data,utilizator,film
0,One of the most intelligent comedies ever made,"Personally, I believe this to be one of the mo...",10,16 December 2013,gogoschka-1,Life of Brian
1,Ave Monty Python!,"This is, in my opinion, the best religious mov...",10,10 October 2005,lee_eisenberg,Life of Brian
2,Still one of the funniest films of all time.,It's impossible for me to be objective about t...,10,13 October 1999,alice liddell,Life of Brian
3,Utterly hilarious from start to finish!,Life of Brian may have caused controversy on r...,10,24 April 2010,TheLittleSongbird,Life of Brian
4,A Comment on Our Gullibility,This is such a fine movie. It involves a guy w...,10,21 December 2016,Hitchcoc,Life of Brian

The Iron Giant

,titlu,text,rating,data,utilizator,film
0,YES!!!!! NO SONG OR DANCE NUMBERS!!!!!!,"What a GREAT movie! Not just for kids, but adu...",10,6 August 1999,Wizard-8,The Iron Giant
1,Outstanding on all levels!,"The Iron Giant was a beautiful, funny and touc...",10,18 November 2009,TheLittleSongbird,The Iron Giant
2,"a masterpiece, plain and simple",I'm 25 years old. I have no children. So why...,10,29 December 1999,dpenny,The Iron Giant
3,An Absolute Wonder Which Cherishes Its Influe...,Animated movies have long been considered stri...,10,22 January 2000,Don-102,The Iron Giant
4,A delightful surprise,"""The Iron Giant"" is the kind of animated film ...",-,11 August 1999,Gouda-3,The Iron Giant

Dersu Uzala

,titlu,text,rating,data,utilizator,film
0,"a tribute to the endurance of man and nature,...",For a variety of reasons (that are well known ...,10,20 February 2005,Quinoa1984,Dersu Uzala
1,A great film from one of the all-time masters,This 1975 joint Japanese-Russian film is a cel...,-,6 May 2002,howard.schumann,Dersu Uzala
2,Art!,Akira Kurosawa was a masterful director and po...,9,9 July 2005,Spondonman,Dersu Uzala
3,A Man with a Beautiful Soul,"In 1902, a Russian army expedition is assigned...",9,5 December 2009,claudio_carvalho,Dersu Uzala
4,A Potpourri of Vestiges Review: Simplicity ca...,Dersu Uzala is not just the quintessence of pr...,10,22 January 2011,murtaza_mma,Dersu Uzala

The Help

,titlu,text,rating,data,utilizator,film
0,Minny Don't Burn Chicken,Greetings again from the darkness. The film is...,7,13 August 2011,ferguson-6,The Help
1,Ready to burst . . .,"I grew up in the 60's, the setting for The Hel...",-,11 August 2011,JohnDeSando,The Help
2,A Film to Remember,I took our 12 year old daughter to see this mo...,-,10 August 2011,taylor_king-890-815491,The Help
3,"Well-acted, emotionally satisfying human drama",There have been a number of films about the De...,8,1 November 2012,JamesHitchcock,The Help
4,A beautiful film--and realistic,If this film were total fiction bearing no rel...,-,13 September 2011,jwfuller,The Help

Aladdin

,titlu,text,rating,data,utilizator,film
0,I'd put it in with the Disney classics,Aladdin is such an awesome move that still get...,10,23 November 2003,Smells_Like_Cheese,Aladdin
1,"Great songs and a good villain make ""Aladdin""...",This movie has three elements that are importa...,9,23 October 2004,Boba_Fett1138,Aladdin
2,"Robin Williams, Great Songs Make This One Of ...",I can think of three quick reasons why this ha...,10,12 January 2007,ccthemovieman-1,Aladdin
3,Forever a favorite of mine ...,"I will never forget the first time I watched ""...",10,19 December 2011,ElMaruecan82,Aladdin
4,Vintage Robin Williams,"I did not care to see this movie, but I was su...",10,5 September 2001,aesgaard41,Aladdin

Gandhi

,titlu,text,rating,data,utilizator,film
0,Took nearly twenty years to make - not a sing...,Here indeed is one of the great films of the 2...,9,24 December 2001,khatcher-2,Gandhi
1,Old-Time Hollywood Epic Redux.,The life of the legendary man from India (domi...,-,24 September 2005,tfrizzell,Gandhi
2,Attenborough offers a tour de force performances,There is a sanctimonious air to the films of S...,10,19 June 2005,Nazi_Fighter_David,Gandhi
3,Beautiful Film,"""The object of this massive tribute died as he...",8,29 January 2002,Rod-88,Gandhi
4,"A true epic, in every sense of the word","Very, VERY few films have had the distinct abi...",-,15 September 2003,quixoboy,Gandhi

Dances with Wolves

,titlu,text,rating,data,utilizator,film
0,Fantastic,It's hard to think of blockbuster films that p...,9,12 April 2021,gbill-74877,Dances with Wolves
1,It is the trail of a true human being. I thin...,Dances With Wolves Is directed by Kevin Costne...,10,10 October 2010,hitchcockthelegend,Dances with Wolves
2,A legacy for all time...,I rember seeing this shortly after it came out...,10,14 February 2019,bheadher,Dances with Wolves
3,I love this movie!,It's hard for me to believe that fourteen year...,10,9 November 2004,PhilipJames1980,Dances with Wolves
4,The best film of all time,"Many people regard a lot of films as ""top clas...",10,28 May 2006,mattrochman,Dances with Wolves

3. Creati un dataset de recenzii, pentru fiecare recenzie stocati:
 * filmul caruia ii apartine
 * titlul recenziei
 * textul recenziei
 * ratingul
 * data
 * utilizator

 Salvati datasetul intr-un fisier JSON.

In [97]:
import json

# la exercitiul precedent am creat deja jsonul dorit
# acum trebuie doar sa il salvez intr-un fisier

with open('reviews.json', 'w') as fout:
    json.dump(reviews, fout, indent=4)

4. Pe o pagina cu recenzii putem gasi un numar mic de astfel de date. Butonul de "Load more" de la final, cand este apasat, produce un request care returneaza HTML-ul urmatoarelor recenzii. Folosind aceasta logica colectati automat pentru fiecare film un numar mai mare de recenzii.

In [99]:
import json

reviews = []
def movies_reviews():   
    for movie in movies:
      more_than_one_load(movie)

    with open('more_reviews.json', 'w') as fout:
        json.dump(reviews, fout, indent=4)

def more_than_one_load(movie):
    html = get_page(movie["url_review"]).content
    soup = parse_html(html)
    pages = 5
    loads = 1
    while soup is not None and pages >= loads:
      print(f"{movie['title']} {loads} load(s) => {number_of_reviews_displayed(soup)} reviews loaded")
      select_reviews(soup, movie)
      try:
        pagination_key = soup.find("div", class_="load-more-data").attrs['data-key']
        html = get_page(f"{movie['url_review']}/_ajax?ref_=undefined&paginationKey={pagination_key}").content
        soup = parse_html(html)
      except Exception:
        break
      loads += 1

def number_of_reviews_displayed(soup):
    review = soup.select("div.lister-list div.review-container div.lister-item-content")
    return len(review)

def select_reviews(soup, movie):
    review_list = soup.select("div.lister-list div.review-container div.lister-item-content")
    for review in review_list:
      titlu = re.sub("\n", "", review.select_one("a").text)    
      text = review.select_one("div.content div.text").text
      try:
        rating = int(review.select_one("span.rating-other-user-rating span").text)
      except Exception:  # daca userul nu a oferit un rating
        rating = "-"
      data = review.select_one("div.display-name-date span.review-date").text
      utilizator = review.select_one("div.display-name-date span.display-name-link a").text

      reviews.append({
          "titlu":titlu,
          "text":text,
          "rating":rating,
          "data":data,
          "utilizator":utilizator,
          "film":movie['title']
      })

movies_reviews()

The Shawshank Redemption 1 load(s) => 25 reviews loaded
The Shawshank Redemption 2 load(s) => 25 reviews loaded
The Shawshank Redemption 3 load(s) => 25 reviews loaded
The Shawshank Redemption 4 load(s) => 24 reviews loaded
The Shawshank Redemption 5 load(s) => 25 reviews loaded
The Godfather 1 load(s) => 25 reviews loaded
The Godfather 2 load(s) => 25 reviews loaded
The Godfather 3 load(s) => 25 reviews loaded
The Godfather 4 load(s) => 25 reviews loaded
The Godfather 5 load(s) => 25 reviews loaded
The Dark Knight 1 load(s) => 25 reviews loaded
The Dark Knight 2 load(s) => 25 reviews loaded
The Dark Knight 3 load(s) => 25 reviews loaded
The Dark Knight 4 load(s) => 25 reviews loaded
The Dark Knight 5 load(s) => 25 reviews loaded
The Godfather Part II 1 load(s) => 25 reviews loaded
The Godfather Part II 2 load(s) => 25 reviews loaded
The Godfather Part II 3 load(s) => 25 reviews loaded
The Godfather Part II 4 load(s) => 25 reviews loaded
The Godfather Part II 5 load(s) => 25 reviews loaded
12 Angry Men 1 load(s) => 25 reviews loaded
12 Angry Men 2 load(s) => 25 reviews loaded
12 Angry Men 3 load(s) => 25 reviews loaded
12 Angry Men 4 load(s) => 25 reviews loaded
12 Angry Men 5 load(s) => 25 reviews loaded
Schindler's List 1 load(s) => 25 reviews loaded
Schindler's List 2 load(s) => 25 reviews loaded
Schindler's List 3 load(s) => 25 reviews loaded
Schindler's List 4 load(s) => 25 reviews loaded
Schindler's List 5 load(s) => 25 reviews loaded
The Lord of the Rings: The Return of the King 1 load(s) => 25 reviews loaded
The Lord of the Rings: The Return of the King 2 load(s) => 25 reviews loaded
The Lord of the Rings: The Return of the King 3 load(s) => 25 reviews loaded
The Lord of the Rings: The Return of the King 4 load(s) => 25 reviews loaded
The Lord of the Rings: The Return of the King 5 load(s) => 25 reviews loaded
Pulp Fiction 1 load(s) => 25 reviews loaded
Pulp Fiction 2 load(s) => 25 reviews loaded
Pulp Fiction 3 load(s) => 25 reviews loaded
Pulp Fiction 4 load(s) => 25 reviews loaded
Pulp Fiction 5 load(s) => 25 reviews loaded
The Lord of the Rings: The Fellowship of the Ring 1 load(s) => 25 reviews loaded
The Lord of the Rings: The Fellowship of the Ring 2 load(s) => 25 reviews loaded
The Lord of the Rings: The Fellowship of the Ring 3 load(s) => 25 reviews loaded
The Lord of the Rings: The Fellowship of the Ring 4 load(s) => 25 reviews loaded
The Lord of the Rings: The Fellowship of the Ring 5 load(s) => 25 reviews loaded
The Good, the Bad and the Ugly 1 load(s) => 24 reviews loaded
The Good, the Bad and the Ugly 2 load(s) => 24 reviews loaded
The Good, the Bad and the Ugly 3 load(s) => 25 reviews loaded
The Good, the Bad and the Ugly 4 load(s) => 25 reviews loaded
The Good, the Bad and the Ugly 5 load(s) => 25 reviews loaded
Forrest Gump 1 load(s) => 25 reviews loaded
Forrest Gump 2 load(s) => 25 reviews loaded
Forrest Gump 3 load(s) => 25 reviews loaded
Forrest Gump 4 load(s) => 25 reviews loaded
Forrest Gump 5 load(s) => 25 reviews loaded
Fight Club 1 load(s) => 25 reviews loaded
Fight Club 2 load(s) => 25 reviews loaded
Fight Club 3 load(s) => 25 reviews loaded
Fight Club 4 load(s) => 25 reviews loaded
Fight Club 5 load(s) => 25 reviews loaded
The Lord of the Rings: The Two Towers 1 load(s) => 25 reviews loaded
The Lord of the Rings: The Two Towers 2 load(s) => 25 reviews loaded
The Lord of the Rings: The Two Towers 3 load(s) => 25 reviews loaded
The Lord of the Rings: The Two Towers 4 load(s) => 25 reviews loaded
The Lord of the Rings: The Two Towers 5 load(s) => 25 reviews loaded
Inception 1 load(s) => 25 reviews loaded
Inception 2 load(s) => 25 reviews loaded
Inception 3 load(s) => 25 reviews loaded
Inception 4 load(s) => 25 reviews loaded
Inception 5 load(s) => 25 reviews loaded
Star Wars: Episode V - The Empire Strikes Back 1 load(s) => 25 reviews loaded
Star Wars: Episode V - The Empire Strikes Back 2 load(s) => 25 reviews loaded
Star Wars: Episode V - The Empire Strikes Back 3 load(s) => 25 reviews loaded
Star Wars: Episode V - The Empire Strikes Back 4 load(s) => 25 reviews loaded
Star Wars: Episode V - The Empire Strikes Back 5 load(s) => 25 reviews loaded
The Matrix 1 load(s) => 25 reviews loaded
The Matrix 2 load(s) => 25 reviews loaded
The Matrix 3 load(s) => 25 reviews loaded
The Matrix 4 load(s) => 25 reviews loaded
The Matrix 5 load(s) => 25 reviews loaded
Goodfellas 1 load(s) => 25 reviews loaded
Goodfellas 2 load(s) => 25 reviews loaded
Goodfellas 3 load(s) => 25 reviews loaded
Goodfellas 4 load(s) => 25 reviews loaded
Goodfellas 5 load(s) => 25 reviews loaded
One Flew Over the Cuckoo's Nest 1 load(s) => 25 reviews loaded
One Flew Over the Cuckoo's Nest 2 load(s) => 25 reviews loaded
One Flew Over the Cuckoo's Nest 3 load(s) => 25 reviews loaded
One Flew Over the Cuckoo's Nest 4 load(s) => 24 reviews loaded
One Flew Over the Cuckoo's Nest 5 load(s) => 25 reviews loaded
Se7en 1 load(s) => 25 reviews loaded
Se7en 2 load(s) => 25 reviews loaded
Se7en 3 load(s) => 25 reviews loaded
Se7en 4 load(s) => 24 reviews loaded
Se7en 5 load(s) => 24 reviews loaded
Seven Samurai 1 load(s) => 25 reviews loaded
Seven Samurai 2 load(s) => 25 reviews loaded
Seven Samurai 3 load(s) => 25 reviews loaded
Seven Samurai 4 load(s) => 25 reviews loaded
Seven Samurai 5 load(s) => 25 reviews loaded
It's a Wonderful Life 1 load(s) => 25 reviews loaded
It's a Wonderful Life 2 load(s) => 25 reviews loaded
It's a Wonderful Life 3 load(s) => 25 reviews loaded
It's a Wonderful Life 4 load(s) => 25 reviews loaded
It's a Wonderful Life 5 load(s) => 25 reviews loaded
The Silence of the Lambs 1 load(s) => 25 reviews loaded
The Silence of the Lambs 2 load(s) => 25 reviews loaded
The Silence of the Lambs 3 load(s) => 25 reviews loaded
The Silence of the Lambs 4 load(s) => 25 reviews loaded
The Silence of the Lambs 5 load(s) => 25 reviews loaded
Saving Private Ryan 1 load(s) => 25 reviews loaded
Saving Private Ryan 2 load(s) => 25 reviews loaded
Saving Private Ryan 3 load(s) => 25 reviews loaded
Saving Private Ryan 4 load(s) => 25 reviews loaded
Saving Private Ryan 5 load(s) => 25 reviews loaded
City of God 1 load(s) => 25 reviews loaded
City of God 2 load(s) => 24 reviews loaded
City of God 3 load(s) => 24 reviews loaded
City of God 4 load(s) => 25 reviews loaded
City of God 5 load(s) => 25 reviews loaded
Interstellar 1 load(s) => 25 reviews loaded
Interstellar 2 load(s) => 25 reviews loaded
Interstellar 3 load(s) => 25 reviews loaded
Interstellar 4 load(s) => 25 reviews loaded
Interstellar 5 load(s) => 25 reviews loaded
Life Is Beautiful 1 load(s) => 25 reviews loaded
Life Is Beautiful 2 load(s) => 24 reviews loaded
Life Is Beautiful 3 load(s) => 24 reviews loaded
Life Is Beautiful 4 load(s) => 25 reviews loaded
Life Is Beautiful 5 load(s) => 25 reviews loaded
The Green Mile 1 load(s) => 25 reviews loaded
The Green Mile 2 load(s) => 25 reviews loaded
The Green Mile 3 load(s) => 25 reviews loaded
The Green Mile 4 load(s) => 24 reviews loaded
The Green Mile 5 load(s) => 25 reviews loaded
Star Wars: Episode IV - A New Hope 1 load(s) => 25 reviews loaded
Star Wars: Episode IV - A New Hope 2 load(s) => 24 reviews loaded
Star Wars: Episode IV - A New Hope 3 load(s) => 25 reviews loaded
Star Wars: Episode IV - A New Hope 4 load(s) => 25 reviews loaded
Star Wars: Episode IV - A New Hope 5 load(s) => 25 reviews loaded
Terminator 2: Judgment Day 1 load(s) => 25 reviews loaded
Terminator 2: Judgment Day 2 load(s) => 25 reviews loaded
Terminator 2: Judgment Day 3 load(s) => 25 reviews loaded
Terminator 2: Judgment Day 4 load(s) => 25 reviews loaded
Terminator 2: Judgment Day 5 load(s) => 25 reviews loaded
Back to the Future 1 load(s) => 25 reviews loaded
Back to the Future 2 load(s) => 25 reviews loaded
Back to the Future 3 load(s) => 25 reviews loaded
Back to the Future 4 load(s) => 25 reviews loaded
Back to the Future 5 load(s) => 25 reviews loaded
Spirited Away 1 load(s) => 25 reviews loaded
Spirited Away 2 load(s) => 25 reviews loaded
Spirited Away 3 load(s) => 25 reviews loaded
Spirited Away 4 load(s) => 25 reviews loaded
Spirited Away 5 load(s) => 25 reviews loaded
The Pianist 1 load(s) => 25 reviews loaded
The Pianist 2 load(s) => 25 reviews loaded
The Pianist 3 load(s) => 25 reviews loaded
The Pianist 4 load(s) => 25 reviews loaded
The Pianist 5 load(s) => 25 reviews loaded
Psycho 1 load(s) => 25 reviews loaded
Psycho 2 load(s) => 25 reviews loaded
Psycho 3 load(s) => 25 reviews loaded
Psycho 4 load(s) => 24 reviews loaded
Psycho 5 load(s) => 23 reviews loaded
Parasite 1 load(s) => 24 reviews loaded
Parasite 2 load(s) => 25 reviews loaded
Parasite 3 load(s) => 25 reviews loaded
Parasite 4 load(s) => 25 reviews loaded
Parasite 5 load(s) => 25 reviews loaded
Léon: The Professional 1 load(s) => 25 reviews loaded
Léon: The Professional 2 load(s) => 25 reviews loaded
Léon: The Professional 3 load(s) => 25 reviews loaded
Léon: The Professional 4 load(s) => 25 reviews loaded
Léon: The Professional 5 load(s) => 25 reviews loaded
The Lion King 1 load(s) => 25 reviews loaded
The Lion King 2 load(s) => 25 reviews loaded
The Lion King 3 load(s) => 25 reviews loaded
The Lion King 4 load(s) => 25 reviews loaded
The Lion King 5 load(s) => 25 reviews loaded
Gladiator 1 load(s) => 25 reviews loaded
Gladiator 2 load(s) => 25 reviews loaded
Gladiator 3 load(s) => 24 reviews loaded
Gladiator 4 load(s) => 25 reviews loaded
Gladiator 5 load(s) => 25 reviews loaded
American History X 1 load(s) => 25 reviews loaded
American History X 2 load(s) => 25 reviews loaded
American History X 3 load(s) => 24 reviews loaded
American History X 4 load(s) => 25 reviews loaded
American History X 5 load(s) => 25 reviews loaded
The Departed 1 load(s) => 25 reviews loaded
The Departed 2 load(s) => 25 reviews loaded
The Departed 3 load(s) => 25 reviews loaded
The Departed 4 load(s) => 25 reviews loaded
The Departed 5 load(s) => 25 reviews loaded
The Usual Suspects 1 load(s) => 25 reviews loaded
The Usual Suspects 2 load(s) => 25 reviews loaded
The Usual Suspects 3 load(s) => 25 reviews loaded
The Usual Suspects 4 load(s) => 22 reviews loaded
The Usual Suspects 5 load(s) => 25 reviews loaded
The Prestige 1 load(s) => 25 reviews loaded
The Prestige 2 load(s) => 25 reviews loaded
The Prestige 3 load(s) => 25 reviews loaded
The Prestige 4 load(s) => 25 reviews loaded
The Prestige 5 load(s) => 25 reviews loaded
Whiplash 1 load(s) => 25 reviews loaded
Whiplash 2 load(s) => 25 reviews loaded
Whiplash 3 load(s) => 25 reviews loaded
Whiplash 4 load(s) => 25 reviews loaded
Whiplash 5 load(s) => 25 reviews loaded
Casablanca 1 load(s) => 25 reviews loaded
Casablanca 2 load(s) => 25 reviews loaded
Casablanca 3 load(s) => 25 reviews loaded
Casablanca 4 load(s) => 25 reviews loaded
Casablanca 5 load(s) => 24 reviews loaded
Harakiri 1 load(s) => 25 reviews loaded
Harakiri 2 load(s) => 25 reviews loaded
Harakiri 3 load(s) => 25 reviews loaded
Harakiri 4 load(s) => 25 reviews loaded
Harakiri 5 load(s) => 25 reviews loaded
Grave of the Fireflies 1 load(s) => 25 reviews loaded
Grave of the Fireflies 2 load(s) => 25 reviews loaded
Grave of the Fireflies 3 load(s) => 25 reviews loaded
Grave of the Fireflies 4 load(s) => 25 reviews loaded
Grave of the Fireflies 5 load(s) => 25 reviews loaded
The Intouchables 1 load(s) => 25 reviews loaded
The Intouchables 2 load(s) => 25 reviews loaded
The Intouchables 3 load(s) => 25 reviews loaded
The Intouchables 4 load(s) => 25 reviews loaded
The Intouchables 5 load(s) => 25 reviews loaded
Modern Times 1 load(s) => 25 reviews loaded
Modern Times 2 load(s) => 25 reviews loaded
Modern Times 3 load(s) => 25 reviews loaded
Modern Times 4 load(s) => 24 reviews loaded
Modern Times 5 load(s) => 25 reviews loaded
Once Upon a Time in the West 1 load(s) => 25 reviews loaded
Once Upon a Time in the West 2 load(s) => 25 reviews loaded
Once Upon a Time in the West 3 load(s) => 25 reviews loaded
Once Upon a Time in the West 4 load(s) => 25 reviews loaded
Once Upon a Time in the West 5 load(s) => 25 reviews loaded
Rear Window 1 load(s) => 25 reviews loaded
Rear Window 2 load(s) => 25 reviews loaded
Rear Window 3 load(s) => 25 reviews loaded
Rear Window 4 load(s) => 25 reviews loaded
Rear Window 5 load(s) => 25 reviews loaded
Cinema Paradiso 1 load(s) => 25 reviews loaded
Cinema Paradiso 2 load(s) => 25 reviews loaded
Cinema Paradiso 3 load(s) => 25 reviews loaded
Cinema Paradiso 4 load(s) => 25 reviews loaded
Cinema Paradiso 5 load(s) => 25 reviews loaded
Alien 1 load(s) => 25 reviews loaded
Alien 2 load(s) => 25 reviews loaded
Alien 3 load(s) => 25 reviews loaded
Alien 4 load(s) => 25 reviews loaded
Alien 5 load(s) => 25 reviews loaded
City Lights 1 load(s) => 25 reviews loaded
City Lights 2 load(s) => 25 reviews loaded
City Lights 3 load(s) => 25 reviews loaded
City Lights 4 load(s) => 25 reviews loaded
City Lights 5 load(s) => 25 reviews loaded
Apocalypse Now 1 load(s) => 24 reviews loaded
Apocalypse Now 2 load(s) => 24 reviews loaded
Apocalypse Now 3 load(s) => 25 reviews loaded
Apocalypse Now 4 load(s) => 25 reviews loaded
Apocalypse Now 5 load(s) => 25 reviews loaded
Memento 1 load(s) => 25 reviews loaded
Memento 2 load(s) => 25 reviews loaded
Memento 3 load(s) => 25 reviews loaded
Memento 4 load(s) => 25 reviews loaded
Memento 5 load(s) => 25 reviews loaded
Django Unchained 1 load(s) => 25 reviews loaded
Django Unchained 2 load(s) => 25 reviews loaded
Django Unchained 3 load(s) => 25 reviews loaded
Django Unchained 4 load(s) => 24 reviews loaded
Django Unchained 5 load(s) => 25 reviews loaded
Indiana Jones and the Raiders of the Lost Ark 1 load(s) => 25 reviews loaded
Indiana Jones and the Raiders of the Lost Ark 2 load(s) => 25 reviews loaded
Indiana Jones and the Raiders of the Lost Ark 3 load(s) => 25 reviews loaded
Indiana Jones and the Raiders of the Lost Ark 4 load(s) => 25 reviews loaded
Indiana Jones and the Raiders of the Lost Ark 5 load(s) => 25 reviews loaded
WALL·E 1 load(s) => 25 reviews loaded
WALL·E 2 load(s) => 25 reviews loaded
WALL·E 3 load(s) => 25 reviews loaded
WALL·E 4 load(s) => 25 reviews loaded
WALL·E 5 load(s) => 25 reviews loaded
The Lives of Others 1 load(s) => 25 reviews loaded
The Lives of Others 2 load(s) => 25 reviews loaded
The Lives of Others 3 load(s) => 25 reviews loaded
The Lives of Others 4 load(s) => 25 reviews loaded
The Lives of Others 5 load(s) => 25 reviews loaded
Sunset Blvd. 1 load(s) => 25 reviews loaded
Sunset Blvd. 2 load(s) => 25 reviews loaded
Sunset Blvd. 3 load(s) => 25 reviews loaded
Sunset Blvd. 4 load(s) => 25 reviews loaded
Sunset Blvd. 5 load(s) => 25 reviews loaded
Paths of Glory 1 load(s) => 25 reviews loaded
Paths of Glory 2 load(s) => 25 reviews loaded
Paths of Glory 3 load(s) => 25 reviews loaded
Paths of Glory 4 load(s) => 25 reviews loaded
Paths of Glory 5 load(s) => 25 reviews loaded
The Shining 1 load(s) => 25 reviews loaded
The Shining 2 load(s) => 25 reviews loaded
The Shining 3 load(s) => 25 reviews loaded
The Shining 4 load(s) => 25 reviews loaded
The Shining 5 load(s) => 25 reviews loaded
The Great Dictator 1 load(s) => 25 reviews loaded
The Great Dictator 2 load(s) => 25 reviews loaded
The Great Dictator 3 load(s) => 25 reviews loaded
The Great Dictator 4 load(s) => 25 reviews loaded
The Great Dictator 5 load(s) => 24 reviews loaded
Avengers: Infinity War 1 load(s) => 25 reviews loaded
Avengers: Infinity War 2 load(s) => 25 reviews loaded
Avengers: Infinity War 3 load(s) => 25 reviews loaded
Avengers: Infinity War 4 load(s) => 25 reviews loaded
Avengers: Infinity War 5 load(s) => 25 reviews loaded
Witness for the Prosecution 1 load(s) => 25 reviews loaded
Witness for the Prosecution 2 load(s) => 25 reviews loaded
Witness for the Prosecution 3 load(s) => 25 reviews loaded
Witness for the Prosecution 4 load(s) => 25 reviews loaded
Witness for the Prosecution 5 load(s) => 25 reviews loaded
Aliens 1 load(s) => 25 reviews loaded
Aliens 2 load(s) => 25 reviews loaded
Aliens 3 load(s) => 25 reviews loaded
Aliens 4 load(s) => 25 reviews loaded
Aliens 5 load(s) => 25 reviews loaded
Spider-Man: Into the Spider-Verse 1 load(s) => 25 reviews loaded
Spider-Man: Into the Spider-Verse 2 load(s) => 25 reviews loaded
Spider-Man: Into the Spider-Verse 3 load(s) => 25 reviews loaded
Spider-Man: Into the Spider-Verse 4 load(s) => 25 reviews loaded
Spider-Man: Into the Spider-Verse 5 load(s) => 25 reviews loaded
American Beauty 1 load(s) => 24 reviews loaded
American Beauty 2 load(s) => 25 reviews loaded
American Beauty 3 load(s) => 25 reviews loaded
American Beauty 4 load(s) => 25 reviews loaded
American Beauty 5 load(s) => 24 reviews loaded
Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb 1 load(s) => 25 reviews loaded
Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb 2 load(s) => 25 reviews loaded
Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb 3 load(s) => 25 reviews loaded
Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb 4 load(s) => 24 reviews loaded
Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb 5 load(s) => 25 reviews loaded
The Dark Knight Rises 1 load(s) => 25 reviews loaded
The Dark Knight Rises 2 load(s) => 25 reviews loaded
The Dark Knight Rises 3 load(s) => 25 reviews loaded
The Dark Knight Rises 4 load(s) => 25 reviews loaded
The Dark Knight Rises 5 load(s) => 25 reviews loaded
Oldboy 1 load(s) => 25 reviews loaded
Oldboy 2 load(s) => 25 reviews loaded
Oldboy 3 load(s) => 25 reviews loaded
Oldboy 4 load(s) => 25 reviews loaded
Oldboy 5 load(s) => 25 reviews loaded
Inglourious Basterds 1 load(s) => 25 reviews loaded
Inglourious Basterds 2 load(s) => 25 reviews loaded
Inglourious Basterds 3 load(s) => 25 reviews loaded
Inglourious Basterds 4 load(s) => 25 reviews loaded
Inglourious Basterds 5 load(s) => 25 reviews loaded
Amadeus 1 load(s) => 25 reviews loaded
Amadeus 2 load(s) => 25 reviews loaded
Amadeus 3 load(s) => 25 reviews loaded
Amadeus 4 load(s) => 25 reviews loaded
Amadeus 5 load(s) => 25 reviews loaded
Coco 1 load(s) => 25 reviews loaded
Coco 2 load(s) => 25 reviews loaded
Coco 3 load(s) => 25 reviews loaded
Coco 4 load(s) => 25 reviews loaded
Coco 5 load(s) => 25 reviews loaded
Toy Story 1 load(s) => 24 reviews loaded
Toy Story 2 load(s) => 25 reviews loaded
Toy Story 3 load(s) => 24 reviews loaded
Toy Story 4 load(s) => 25 reviews loaded
Toy Story 5 load(s) => 25 reviews loaded
Joker 1 load(s) => 25 reviews loaded
Joker 2 load(s) => 25 reviews loaded
Joker 3 load(s) => 25 reviews loaded
Joker 4 load(s) => 25 reviews loaded
Joker 5 load(s) => 25 reviews loaded
Braveheart 1 load(s) => 25 reviews loaded
Braveheart 2 load(s) => 24 reviews loaded
Braveheart 3 load(s) => 25 reviews loaded
Braveheart 4 load(s) => 25 reviews loaded
Braveheart 5 load(s) => 25 reviews loaded
The Boat 1 load(s) => 25 reviews loaded
The Boat 2 load(s) => 25 reviews loaded
The Boat 3 load(s) => 25 reviews loaded
The Boat 4 load(s) => 25 reviews loaded
The Boat 5 load(s) => 25 reviews loaded
Avengers: Endgame 1 load(s) => 25 reviews loaded
Avengers: Endgame 2 load(s) => 25 reviews loaded
Avengers: Endgame 3 load(s) => 25 reviews loaded
Avengers: Endgame 4 load(s) => 25 reviews loaded
Avengers: Endgame 5 load(s) => 25 reviews loaded
Princess Mononoke 1 load(s) => 25 reviews loaded
Princess Mononoke 2 load(s) => 25 reviews loaded
Princess Mononoke 3 load(s) => 25 reviews loaded
Princess Mononoke 4 load(s) => 25 reviews loaded
Princess Mononoke 5 load(s) => 24 reviews loaded
Once Upon a Time in America 1 load(s) => 25 reviews loaded
Once Upon a Time in America 2 load(s) => 25 reviews loaded
Once Upon a Time in America 3 load(s) => 25 reviews loaded
Once Upon a Time in America 4 load(s) => 25 reviews loaded
Once Upon a Time in America 5 load(s) => 24 reviews loaded
Good Will Hunting 1 load(s) => 24 reviews loaded
Good Will Hunting 2 load(s) => 24 reviews loaded
Good Will Hunting 3 load(s) => 25 reviews loaded
Good Will Hunting 4 load(s) => 24 reviews loaded
Good Will Hunting 5 load(s) => 24 reviews loaded